var annotated =
[
    [ "COMMAND_INTERPRETER", "d3/db2/class_c_o_m_m_a_n_d___i_n_t_e_r_p_r_e_t_e_r.html", "d3/db2/class_c_o_m_m_a_n_d___i_n_t_e_r_p_r_e_t_e_r" ],
    [ "DEBUG_API", "d2/d0d/class_d_e_b_u_g___a_p_i.html", "d2/d0d/class_d_e_b_u_g___a_p_i" ],
    [ "DEBUG_CODES_STRUCT", "da/d71/struct_d_e_b_u_g___c_o_d_e_s___s_t_r_u_c_t.html", "da/d71/struct_d_e_b_u_g___c_o_d_e_s___s_t_r_u_c_t" ],
    [ "EMULATION_DEVICE", "de/d71/class_e_m_u_l_a_t_i_o_n___d_e_v_i_c_e.html", "de/d71/class_e_m_u_l_a_t_i_o_n___d_e_v_i_c_e" ],
    [ "error_message_t", "d2/d11/structerror__message__t.html", "d2/d11/structerror__message__t" ],
    [ "ERROR_TYPE_COUNTS", "d8/de9/struct_e_r_r_o_r___t_y_p_e___c_o_u_n_t_s.html", "d8/de9/struct_e_r_r_o_r___t_y_p_e___c_o_u_n_t_s" ],
    [ "local_command_t", "dc/d7f/structlocal__command__t.html", "dc/d7f/structlocal__command__t" ],
    [ "number_of_channels_t", "dc/da0/structnumber__of__channels__t.html", "dc/da0/structnumber__of__channels__t" ],
    [ "number_of_sensors_t", "dc/d53/structnumber__of__sensors__t.html", "dc/d53/structnumber__of__sensors__t" ],
    [ "NVRAM", "d0/df4/class_n_v_r_a_m.html", "d0/df4/class_n_v_r_a_m" ],
    [ "PACKET_DECODER", "d7/da1/class_p_a_c_k_e_t___d_e_c_o_d_e_r.html", "d7/da1/class_p_a_c_k_e_t___d_e_c_o_d_e_r" ],
    [ "packet_handler_t", "d0/d64/structpacket__handler__t.html", "d0/d64/structpacket__handler__t" ],
    [ "packet_header_t", "d8/d55/structpacket__header__t.html", "d8/d55/structpacket__header__t" ],
    [ "PACKET_PARSER", "d7/db5/class_p_a_c_k_e_t___p_a_r_s_e_r.html", "d7/db5/class_p_a_c_k_e_t___p_a_r_s_e_r" ],
    [ "remote_radio_configs_t", "de/d65/structremote__radio__configs__t.html", "de/d65/structremote__radio__configs__t" ],
    [ "remote_sensor_data_t", "dd/d60/classremote__sensor__data__t.html", null ],
    [ "router_ack_info_t", "dc/dff/structrouter__ack__info__t.html", "dc/dff/structrouter__ack__info__t" ],
    [ "router_debug_status_t", "dc/db9/structrouter__debug__status__t.html", "dc/db9/structrouter__debug__status__t" ],
    [ "router_heartbeat_t", "d7/dd5/structrouter__heartbeat__t.html", "d7/dd5/structrouter__heartbeat__t" ],
    [ "router_nmap_info_t", "d7/d27/structrouter__nmap__info__t.html", "d7/d27/structrouter__nmap__info__t" ],
    [ "router_sensor_enable_report_t", "d2/db8/structrouter__sensor__enable__report__t.html", "d2/db8/structrouter__sensor__enable__report__t" ],
    [ "router_status_info_t", "d3/d1a/structrouter__status__info__t.html", "d3/d1a/structrouter__status__info__t" ],
    [ "sensor_configs_t", "d5/dc2/classsensor__configs__t.html", null ],
    [ "USB_DEVICE", "d4/d27/class_u_s_b___d_e_v_i_c_e.html", "d4/d27/class_u_s_b___d_e_v_i_c_e" ],
    [ "USB_STATE_MACHINE", "df/df5/class_u_s_b___s_t_a_t_e___m_a_c_h_i_n_e.html", "df/df5/class_u_s_b___s_t_a_t_e___m_a_c_h_i_n_e" ],
    [ "usbRequest", "d6/dfa/structusb_request.html", "d6/dfa/structusb_request" ],
    [ "usbTxStatus", "d5/d74/structusb_tx_status.html", "d5/d74/structusb_tx_status" ],
    [ "usbWord", "de/d4d/unionusb_word.html", "de/d4d/unionusb_word" ],
    [ "WATCHDOG", "de/d42/class_w_a_t_c_h_d_o_g.html", "de/d42/class_w_a_t_c_h_d_o_g" ]
];