.TH "simpliciti/Applications/application/End Device/ Directory Reference" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpliciti/Applications/application/End Device/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain_ED_BM\&.c\fP"
.br
.in -1c
