.TH "Original Code/V2.2/simpliciti/Components/bsp/ Directory Reference" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/simpliciti/Components/bsp/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBboards\fP"
.br
.ti -1c
.RI "directory \fBdrivers\fP"
.br
.ti -1c
.RI "directory \fBmcus\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbsp\&.c\fP"
.br
.ti -1c
.RI "file \fBbsp\&.h\fP"
.br
.ti -1c
.RI "file \fBbsp_macros\&.h\fP"
.br
.in -1c
