.TH "simpliciti/Components/mrfi/ Directory Reference" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpliciti/Components/mrfi/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBradios\fP"
.br
.ti -1c
.RI "directory \fBsmartrf\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmrfi\&.c\fP"
.br
.ti -1c
.RI "file \fBmrfi\&.h\fP"
.br
.ti -1c
.RI "file \fBmrfi_defs\&.h\fP"
.br
.in -1c
