.TH "Original Code/V2.2/simpliciti/Components/bsp/boards/CC430EM/bsp_external/ Directory Reference" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/simpliciti/Components/bsp/boards/CC430EM/bsp_external/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmrfi_board_defs\&.h\fP"
.br
.in -1c
