.TH "Original Code/V2.2/logic/acceleration.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/logic/acceleration.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'vti_as\&.h'\fP
.br
\fC#include 'acceleration\&.h'\fP
.br
\fC#include 'agility\&.h'\fP
.br
\fC#include 'simpliciti\&.h'\fP
.br
\fC#include 'user\&.h'\fP
.br
\fC#include 'display2\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreset_acceleration\fP (void)"
.br
.ti -1c
.RI "void \fBsx_acceleration\fP (u8 line)"
.br
.ti -1c
.RI "u8 \fBacceleration_value_is_positive\fP (u8 value)"
.br
.ti -1c
.RI "\fBu16\fP \fBconvert_acceleration_value_to_mgrav\fP (u8 value)"
.br
.ti -1c
.RI "u8 \fBis_acceleration_measurement\fP (void)"
.br
.ti -1c
.RI "void \fBdo_acceleration_measurement\fP (void)"
.br
.ti -1c
.RI "void \fBdisplay_acceleration\fP (u8 line, u8 update)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBaccel\fP \fBsAccel\fP"
.br
.ti -1c
.RI "const \fBu16\fP \fBmgrav_per_bit\fP [7] = { 18, 36, 71, 143, 286, 571, 1142 }"
.br
.ti -1c
.RI "u8 \fBas_ok\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "u8 \fBacceleration_value_is_positive\fP (u8value)"
.PP
Definition at line 114 of file acceleration\&.c\&.
.SS "\fBu16\fP \fBconvert_acceleration_value_to_mgrav\fP (u8value)"
.PP
Definition at line 126 of file acceleration\&.c\&.
.SS "void \fBdisplay_acceleration\fP (u8line, u8update)"
.PP
Definition at line 185 of file acceleration\&.c\&.
.SS "void \fBdo_acceleration_measurement\fP (void)"
.PP
Definition at line 168 of file acceleration\&.c\&.
.SS "u8 \fBis_acceleration_measurement\fP (void)"
.PP
Definition at line 155 of file acceleration\&.c\&.
.SS "void \fBreset_acceleration\fP (void)"
.PP
Definition at line 77 of file acceleration\&.c\&.
.SS "void \fBsx_acceleration\fP (u8line)"
.PP
Definition at line 96 of file acceleration\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "u8 \fBas_ok\fP"
.PP
Definition at line 86 of file vti_as\&.c\&.
.SS "const \fBu16\fP \fBmgrav_per_bit\fP[7] = { 18, 36, 71, 143, 286, 571, 1142 }"
.PP
Definition at line 62 of file acceleration\&.c\&.
.SS "struct \fBaccel\fP \fBsAccel\fP"
.PP
Definition at line 59 of file acceleration\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
