.TH "Original Code/V2.2/logic/altitude.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/logic/altitude.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBalt\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBALTITUDE_MEASUREMENT_TIMEOUT\fP   (60*60u)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreset_altitude_measurement\fP (void)"
.br
.ti -1c
.RI "u8 \fBis_altitude_measurement\fP (void)"
.br
.ti -1c
.RI "void \fBstart_altitude_measurement\fP (void)"
.br
.ti -1c
.RI "void \fBstop_altitude_measurement\fP (void)"
.br
.ti -1c
.RI "void \fBdo_altitude_measurement\fP (u8 filter)"
.br
.ti -1c
.RI "void \fBsx_altitude\fP (u8 line)"
.br
.ti -1c
.RI "void \fBmx_altitude\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_altitude\fP (u8 line, u8 update)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBalt\fP \fBsAlt\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBALTITUDE_MEASUREMENT_TIMEOUT\fP   (60*60u)"
.PP
Definition at line 62 of file altitude\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBdisplay_altitude\fP (u8line, u8update)"
.PP
Definition at line 379 of file altitude\&.c\&.
.SS "void \fBdo_altitude_measurement\fP (u8filter)"
.PP
Definition at line 224 of file altitude\&.c\&.
.SS "u8 \fBis_altitude_measurement\fP (void)"
.PP
Definition at line 153 of file altitude\&.c\&.
.SS "void \fBmx_altitude\fP (u8line)"
.PP
Definition at line 284 of file altitude\&.c\&.
.SS "void \fBreset_altitude_measurement\fP (void)"
.PP
Definition at line 87 of file altitude\&.c\&.
.SS "void \fBstart_altitude_measurement\fP (void)"
.PP
Definition at line 165 of file altitude\&.c\&.
.SS "void \fBstop_altitude_measurement\fP (void)"
.PP
Definition at line 200 of file altitude\&.c\&.
.SS "void \fBsx_altitude\fP (u8line)"
.PP
Definition at line 265 of file altitude\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBalt\fP \fBsAlt\fP"
.PP
Definition at line 67 of file altitude\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
