.TH "logic/battery.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/battery.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'ports\&.h'\fP
.br
\fC#include 'adc12\&.h'\fP
.br
\fC#include 'menu\&.h'\fP
.br
\fC#include 'battery\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreset_batt_measurement\fP (void)"
.br
.ti -1c
.RI "void \fBbattery_measurement\fP (void)"
.br
.ti -1c
.RI "void \fBdisplay_battery_V\fP (u8 line, u8 update)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBbatt\fP \fBsBatt\fP"
.br
.ti -1c
.RI "void(* \fBfptr_lcd_function_line2\fP )(u8 line, u8 update)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBbattery_measurement\fP (void)"
.PP
Definition at line 100 of file battery\&.c\&.
.SS "void \fBdisplay_battery_V\fP (u8line, u8update)"
.PP
Definition at line 157 of file battery\&.c\&.
.SS "void \fBreset_batt_measurement\fP (void)"
.PP
Definition at line 81 of file battery\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "void(* \fBfptr_lcd_function_line2\fP)(u8 line, u8 update)"
.PP
Definition at line 117 of file main\&.c\&.
.SS "struct \fBbatt\fP \fBsBatt\fP"
.PP
Definition at line 67 of file battery\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
