.TH "logic/bluerobin.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/bluerobin.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'radio\&.h'\fP
.br
\fC#include 'ports\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'rf1a\&.h'\fP
.br
\fC#include 'BlueRobin_RX_API\&.h'\fP
.br
\fC#include 'bluerobin\&.h'\fP
.br
\fC#include 'rfsimpliciti\&.h'\fP
.br
\fC#include 'user\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBREMEMBER_TX_ID\fP   (\fBFALSE\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdisplay_calories\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBdisplay_distance\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBBRRX__StopTimer_v\fP (void)"
.br
.ti -1c
.RI "void \fBreset_bluerobin\fP (void)"
.br
.ti -1c
.RI "void \fBmx_bluerobin\fP (u8 line)"
.br
.ti -1c
.RI "void \fBsx_bluerobin\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_selection_User_Sex1\fP (u8 segments, u32 index, u8 digits, u8 blanks)"
.br
.ti -1c
.RI "void \fBmx_caldist\fP (u8 line)"
.br
.ti -1c
.RI "void \fBsx_caldist\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_heartrate\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBdisplay_speed\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBdisplay_caldist\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "u8 \fBis_bluerobin\fP (void)"
.br
.ti -1c
.RI "u8 \fBis_bluerobin_searching\fP (void)"
.br
.ti -1c
.RI "void \fBget_bluerobin_data\fP (void)"
.br
.ti -1c
.RI "void \fBstop_bluerobin\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBbr\fP \fBsBlueRobin\fP"
.br
.ti -1c
.RI "const u8 \fBselection_User_Sex\fP [][4] = { 'MALE', 'FEMA' }"
.br
.ti -1c
.RI "u8 \fBrf_frequoffset\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBREMEMBER_TX_ID\fP   (\fBFALSE\fP)"
.PP
Definition at line 70 of file bluerobin\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void \fBBRRX__StopTimer_v\fP (void)"
.SS "void \fBdisplay_caldist\fP (u8line, u8update)"
.PP
Definition at line 545 of file bluerobin\&.c\&.
.SS "void \fBdisplay_calories\fP (u8line, u8update)"
.PP
Definition at line 559 of file bluerobin\&.c\&.
.SS "void \fBdisplay_distance\fP (u8line, u8update)"
.PP
Definition at line 473 of file bluerobin\&.c\&.
.SS "void \fBdisplay_heartrate\fP (u8line, u8update)"
.PP
Definition at line 374 of file bluerobin\&.c\&.
.SS "void \fBdisplay_selection_User_Sex1\fP (u8segments, u32index, u8digits, u8blanks)"
.PP
Definition at line 260 of file bluerobin\&.c\&.
.SS "void \fBdisplay_speed\fP (u8line, u8update)"
.PP
Definition at line 414 of file bluerobin\&.c\&.
.SS "void \fBget_bluerobin_data\fP (void)"
.PP
Definition at line 613 of file bluerobin\&.c\&.
.SS "u8 \fBis_bluerobin\fP (void)"
.PP
Definition at line 589 of file bluerobin\&.c\&.
.SS "u8 \fBis_bluerobin_searching\fP (void)"
.PP
Definition at line 601 of file bluerobin\&.c\&.
.SS "void \fBmx_bluerobin\fP (u8line)"
.PP
Definition at line 128 of file bluerobin\&.c\&.
.SS "void \fBmx_caldist\fP (u8line)"
.PP
Definition at line 272 of file bluerobin\&.c\&.
.SS "void \fBreset_bluerobin\fP (void)"
.PP
Definition at line 97 of file bluerobin\&.c\&.
.SS "void \fBstop_bluerobin\fP (void)"
.PP
Definition at line 668 of file bluerobin\&.c\&.
.SS "void \fBsx_bluerobin\fP (u8line)"
.PP
Definition at line 152 of file bluerobin\&.c\&.
.SS "void \fBsx_caldist\fP (u8line)"
.PP
Definition at line 353 of file bluerobin\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "u8 \fBrf_frequoffset\fP"
.PP
Definition at line 110 of file main\&.c\&.
.SS "struct \fBbr\fP \fBsBlueRobin\fP"
.PP
Definition at line 75 of file bluerobin\&.c\&.
.SS "const u8 \fBselection_User_Sex\fP[][4] = { 'MALE', 'FEMA' }"
.PP
Definition at line 78 of file bluerobin\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
