.TH "Original Code/V2.2/simpliciti/Components/bsp/bsp_macros.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/simpliciti/Components/bsp/bsp_macros.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBst\fP(x)   do { x } while (__LINE__ == -1)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBst\fP(x)   do { x } while (__LINE__ == -1)"
.PP
Definition at line 74 of file bsp_macros\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
