.TH "simpliciti/Components/bsp/boards/CC430EM/bsp_driver_defs.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpliciti/Components/bsp/boards/CC430EM/bsp_driver_defs.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBSP_DRIVERS_C\fP   'bsp_drivers\&.c'"
.br
.ti -1c
.RI "#define \fBBSP_INIT_DRIVERS\fP()   \fBBSP_InitDrivers\fP()"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBSP_InitDrivers\fP (void)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBBSP_DRIVERS_C\fP   'bsp_drivers\&.c'"
.PP
Definition at line 47 of file bsp_driver_defs\&.h\&.
.SS "#define \fBBSP_INIT_DRIVERS\fP()   \fBBSP_InitDrivers\fP()"
.PP
Definition at line 48 of file bsp_driver_defs\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBBSP_InitDrivers\fP (void)"
.PP
Definition at line 59 of file bsp_drivers\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
