.TH "simpliciti/Components/bsp/drivers/code/bsp_leds.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpliciti/Components/bsp/drivers/code/bsp_leds.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bsp_leds\&.h'\fP
.br
\fC#include 'bsp_led_defs\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBSP_CONFIG_LED1\fP()   \fB__bsp_LED1_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_CONFIG_LED2\fP()   \fB__bsp_LED2_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_CONFIG_LED3\fP()   \fB__bsp_LED3_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_CONFIG_LED4\fP()   \fB__bsp_LED4_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_CONFIG_LED5\fP()   \fB__bsp_LED5_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_CONFIG_LED6\fP()   \fB__bsp_LED6_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_CONFIG_LED7\fP()   \fB__bsp_LED7_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_CONFIG_LED8\fP()   \fB__bsp_LED8_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_LED_EXTENDED_CONFIG\fP()"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBSP_InitLeds\fP (void)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBBSP_CONFIG_LED1\fP()   \fB__bsp_LED1_CONFIG__\fP()"
.PP
Definition at line 50 of file bsp_leds\&.c\&.
.SS "#define \fBBSP_CONFIG_LED2\fP()   \fB__bsp_LED2_CONFIG__\fP()"
.PP
Definition at line 51 of file bsp_leds\&.c\&.
.SS "#define \fBBSP_CONFIG_LED3\fP()   \fB__bsp_LED3_CONFIG__\fP()"
.PP
Definition at line 52 of file bsp_leds\&.c\&.
.SS "#define \fBBSP_CONFIG_LED4\fP()   \fB__bsp_LED4_CONFIG__\fP()"
.PP
Definition at line 53 of file bsp_leds\&.c\&.
.SS "#define \fBBSP_CONFIG_LED5\fP()   \fB__bsp_LED5_CONFIG__\fP()"
.PP
Definition at line 54 of file bsp_leds\&.c\&.
.SS "#define \fBBSP_CONFIG_LED6\fP()   \fB__bsp_LED6_CONFIG__\fP()"
.PP
Definition at line 55 of file bsp_leds\&.c\&.
.SS "#define \fBBSP_CONFIG_LED7\fP()   \fB__bsp_LED7_CONFIG__\fP()"
.PP
Definition at line 56 of file bsp_leds\&.c\&.
.SS "#define \fBBSP_CONFIG_LED8\fP()   \fB__bsp_LED8_CONFIG__\fP()"
.PP
Definition at line 57 of file bsp_leds\&.c\&.
.SS "#define \fBBSP_LED_EXTENDED_CONFIG\fP()"
.PP
Definition at line 62 of file bsp_leds\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void \fBBSP_InitLeds\fP (void)"
.PP
Definition at line 76 of file bsp_leds\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
