.TH "simpliciti/Components/bsp/boards/CC430EM/bsp_led_defs.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpliciti/Components/bsp/boards/CC430EM/bsp_led_defs.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bsp_board_defs\&.h'\fP
.br
\fC#include 'code/bsp_generic_leds\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB__bsp_NUM_LEDS__\fP   2"
.br
.ti -1c
.RI "#define \fB__bsp_LED_BLINK_LOOP_COUNT__\fP   0x34000"
.br
.ti -1c
.RI "#define \fB__bsp_LED1_BIT__\fP   0"
.br
.ti -1c
.RI "#define \fB__bsp_LED1_PORT__\fP   P1OUT"
.br
.ti -1c
.RI "#define \fB__bsp_LED1_DDR__\fP   P1DIR"
.br
.ti -1c
.RI "#define \fB__bsp_LED1_IS_ACTIVE_LOW__\fP   0"
.br
.ti -1c
.RI "#define \fB__bsp_LED2_BIT__\fP   6"
.br
.ti -1c
.RI "#define \fB__bsp_LED2_PORT__\fP   P3OUT"
.br
.ti -1c
.RI "#define \fB__bsp_LED2_DDR__\fP   P3DIR"
.br
.ti -1c
.RI "#define \fB__bsp_LED2_IS_ACTIVE_LOW__\fP   0"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fB__bsp_LED1_BIT__\fP   0"
.PP
Definition at line 67 of file bsp_led_defs\&.h\&.
.SS "#define \fB__bsp_LED1_DDR__\fP   P1DIR"
.PP
Definition at line 69 of file bsp_led_defs\&.h\&.
.SS "#define \fB__bsp_LED1_IS_ACTIVE_LOW__\fP   0"
.PP
Definition at line 70 of file bsp_led_defs\&.h\&.
.SS "#define \fB__bsp_LED1_PORT__\fP   P1OUT"
.PP
Definition at line 68 of file bsp_led_defs\&.h\&.
.SS "#define \fB__bsp_LED2_BIT__\fP   6"
.PP
Definition at line 82 of file bsp_led_defs\&.h\&.
.SS "#define \fB__bsp_LED2_DDR__\fP   P3DIR"
.PP
Definition at line 84 of file bsp_led_defs\&.h\&.
.SS "#define \fB__bsp_LED2_IS_ACTIVE_LOW__\fP   0"
.PP
Definition at line 85 of file bsp_led_defs\&.h\&.
.SS "#define \fB__bsp_LED2_PORT__\fP   P3OUT"
.PP
Definition at line 83 of file bsp_led_defs\&.h\&.
.SS "#define \fB__bsp_LED_BLINK_LOOP_COUNT__\fP   0x34000"
.PP
Definition at line 55 of file bsp_led_defs\&.h\&.
.SS "#define \fB__bsp_NUM_LEDS__\fP   2"
.PP
Definition at line 54 of file bsp_led_defs\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
