.TH "Original Code/V2.2/simpliciti/Components/bsp/boards/CC430EM/bsp_drivers.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/simpliciti/Components/bsp/boards/CC430EM/bsp_drivers.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bsp_driver_defs\&.h'\fP
.br
\fC#include 'bsp_leds\&.h'\fP
.br
\fC#include 'bsp_buttons\&.h'\fP
.br
\fC#include 'bsp_config\&.h'\fP
.br
\fC#include 'drivers/code/bsp_leds\&.c'\fP
.br
\fC#include 'drivers/code/bsp_buttons\&.c'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBSP_InitDrivers\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBBSP_InitDrivers\fP (void)"
.PP
Definition at line 59 of file bsp_drivers\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
