.TH "driver/buzzer.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
driver/buzzer.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBbuzzer\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBUZZER_OFF\fP   (0u)"
.br
.ti -1c
.RI "#define \fBBUZZER_ON_OUTPUT_DISABLED\fP   (1u)"
.br
.ti -1c
.RI "#define \fBBUZZER_ON_OUTPUT_ENABLED\fP   (2u)"
.br
.ti -1c
.RI "#define \fBBUZZER_MODE_SINGLE\fP   (0u)"
.br
.ti -1c
.RI "#define \fBBUZZER_MODE_SINGLE_CONTINUOUS\fP   (1u)"
.br
.ti -1c
.RI "#define \fBBUZZER_MODE_DOUBLE_CONTINUOUS\fP   (2u)"
.br
.ti -1c
.RI "#define \fBBUZZER_TIMER_STEPS\fP   (5u)"
.br
.ti -1c
.RI "#define \fBBUZZER_ON_TICKS\fP   (\fBCONV_MS_TO_TICKS\fP(20))"
.br
.ti -1c
.RI "#define \fBBUZZER_OFF_TICKS\fP   (\fBCONV_MS_TO_TICKS\fP(200))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreset_buzzer\fP (void)"
.br
.ti -1c
.RI "void \fBstart_buzzer\fP (u8 cycles, \fBu16\fP on_time, \fBu16\fP off_time)"
.br
.ti -1c
.RI "void \fBstop_buzzer\fP (void)"
.br
.ti -1c
.RI "void \fBtoggle_buzzer\fP (void)"
.br
.ti -1c
.RI "u8 \fBis_buzzer\fP (void)"
.br
.ti -1c
.RI "void \fBcountdown_buzzer\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBbuzzer\fP \fBsBuzzer\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBBUZZER_MODE_DOUBLE_CONTINUOUS\fP   (2u)"
.PP
Definition at line 65 of file buzzer\&.h\&.
.SS "#define \fBBUZZER_MODE_SINGLE\fP   (0u)"
.PP
Definition at line 63 of file buzzer\&.h\&.
.SS "#define \fBBUZZER_MODE_SINGLE_CONTINUOUS\fP   (1u)"
.PP
Definition at line 64 of file buzzer\&.h\&.
.SS "#define \fBBUZZER_OFF\fP   (0u)"
.PP
Definition at line 58 of file buzzer\&.h\&.
.SS "#define \fBBUZZER_OFF_TICKS\fP   (\fBCONV_MS_TO_TICKS\fP(200))"
.PP
Definition at line 74 of file buzzer\&.h\&.
.SS "#define \fBBUZZER_ON_OUTPUT_DISABLED\fP   (1u)"
.PP
Definition at line 59 of file buzzer\&.h\&.
.SS "#define \fBBUZZER_ON_OUTPUT_ENABLED\fP   (2u)"
.PP
Definition at line 60 of file buzzer\&.h\&.
.SS "#define \fBBUZZER_ON_TICKS\fP   (\fBCONV_MS_TO_TICKS\fP(20))"
.PP
Definition at line 71 of file buzzer\&.h\&.
.SS "#define \fBBUZZER_TIMER_STEPS\fP   (5u)"
.PP
Definition at line 68 of file buzzer\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBcountdown_buzzer\fP (void)"
.PP
Definition at line 227 of file buzzer\&.c\&.
.SS "u8 \fBis_buzzer\fP (void)"
.PP
Definition at line 214 of file buzzer\&.c\&.
.SS "void \fBreset_buzzer\fP (void)"
.PP
Definition at line 81 of file buzzer\&.c\&.
.SS "void \fBstart_buzzer\fP (u8cycles, \fBu16\fPon_time, \fBu16\fPoff_time)"
.PP
Definition at line 95 of file buzzer\&.c\&.
.SS "void \fBstop_buzzer\fP (void)"
.PP
Definition at line 187 of file buzzer\&.c\&.
.SS "void \fBtoggle_buzzer\fP (void)"
.PP
Definition at line 138 of file buzzer\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBbuzzer\fP \fBsBuzzer\fP"
.PP
Definition at line 66 of file buzzer\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
