.TH "logic/date.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/date.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBdate\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreset_date\fP (void)"
.br
.ti -1c
.RI "void \fBadd_day\fP (void)"
.br
.ti -1c
.RI "void \fBmx_date\fP (u8 line)"
.br
.ti -1c
.RI "void \fBsx_date\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_date\fP (u8 line, u8 update)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBdate\fP \fBsDate\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBadd_day\fP (void)"
.PP
Definition at line 395 of file date\&.c\&.
.SS "void \fBdisplay_date\fP (u8line, u8update)"
.PP
Definition at line 582 of file date\&.c\&.
.SS "void \fBmx_date\fP (u8line)"
.PP
Definition at line 436 of file date\&.c\&.
.SS "void \fBreset_date\fP (void)"
.PP
Definition at line 288 of file date\&.c\&.
.SS "void \fBsx_date\fP (u8line)"
.PP
Definition at line 564 of file date\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBdate\fP \fBsDate\fP"
.PP
Definition at line 74 of file date\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
