.TH "date" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
date \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'date\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBdisplay\fP"
.br
.ti -1c
.RI "u8 \fBday\fP"
.br
.ti -1c
.RI "u8 \fBDayOfWeek\fP"
.br
.ti -1c
.RI "u8 \fBmonth\fP"
.br
.ti -1c
.RI "\fBu16\fP \fByear\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file date\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u8 \fBday\fP"
.PP
Definition at line 62 of file date\&.h\&.
.SS "u8 \fBDayOfWeek\fP"
.PP
Definition at line 63 of file date\&.h\&.
.SS "u8 \fBdisplay\fP"
.PP
Definition at line 61 of file date\&.h\&.
.SS "u8 \fBmonth\fP"
.PP
Definition at line 64 of file date\&.h\&.
.SS "\fBu16\fP \fByear\fP"
.PP
Definition at line 65 of file date\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
