.TH "driver/display.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
driver/display.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <project\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBs_display_flags\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDISPLAY_LINE_UPDATE_FULL\fP   (BIT0)"
.br
.ti -1c
.RI "#define \fBDISPLAY_LINE_UPDATE_PARTIAL\fP   (BIT1)"
.br
.ti -1c
.RI "#define \fBDISPLAY_LINE_CLEAR\fP   (BIT2)"
.br
.ti -1c
.RI "#define \fBDISPLAY_DEFAULT_VIEW\fP   (0u)"
.br
.ti -1c
.RI "#define \fBDISPLAY_ALTERNATIVE_VIEW\fP   (1u)"
.br
.ti -1c
.RI "#define \fBDISPLAY_ALTERNATIVE_VIEW_2\fP   (2u)"
.br
.ti -1c
.RI "#define \fBDISPLAY_ALTERNATIVE_VIEW_3\fP   (3u)"
.br
.ti -1c
.RI "#define \fBDISPLAY_ALTERNATIVE_VIEW_4\fP   (4u)"
.br
.ti -1c
.RI "#define \fBLINE1\fP   (1u)"
.br
.ti -1c
.RI "#define \fBLINE2\fP   (2u)"
.br
.ti -1c
.RI "#define \fBSEG_OFF\fP   (0u)"
.br
.ti -1c
.RI "#define \fBSEG_ON\fP   (1u)"
.br
.ti -1c
.RI "#define \fBSEG_ON_BLINK_ON\fP   (2u)"
.br
.ti -1c
.RI "#define \fBSEG_ON_BLINK_OFF\fP   (3u)"
.br
.ti -1c
.RI "#define \fBSEG_OFF_BLINK_OFF\fP   (4u)"
.br
.ti -1c
.RI "#define \fBSEG_A\fP   (BIT4)"
.br
.ti -1c
.RI "#define \fBSEG_B\fP   (BIT5)"
.br
.ti -1c
.RI "#define \fBSEG_C\fP   (BIT6)"
.br
.ti -1c
.RI "#define \fBSEG_D\fP   (BIT7)"
.br
.ti -1c
.RI "#define \fBSEG_E\fP   (BIT2)"
.br
.ti -1c
.RI "#define \fBSEG_F\fP   (BIT0)"
.br
.ti -1c
.RI "#define \fBSEG_G\fP   (BIT1)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_AM\fP   0"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_PM\fP   1"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_ARROW_UP\fP   2"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_ARROW_DOWN\fP   3"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_PERCENT\fP   4"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_TOTAL\fP   5"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_AVERAGE\fP   6"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_MAX\fP   7"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_BATTERY\fP   8"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_FT\fP   9"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_K\fP   10"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_M\fP   11"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_I\fP   12"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_PER_S\fP   13"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_PER_H\fP   14"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_DEGREE\fP   15"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L2_KCAL\fP   16"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L2_KM\fP   17"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L2_MI\fP   18"
.br
.ti -1c
.RI "#define \fBLCD_ICON_HEART\fP   19"
.br
.ti -1c
.RI "#define \fBLCD_ICON_STOPWATCH\fP   20"
.br
.ti -1c
.RI "#define \fBLCD_ICON_RECORD\fP   21"
.br
.ti -1c
.RI "#define \fBLCD_ICON_ALARM\fP   22"
.br
.ti -1c
.RI "#define \fBLCD_ICON_BEEPER1\fP   23"
.br
.ti -1c
.RI "#define \fBLCD_ICON_BEEPER2\fP   24"
.br
.ti -1c
.RI "#define \fBLCD_ICON_BEEPER3\fP   25"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_3\fP   26"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_2\fP   27"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_1\fP   28"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_0\fP   29"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_COL\fP   30"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_DP1\fP   31"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_DP0\fP   32"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_5\fP   33"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_4\fP   34"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_3\fP   35"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_2\fP   36"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_1\fP   37"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_0\fP   38"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_COL1\fP   39"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_COL0\fP   40"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_DP\fP   41"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_3_0\fP   70"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_2_0\fP   71"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_1_0\fP   72"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_3_1\fP   73"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_3_2\fP   74"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_5_0\fP   90"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_4_0\fP   91"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_3_0\fP   92"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_2_0\fP   93"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_1_0\fP   94"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_5_2\fP   95"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_3_2\fP   96"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_5_4\fP   97"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_4_2\fP   98"
.br
.ti -1c
.RI "#define \fBLCD_MEM_1\fP   ((u8*)0x0A20)"
.br
.ti -1c
.RI "#define \fBLCD_MEM_2\fP   ((u8*)0x0A21)"
.br
.ti -1c
.RI "#define \fBLCD_MEM_3\fP   ((u8*)0x0A22)"
.br
.ti -1c
.RI "#define \fBLCD_MEM_4\fP   ((u8*)0x0A23)"
.br
.ti -1c
.RI "#define \fBLCD_MEM_5\fP   ((u8*)0x0A24)"
.br
.ti -1c
.RI "#define \fBLCD_MEM_6\fP   ((u8*)0x0A25)"
.br
.ti -1c
.RI "#define \fBLCD_MEM_7\fP   ((u8*)0x0A26)"
.br
.ti -1c
.RI "#define \fBLCD_MEM_8\fP   ((u8*)0x0A27)"
.br
.ti -1c
.RI "#define \fBLCD_MEM_9\fP   ((u8*)0x0A28)"
.br
.ti -1c
.RI "#define \fBLCD_MEM_10\fP   ((u8*)0x0A29)"
.br
.ti -1c
.RI "#define \fBLCD_MEM_11\fP   ((u8*)0x0A2A)"
.br
.ti -1c
.RI "#define \fBLCD_MEM_12\fP   ((u8*)0x0A2B)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_0_MEM\fP   (\fBLCD_MEM_6\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_1_MEM\fP   (\fBLCD_MEM_4\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_2_MEM\fP   (\fBLCD_MEM_3\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_3_MEM\fP   (\fBLCD_MEM_2\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_COL_MEM\fP   (\fBLCD_MEM_1\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_DP1_MEM\fP   (\fBLCD_MEM_1\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_DP0_MEM\fP   (\fBLCD_MEM_5\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_0_MEM\fP   (\fBLCD_MEM_8\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_1_MEM\fP   (\fBLCD_MEM_9\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_2_MEM\fP   (\fBLCD_MEM_10\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_3_MEM\fP   (\fBLCD_MEM_11\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_4_MEM\fP   (\fBLCD_MEM_12\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_5_MEM\fP   (\fBLCD_MEM_12\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_COL1_MEM\fP   (\fBLCD_MEM_1\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_COL0_MEM\fP   (\fBLCD_MEM_5\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_DP_MEM\fP   (\fBLCD_MEM_9\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_AM_MEM\fP   (\fBLCD_MEM_1\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_PM_MEM\fP   (\fBLCD_MEM_1\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_ARROW_UP_MEM\fP   (\fBLCD_MEM_1\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_ARROW_DOWN_MEM\fP   (\fBLCD_MEM_1\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_PERCENT_MEM\fP   (\fBLCD_MEM_5\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_TOTAL_MEM\fP   (\fBLCD_MEM_11\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_AVERAGE_MEM\fP   (\fBLCD_MEM_10\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_MAX_MEM\fP   (\fBLCD_MEM_8\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_BATTERY_MEM\fP   (\fBLCD_MEM_7\fP)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_FT_MEM\fP   (\fBLCD_MEM_5\fP)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_K_MEM\fP   (\fBLCD_MEM_5\fP)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_M_MEM\fP   (\fBLCD_MEM_7\fP)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_I_MEM\fP   (\fBLCD_MEM_7\fP)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_PER_S_MEM\fP   (\fBLCD_MEM_5\fP)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_PER_H_MEM\fP   (\fBLCD_MEM_7\fP)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_DEGREE_MEM\fP   (\fBLCD_MEM_5\fP)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L2_KCAL_MEM\fP   (\fBLCD_MEM_7\fP)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L2_KM_MEM\fP   (\fBLCD_MEM_7\fP)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L2_MI_MEM\fP   (\fBLCD_MEM_7\fP)"
.br
.ti -1c
.RI "#define \fBLCD_ICON_HEART_MEM\fP   (\fBLCD_MEM_2\fP)"
.br
.ti -1c
.RI "#define \fBLCD_ICON_STOPWATCH_MEM\fP   (\fBLCD_MEM_3\fP)"
.br
.ti -1c
.RI "#define \fBLCD_ICON_RECORD_MEM\fP   (\fBLCD_MEM_1\fP)"
.br
.ti -1c
.RI "#define \fBLCD_ICON_ALARM_MEM\fP   (\fBLCD_MEM_4\fP)"
.br
.ti -1c
.RI "#define \fBLCD_ICON_BEEPER1_MEM\fP   (\fBLCD_MEM_5\fP)"
.br
.ti -1c
.RI "#define \fBLCD_ICON_BEEPER2_MEM\fP   (\fBLCD_MEM_6\fP)"
.br
.ti -1c
.RI "#define \fBLCD_ICON_BEEPER3_MEM\fP   (\fBLCD_MEM_7\fP)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_0_MASK\fP   (BIT2+BIT1+BIT0+BIT7+BIT6+BIT5+BIT4)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_1_MASK\fP   (BIT2+BIT1+BIT0+BIT7+BIT6+BIT5+BIT4)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_2_MASK\fP   (BIT2+BIT1+BIT0+BIT7+BIT6+BIT5+BIT4)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_3_MASK\fP   (BIT2+BIT1+BIT0+BIT7+BIT6+BIT5+BIT4)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_COL_MASK\fP   (BIT5)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_DP1_MASK\fP   (BIT6)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L1_DP0_MASK\fP   (BIT2)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_0_MASK\fP   (BIT3+BIT2+BIT1+BIT0+BIT6+BIT5+BIT4)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_1_MASK\fP   (BIT3+BIT2+BIT1+BIT0+BIT6+BIT5+BIT4)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_2_MASK\fP   (BIT3+BIT2+BIT1+BIT0+BIT6+BIT5+BIT4)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_3_MASK\fP   (BIT3+BIT2+BIT1+BIT0+BIT6+BIT5+BIT4)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_4_MASK\fP   (BIT3+BIT2+BIT1+BIT0+BIT6+BIT5+BIT4)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_5_MASK\fP   (BIT7)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_COL1_MASK\fP   (BIT4)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_COL0_MASK\fP   (BIT0)"
.br
.ti -1c
.RI "#define \fBLCD_SEG_L2_DP_MASK\fP   (BIT7)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_AM_MASK\fP   (BIT1+BIT0)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_PM_MASK\fP   (BIT0)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_ARROW_UP_MASK\fP   (BIT2)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_ARROW_DOWN_MASK\fP   (BIT3)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_PERCENT_MASK\fP   (BIT4)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_TOTAL_MASK\fP   (BIT7)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_AVERAGE_MASK\fP   (BIT7)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_MAX_MASK\fP   (BIT7)"
.br
.ti -1c
.RI "#define \fBLCD_SYMB_BATTERY_MASK\fP   (BIT7)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_FT_MASK\fP   (BIT5)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_K_MASK\fP   (BIT6)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_M_MASK\fP   (BIT1)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_I_MASK\fP   (BIT0)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_PER_S_MASK\fP   (BIT3)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_PER_H_MASK\fP   (BIT2)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L1_DEGREE_MASK\fP   (BIT1)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L2_KCAL_MASK\fP   (BIT4)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L2_KM_MASK\fP   (BIT5)"
.br
.ti -1c
.RI "#define \fBLCD_UNIT_L2_MI_MASK\fP   (BIT6)"
.br
.ti -1c
.RI "#define \fBLCD_ICON_HEART_MASK\fP   (BIT3)"
.br
.ti -1c
.RI "#define \fBLCD_ICON_STOPWATCH_MASK\fP   (BIT3)"
.br
.ti -1c
.RI "#define \fBLCD_ICON_RECORD_MASK\fP   (BIT7)"
.br
.ti -1c
.RI "#define \fBLCD_ICON_ALARM_MASK\fP   (BIT3)"
.br
.ti -1c
.RI "#define \fBLCD_ICON_BEEPER1_MASK\fP   (BIT3)"
.br
.ti -1c
.RI "#define \fBLCD_ICON_BEEPER2_MASK\fP   (BIT3)"
.br
.ti -1c
.RI "#define \fBLCD_ICON_BEEPER3_MASK\fP   (BIT3)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBwrite_lcd_mem\fP (u8 *lcdmem, u8 bits, u8 bitmask, u8 state)"
.br
.ti -1c
.RI "void \fBlcd_init\fP (void)"
.br
.ti -1c
.RI "void \fBclear_display\fP (void)"
.br
.ti -1c
.RI "void \fBclear_display_all\fP (void)"
.br
.ti -1c
.RI "void \fBclear_line\fP (u8 line)"
.br
.ti -1c
.RI "void \fBstart_blink\fP (void)"
.br
.ti -1c
.RI "void \fBstop_blink\fP (void)"
.br
.ti -1c
.RI "void \fBclear_blink_mem\fP (void)"
.br
.ti -1c
.RI "void \fBset_blink_rate\fP (u8 bits)"
.br
.ti -1c
.RI "void \fBdisplay_char\fP (u8 segment, u8 chr, u8 mode)"
.br
.ti -1c
.RI "void \fBdisplay_chars\fP (u8 segments, u8 *str, u8 mode)"
.br
.ti -1c
.RI "void \fBdisplay_symbol\fP (u8 symbol, u8 mode)"
.br
.ti -1c
.RI "void \fBDisplayTime\fP (u8 updateMode)"
.br
.ti -1c
.RI "void \fBdisplay_am_pm_symbol\fP (u8 timeAM)"
.br
.ti -1c
.RI "void \fBdisplay_value1\fP (u8 segments, u32 value, u8 digits, u8 blanks)"
.br
.ti -1c
.RI "void \fBdisplay_hours1\fP (u8 segments, u32 value, u8 digits, u8 blanks)"
.br
.ti -1c
.RI "u8 * \fBitoa\fP (u32 n, u8 digits, u8 blanks)"
.br
.ti -1c
.RI "u8 \fBswitch_seg\fP (u8 line, u8 index1, u8 index2)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const u8 \fBlcd_font\fP []"
.br
.ti -1c
.RI "const u8 * \fBsegments_lcdmem\fP []"
.br
.ti -1c
.RI "const u8 \fBsegments_bitmask\fP []"
.br
.ti -1c
.RI "const u8 \fBitoa_conversion_table\fP [][3]"
.br
.ti -1c
.RI "volatile \fBs_display_flags\fP \fBdisplay\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBDISPLAY_ALTERNATIVE_VIEW\fP   (1u)"
.PP
Definition at line 98 of file display\&.h\&.
.SS "#define \fBDISPLAY_ALTERNATIVE_VIEW_2\fP   (2u)"
.PP
Definition at line 99 of file display\&.h\&.
.SS "#define \fBDISPLAY_ALTERNATIVE_VIEW_3\fP   (3u)"
.PP
Definition at line 100 of file display\&.h\&.
.SS "#define \fBDISPLAY_ALTERNATIVE_VIEW_4\fP   (4u)"
.PP
Definition at line 101 of file display\&.h\&.
.SS "#define \fBDISPLAY_DEFAULT_VIEW\fP   (0u)"
.PP
Definition at line 97 of file display\&.h\&.
.SS "#define \fBDISPLAY_LINE_CLEAR\fP   (BIT2)"
.PP
Definition at line 94 of file display\&.h\&.
.SS "#define \fBDISPLAY_LINE_UPDATE_FULL\fP   (BIT0)"
.PP
Definition at line 92 of file display\&.h\&.
.SS "#define \fBDISPLAY_LINE_UPDATE_PARTIAL\fP   (BIT1)"
.PP
Definition at line 93 of file display\&.h\&.
.SS "#define \fBLCD_ICON_ALARM\fP   22"
.PP
Definition at line 164 of file display\&.h\&.
.SS "#define \fBLCD_ICON_ALARM_MASK\fP   (BIT3)"
.PP
Definition at line 307 of file display\&.h\&.
.SS "#define \fBLCD_ICON_ALARM_MEM\fP   (\fBLCD_MEM_4\fP)"
.PP
Definition at line 263 of file display\&.h\&.
.SS "#define \fBLCD_ICON_BEEPER1\fP   23"
.PP
Definition at line 165 of file display\&.h\&.
.SS "#define \fBLCD_ICON_BEEPER1_MASK\fP   (BIT3)"
.PP
Definition at line 308 of file display\&.h\&.
.SS "#define \fBLCD_ICON_BEEPER1_MEM\fP   (\fBLCD_MEM_5\fP)"
.PP
Definition at line 264 of file display\&.h\&.
.SS "#define \fBLCD_ICON_BEEPER2\fP   24"
.PP
Definition at line 166 of file display\&.h\&.
.SS "#define \fBLCD_ICON_BEEPER2_MASK\fP   (BIT3)"
.PP
Definition at line 309 of file display\&.h\&.
.SS "#define \fBLCD_ICON_BEEPER2_MEM\fP   (\fBLCD_MEM_6\fP)"
.PP
Definition at line 265 of file display\&.h\&.
.SS "#define \fBLCD_ICON_BEEPER3\fP   25"
.PP
Definition at line 167 of file display\&.h\&.
.SS "#define \fBLCD_ICON_BEEPER3_MASK\fP   (BIT3)"
.PP
Definition at line 310 of file display\&.h\&.
.SS "#define \fBLCD_ICON_BEEPER3_MEM\fP   (\fBLCD_MEM_7\fP)"
.PP
Definition at line 266 of file display\&.h\&.
.SS "#define \fBLCD_ICON_HEART\fP   19"
.PP
Definition at line 161 of file display\&.h\&.
.SS "#define \fBLCD_ICON_HEART_MASK\fP   (BIT3)"
.PP
Definition at line 304 of file display\&.h\&.
.SS "#define \fBLCD_ICON_HEART_MEM\fP   (\fBLCD_MEM_2\fP)"
.PP
Definition at line 260 of file display\&.h\&.
.SS "#define \fBLCD_ICON_RECORD\fP   21"
.PP
Definition at line 163 of file display\&.h\&.
.SS "#define \fBLCD_ICON_RECORD_MASK\fP   (BIT7)"
.PP
Definition at line 306 of file display\&.h\&.
.SS "#define \fBLCD_ICON_RECORD_MEM\fP   (\fBLCD_MEM_1\fP)"
.PP
Definition at line 262 of file display\&.h\&.
.SS "#define \fBLCD_ICON_STOPWATCH\fP   20"
.PP
Definition at line 162 of file display\&.h\&.
.SS "#define \fBLCD_ICON_STOPWATCH_MASK\fP   (BIT3)"
.PP
Definition at line 305 of file display\&.h\&.
.SS "#define \fBLCD_ICON_STOPWATCH_MEM\fP   (\fBLCD_MEM_3\fP)"
.PP
Definition at line 261 of file display\&.h\&.
.SS "#define \fBLCD_MEM_1\fP   ((u8*)0x0A20)"
.PP
Definition at line 210 of file display\&.h\&.
.SS "#define \fBLCD_MEM_10\fP   ((u8*)0x0A29)"
.PP
Definition at line 219 of file display\&.h\&.
.SS "#define \fBLCD_MEM_11\fP   ((u8*)0x0A2A)"
.PP
Definition at line 220 of file display\&.h\&.
.SS "#define \fBLCD_MEM_12\fP   ((u8*)0x0A2B)"
.PP
Definition at line 221 of file display\&.h\&.
.SS "#define \fBLCD_MEM_2\fP   ((u8*)0x0A21)"
.PP
Definition at line 211 of file display\&.h\&.
.SS "#define \fBLCD_MEM_3\fP   ((u8*)0x0A22)"
.PP
Definition at line 212 of file display\&.h\&.
.SS "#define \fBLCD_MEM_4\fP   ((u8*)0x0A23)"
.PP
Definition at line 213 of file display\&.h\&.
.SS "#define \fBLCD_MEM_5\fP   ((u8*)0x0A24)"
.PP
Definition at line 214 of file display\&.h\&.
.SS "#define \fBLCD_MEM_6\fP   ((u8*)0x0A25)"
.PP
Definition at line 215 of file display\&.h\&.
.SS "#define \fBLCD_MEM_7\fP   ((u8*)0x0A26)"
.PP
Definition at line 216 of file display\&.h\&.
.SS "#define \fBLCD_MEM_8\fP   ((u8*)0x0A27)"
.PP
Definition at line 217 of file display\&.h\&.
.SS "#define \fBLCD_MEM_9\fP   ((u8*)0x0A28)"
.PP
Definition at line 218 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_0\fP   29"
.PP
Definition at line 173 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_0_MASK\fP   (BIT2+BIT1+BIT0+BIT7+BIT6+BIT5+BIT4)"
.PP
Definition at line 269 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_0_MEM\fP   (\fBLCD_MEM_6\fP)"
.PP
Definition at line 225 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_1\fP   28"
.PP
Definition at line 172 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_1_0\fP   72"
.PP
Definition at line 193 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_1_MASK\fP   (BIT2+BIT1+BIT0+BIT7+BIT6+BIT5+BIT4)"
.PP
Definition at line 270 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_1_MEM\fP   (\fBLCD_MEM_4\fP)"
.PP
Definition at line 226 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_2\fP   27"
.PP
Definition at line 171 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_2_0\fP   71"
.PP
Definition at line 192 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_2_MASK\fP   (BIT2+BIT1+BIT0+BIT7+BIT6+BIT5+BIT4)"
.PP
Definition at line 271 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_2_MEM\fP   (\fBLCD_MEM_3\fP)"
.PP
Definition at line 227 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_3\fP   26"
.PP
Definition at line 170 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_3_0\fP   70"
.PP
Definition at line 191 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_3_1\fP   73"
.PP
Definition at line 194 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_3_2\fP   74"
.PP
Definition at line 195 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_3_MASK\fP   (BIT2+BIT1+BIT0+BIT7+BIT6+BIT5+BIT4)"
.PP
Definition at line 272 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_3_MEM\fP   (\fBLCD_MEM_2\fP)"
.PP
Definition at line 228 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_COL\fP   30"
.PP
Definition at line 174 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_COL_MASK\fP   (BIT5)"
.PP
Definition at line 273 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_COL_MEM\fP   (\fBLCD_MEM_1\fP)"
.PP
Definition at line 229 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_DP0\fP   32"
.PP
Definition at line 176 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_DP0_MASK\fP   (BIT2)"
.PP
Definition at line 275 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_DP0_MEM\fP   (\fBLCD_MEM_5\fP)"
.PP
Definition at line 231 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_DP1\fP   31"
.PP
Definition at line 175 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_DP1_MASK\fP   (BIT6)"
.PP
Definition at line 274 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L1_DP1_MEM\fP   (\fBLCD_MEM_1\fP)"
.PP
Definition at line 230 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_0\fP   38"
.PP
Definition at line 184 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_0_MASK\fP   (BIT3+BIT2+BIT1+BIT0+BIT6+BIT5+BIT4)"
.PP
Definition at line 276 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_0_MEM\fP   (\fBLCD_MEM_8\fP)"
.PP
Definition at line 232 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_1\fP   37"
.PP
Definition at line 183 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_1_0\fP   94"
.PP
Definition at line 202 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_1_MASK\fP   (BIT3+BIT2+BIT1+BIT0+BIT6+BIT5+BIT4)"
.PP
Definition at line 277 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_1_MEM\fP   (\fBLCD_MEM_9\fP)"
.PP
Definition at line 233 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_2\fP   36"
.PP
Definition at line 182 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_2_0\fP   93"
.PP
Definition at line 201 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_2_MASK\fP   (BIT3+BIT2+BIT1+BIT0+BIT6+BIT5+BIT4)"
.PP
Definition at line 278 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_2_MEM\fP   (\fBLCD_MEM_10\fP)"
.PP
Definition at line 234 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_3\fP   35"
.PP
Definition at line 181 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_3_0\fP   92"
.PP
Definition at line 200 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_3_2\fP   96"
.PP
Definition at line 204 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_3_MASK\fP   (BIT3+BIT2+BIT1+BIT0+BIT6+BIT5+BIT4)"
.PP
Definition at line 279 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_3_MEM\fP   (\fBLCD_MEM_11\fP)"
.PP
Definition at line 235 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_4\fP   34"
.PP
Definition at line 180 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_4_0\fP   91"
.PP
Definition at line 199 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_4_2\fP   98"
.PP
Definition at line 206 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_4_MASK\fP   (BIT3+BIT2+BIT1+BIT0+BIT6+BIT5+BIT4)"
.PP
Definition at line 280 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_4_MEM\fP   (\fBLCD_MEM_12\fP)"
.PP
Definition at line 236 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_5\fP   33"
.PP
Definition at line 179 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_5_0\fP   90"
.PP
Definition at line 198 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_5_2\fP   95"
.PP
Definition at line 203 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_5_4\fP   97"
.PP
Definition at line 205 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_5_MASK\fP   (BIT7)"
.PP
Definition at line 281 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_5_MEM\fP   (\fBLCD_MEM_12\fP)"
.PP
Definition at line 237 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_COL0\fP   40"
.PP
Definition at line 186 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_COL0_MASK\fP   (BIT0)"
.PP
Definition at line 283 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_COL0_MEM\fP   (\fBLCD_MEM_5\fP)"
.PP
Definition at line 239 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_COL1\fP   39"
.PP
Definition at line 185 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_COL1_MASK\fP   (BIT4)"
.PP
Definition at line 282 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_COL1_MEM\fP   (\fBLCD_MEM_1\fP)"
.PP
Definition at line 238 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_DP\fP   41"
.PP
Definition at line 187 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_DP_MASK\fP   (BIT7)"
.PP
Definition at line 284 of file display\&.h\&.
.SS "#define \fBLCD_SEG_L2_DP_MEM\fP   (\fBLCD_MEM_9\fP)"
.PP
Definition at line 240 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_AM\fP   0"
.PP
Definition at line 134 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_AM_MASK\fP   (BIT1+BIT0)"
.PP
Definition at line 285 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_AM_MEM\fP   (\fBLCD_MEM_1\fP)"
.PP
Definition at line 241 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_ARROW_DOWN\fP   3"
.PP
Definition at line 137 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_ARROW_DOWN_MASK\fP   (BIT3)"
.PP
Definition at line 288 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_ARROW_DOWN_MEM\fP   (\fBLCD_MEM_1\fP)"
.PP
Definition at line 244 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_ARROW_UP\fP   2"
.PP
Definition at line 136 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_ARROW_UP_MASK\fP   (BIT2)"
.PP
Definition at line 287 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_ARROW_UP_MEM\fP   (\fBLCD_MEM_1\fP)"
.PP
Definition at line 243 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_AVERAGE\fP   6"
.PP
Definition at line 142 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_AVERAGE_MASK\fP   (BIT7)"
.PP
Definition at line 291 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_AVERAGE_MEM\fP   (\fBLCD_MEM_10\fP)"
.PP
Definition at line 247 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_BATTERY\fP   8"
.PP
Definition at line 144 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_BATTERY_MASK\fP   (BIT7)"
.PP
Definition at line 293 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_BATTERY_MEM\fP   (\fBLCD_MEM_7\fP)"
.PP
Definition at line 249 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_MAX\fP   7"
.PP
Definition at line 143 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_MAX_MASK\fP   (BIT7)"
.PP
Definition at line 292 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_MAX_MEM\fP   (\fBLCD_MEM_8\fP)"
.PP
Definition at line 248 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_PERCENT\fP   4"
.PP
Definition at line 138 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_PERCENT_MASK\fP   (BIT4)"
.PP
Definition at line 289 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_PERCENT_MEM\fP   (\fBLCD_MEM_5\fP)"
.PP
Definition at line 245 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_PM\fP   1"
.PP
Definition at line 135 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_PM_MASK\fP   (BIT0)"
.PP
Definition at line 286 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_PM_MEM\fP   (\fBLCD_MEM_1\fP)"
.PP
Definition at line 242 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_TOTAL\fP   5"
.PP
Definition at line 141 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_TOTAL_MASK\fP   (BIT7)"
.PP
Definition at line 290 of file display\&.h\&.
.SS "#define \fBLCD_SYMB_TOTAL_MEM\fP   (\fBLCD_MEM_11\fP)"
.PP
Definition at line 246 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_DEGREE\fP   15"
.PP
Definition at line 153 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_DEGREE_MASK\fP   (BIT1)"
.PP
Definition at line 300 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_DEGREE_MEM\fP   (\fBLCD_MEM_5\fP)"
.PP
Definition at line 256 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_FT\fP   9"
.PP
Definition at line 147 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_FT_MASK\fP   (BIT5)"
.PP
Definition at line 294 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_FT_MEM\fP   (\fBLCD_MEM_5\fP)"
.PP
Definition at line 250 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_I\fP   12"
.PP
Definition at line 150 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_I_MASK\fP   (BIT0)"
.PP
Definition at line 297 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_I_MEM\fP   (\fBLCD_MEM_7\fP)"
.PP
Definition at line 253 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_K\fP   10"
.PP
Definition at line 148 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_K_MASK\fP   (BIT6)"
.PP
Definition at line 295 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_K_MEM\fP   (\fBLCD_MEM_5\fP)"
.PP
Definition at line 251 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_M\fP   11"
.PP
Definition at line 149 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_M_MASK\fP   (BIT1)"
.PP
Definition at line 296 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_M_MEM\fP   (\fBLCD_MEM_7\fP)"
.PP
Definition at line 252 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_PER_H\fP   14"
.PP
Definition at line 152 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_PER_H_MASK\fP   (BIT2)"
.PP
Definition at line 299 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_PER_H_MEM\fP   (\fBLCD_MEM_7\fP)"
.PP
Definition at line 255 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_PER_S\fP   13"
.PP
Definition at line 151 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_PER_S_MASK\fP   (BIT3)"
.PP
Definition at line 298 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L1_PER_S_MEM\fP   (\fBLCD_MEM_5\fP)"
.PP
Definition at line 254 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L2_KCAL\fP   16"
.PP
Definition at line 156 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L2_KCAL_MASK\fP   (BIT4)"
.PP
Definition at line 301 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L2_KCAL_MEM\fP   (\fBLCD_MEM_7\fP)"
.PP
Definition at line 257 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L2_KM\fP   17"
.PP
Definition at line 157 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L2_KM_MASK\fP   (BIT5)"
.PP
Definition at line 302 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L2_KM_MEM\fP   (\fBLCD_MEM_7\fP)"
.PP
Definition at line 258 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L2_MI\fP   18"
.PP
Definition at line 158 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L2_MI_MASK\fP   (BIT6)"
.PP
Definition at line 303 of file display\&.h\&.
.SS "#define \fBLCD_UNIT_L2_MI_MEM\fP   (\fBLCD_MEM_7\fP)"
.PP
Definition at line 259 of file display\&.h\&.
.SS "#define \fBLINE1\fP   (1u)"
.PP
Definition at line 104 of file display\&.h\&.
.SS "#define \fBLINE2\fP   (2u)"
.PP
Definition at line 105 of file display\&.h\&.
.SS "#define \fBSEG_A\fP   (BIT4)"
.PP
Definition at line 115 of file display\&.h\&.
.SS "#define \fBSEG_B\fP   (BIT5)"
.PP
Definition at line 116 of file display\&.h\&.
.SS "#define \fBSEG_C\fP   (BIT6)"
.PP
Definition at line 117 of file display\&.h\&.
.SS "#define \fBSEG_D\fP   (BIT7)"
.PP
Definition at line 118 of file display\&.h\&.
.SS "#define \fBSEG_E\fP   (BIT2)"
.PP
Definition at line 119 of file display\&.h\&.
.SS "#define \fBSEG_F\fP   (BIT0)"
.PP
Definition at line 120 of file display\&.h\&.
.SS "#define \fBSEG_G\fP   (BIT1)"
.PP
Definition at line 121 of file display\&.h\&.
.SS "#define \fBSEG_OFF\fP   (0u)"
.PP
Definition at line 108 of file display\&.h\&.
.SS "#define \fBSEG_OFF_BLINK_OFF\fP   (4u)"
.PP
Definition at line 112 of file display\&.h\&.
.SS "#define \fBSEG_ON\fP   (1u)"
.PP
Definition at line 109 of file display\&.h\&.
.SS "#define \fBSEG_ON_BLINK_OFF\fP   (3u)"
.PP
Definition at line 111 of file display\&.h\&.
.SS "#define \fBSEG_ON_BLINK_ON\fP   (2u)"
.PP
Definition at line 110 of file display\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBclear_blink_mem\fP (void)"
.PP
Definition at line 553 of file display\&.c\&.
.SS "void \fBclear_display\fP (void)"
.PP
Definition at line 145 of file display\&.c\&.
.SS "void \fBclear_display_all\fP (void)"
.PP
Definition at line 126 of file display\&.c\&.
.SS "void \fBclear_line\fP (u8line)"
.PP
Definition at line 158 of file display\&.c\&.
.SS "void \fBdisplay_am_pm_symbol\fP (u8timeAM)"
.PP
Definition at line 350 of file display\&.c\&.
.SS "void \fBdisplay_char\fP (u8segment, u8chr, u8mode)"
.PP
Definition at line 404 of file display\&.c\&.
.SS "void \fBdisplay_chars\fP (u8segments, u8 *str, u8mode)"
.PP
Definition at line 465 of file display\&.c\&.
.SS "void \fBdisplay_hours1\fP (u8segments, u32value, u8digits, u8blanks)"
.PP
Definition at line 323 of file display\&.c\&.
.SS "void \fBdisplay_symbol\fP (u8symbol, u8mode)"
.PP
Definition at line 373 of file display\&.c\&.
.SS "void \fBdisplay_value1\fP (u8segments, u32value, u8digits, u8blanks)"
.PP
Definition at line 301 of file display\&.c\&.
.SS "void \fBDisplayTime\fP (u8updateMode)"
.SS "u8* \fBitoa\fP (u32n, u8digits, u8blanks)"
.PP
Definition at line 242 of file display\&.c\&.
.SS "void \fBlcd_init\fP (void)"
.PP
Definition at line 93 of file display\&.c\&.
.SS "void \fBset_blink_rate\fP (u8bits)"
.PP
Definition at line 565 of file display\&.c\&.
.SS "void \fBstart_blink\fP (void)"
.PP
Definition at line 529 of file display\&.c\&.
.SS "void \fBstop_blink\fP (void)"
.PP
Definition at line 541 of file display\&.c\&.
.SS "u8 \fBswitch_seg\fP (u8line, u8index1, u8index2)"
.PP
Definition at line 510 of file display\&.c\&.
.SS "void \fBwrite_lcd_mem\fP (u8 *lcdmem, u8bits, u8bitmask, u8state)"
.PP
Definition at line 185 of file display\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "volatile \fBs_display_flags\fP \fBdisplay\fP"
.PP
Definition at line 75 of file display\&.c\&.
.SS "const u8 \fBitoa_conversion_table\fP[][3]"
.PP
Definition at line 209 of file display1\&.c\&.
.SS "const u8 \fBlcd_font\fP[]"
.PP
Definition at line 62 of file display1\&.c\&.
.SS "const u8 \fBsegments_bitmask\fP[]"
.PP
Definition at line 161 of file display1\&.c\&.
.SS "const u8* \fBsegments_lcdmem\fP[]"
.PP
Definition at line 113 of file display1\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
