.TH "logic/display2.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/display2.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'display2\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdisplay_charSegments\fP (u8 segment, u8 charSegments, u8 mode)"
.br
.ti -1c
.RI "void \fBdisplay_OFF_ON\fP (u8 segments, u32 value, u8 digits, u8 blanks)"
.br
.ti -1c
.RI "void \fBdisplay_CONT_ONCE\fP (u8 segments, u32 value, u8 digits, u8 blanks)"
.br
.ti -1c
.RI "void \fBdisplay_NO_YES\fP (u8 segments, u32 value, u8 digits, u8 blanks)"
.br
.ti -1c
.RI "void \fBdisplay_NO_YES_AUTO_MAN\fP (u8 segments, u32 value, u8 digits, u8 blanks)"
.br
.ti -1c
.RI "void \fBdisplay_SW_Version\fP (u8 segments, u32 value, u8 digits, u8 blanks)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBdisplay_charSegments\fP (u8segment, u8charSegments, u8mode)"
.PP
Definition at line 81 of file display2\&.c\&.
.SS "void \fBdisplay_CONT_ONCE\fP (u8segments, u32value, u8digits, u8blanks)"
.PP
Definition at line 146 of file display2\&.c\&.
.SS "void \fBdisplay_NO_YES\fP (u8segments, u32value, u8digits, u8blanks)"
.PP
Definition at line 162 of file display2\&.c\&.
.SS "void \fBdisplay_NO_YES_AUTO_MAN\fP (u8segments, u32value, u8digits, u8blanks)"
.PP
Definition at line 178 of file display2\&.c\&.
.SS "void \fBdisplay_OFF_ON\fP (u8segments, u32value, u8digits, u8blanks)"
.PP
Definition at line 130 of file display2\&.c\&.
.SS "void \fBdisplay_SW_Version\fP (u8segments, u32value, u8digits, u8blanks)"
.PP
Definition at line 196 of file display2\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
