.TH "logic/menu.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/menu.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBmenu\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L1_Time\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L1_Alarm\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L1_Altitude\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L1_Temperature\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L1_Heartrate\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L1_Speed\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L1_Acceleration\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_Date\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_Stopwatch\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_Battery\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_Rf\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_Ppt\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_Sync\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_CalDist\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_RFBSL\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_cdtimer\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_random\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_agility\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_number_storage\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP * \fBptrMenu_L1\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP * \fBptrMenu_L2\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "struct \fBmenu\fP \fBmenu_L1_Acceleration\fP"
.PP
Definition at line 186 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L1_Alarm\fP"
.PP
Definition at line 140 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L1_Altitude\fP"
.PP
Definition at line 77 of file menu\&.h\&.
.SS "struct \fBmenu\fP \fBmenu_L1_Heartrate\fP"
.SS "struct \fBmenu\fP \fBmenu_L1_Speed\fP"
.SS "struct \fBmenu\fP \fBmenu_L1_Temperature\fP"
.PP
Definition at line 149 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L1_Time\fP"
.PP
Definition at line 131 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_agility\fP"
.PP
Definition at line 223 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_Battery\fP"
.PP
Definition at line 250 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_CalDist\fP"
.SS "struct \fBmenu\fP \fBmenu_L2_cdtimer\fP"
.PP
Definition at line 214 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_Date\fP"
.PP
Definition at line 196 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_number_storage\fP"
.PP
Definition at line 232 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_Ppt\fP"
.PP
Definition at line 268 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_random\fP"
.PP
Definition at line 241 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_Rf\fP"
.PP
Definition at line 259 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_RFBSL\fP"
.PP
Definition at line 296 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_Stopwatch\fP"
.PP
Definition at line 205 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_Sync\fP"
.PP
Definition at line 277 of file menu\&.c\&.
.SS "struct \fBmenu\fP* \fBptrMenu_L1\fP"
.PP
Definition at line 75 of file menu\&.c\&.
.SS "struct \fBmenu\fP* \fBptrMenu_L2\fP"
.PP
Definition at line 76 of file menu\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
