.TH "simpliciti/Components/mrfi/mrfi.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpliciti/Components/mrfi/mrfi.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bsp\&.h'\fP
.br
\fC#include 'mrfi_defs\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBmrfiPacket_t\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMRFI_NUM_LOGICAL_CHANS\fP   __mrfi_NUM_LOGICAL_CHANS__"
.br
.ti -1c
.RI "#define \fBMRFI_NUM_POWER_SETTINGS\fP   __mrfi_NUM_POWER_SETTINGS__"
.br
.ti -1c
.RI "#define \fBMRFI_TX_RESULT_SUCCESS\fP   0"
.br
.ti -1c
.RI "#define \fBMRFI_TX_RESULT_FAILED\fP   1"
.br
.ti -1c
.RI "#define \fBMRFI_TX_TYPE_FORCED\fP   0"
.br
.ti -1c
.RI "#define \fBMRFI_TX_TYPE_CCA\fP   1"
.br
.ti -1c
.RI "#define \fBNWK_HDR_SIZE\fP   3"
.br
.ti -1c
.RI "#define \fBNWK_PAYLOAD\fP   MAX_NWK_PAYLOAD"
.br
.ti -1c
.RI "#define \fBMRFI_ADDR_SIZE\fP   __mrfi_ADDR_SIZE__"
.br
.ti -1c
.RI "#define \fBMRFI_MAX_PAYLOAD_SIZE\fP   __mrfi_MAX_PAYLOAD_SIZE__"
.br
.ti -1c
.RI "#define \fBMRFI_MAX_FRAME_SIZE\fP   (\fBMRFI_MAX_PAYLOAD_SIZE\fP + __mrfi_FRAME_OVERHEAD_SIZE__)"
.br
.ti -1c
.RI "#define \fBMRFI_RX_METRICS_SIZE\fP   __mrfi_RX_METRICS_SIZE__"
.br
.ti -1c
.RI "#define \fBMRFI_RX_METRICS_RSSI_OFS\fP   __mrfi_RX_METRICS_RSSI_OFS__"
.br
.ti -1c
.RI "#define \fBMRFI_RX_METRICS_CRC_LQI_OFS\fP   __mrfi_RX_METRICS_CRC_LQI_OFS__"
.br
.ti -1c
.RI "#define \fBMRFI_RADIO_STATE_UNKNOWN\fP   0"
.br
.ti -1c
.RI "#define \fBMRFI_RADIO_STATE_OFF\fP   1"
.br
.ti -1c
.RI "#define \fBMRFI_RADIO_STATE_IDLE\fP   2"
.br
.ti -1c
.RI "#define \fBMRFI_RADIO_STATE_RX\fP   3"
.br
.ti -1c
.RI "#define \fBPLATFORM_FACTOR_CONSTANT\fP   (2 + 2*(\fBMAX_HOPS\fP*(\fBMRFI_CCA_RETRIES\fP*(8*\fBMRFI_BACKOFF_PERIOD_USECS\fP)/1000)))"
.br
.ti -1c
.RI "#define \fBMRFI_GET_PAYLOAD_LEN\fP(\fBp\fP)   __mrfi_GET_PAYLOAD_LEN__(\fBp\fP)"
.br
.ti -1c
.RI "#define \fBMRFI_SET_PAYLOAD_LEN\fP(\fBp\fP, x)   __mrfi_SET_PAYLOAD_LEN__(\fBp\fP,x)"
.br
.ti -1c
.RI "#define \fBMRFI_P_DST_ADDR\fP(\fBp\fP)   \fB__mrfi_P_DST_ADDR__\fP(\fBp\fP)"
.br
.ti -1c
.RI "#define \fBMRFI_P_SRC_ADDR\fP(\fBp\fP)   \fB__mrfi_P_SRC_ADDR__\fP(\fBp\fP)"
.br
.ti -1c
.RI "#define \fBMRFI_P_PAYLOAD\fP(\fBp\fP)   \fB__mrfi_P_PAYLOAD__\fP(\fBp\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMRFI_Init\fP (void)"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBMRFI_Transmit\fP (\fBmrfiPacket_t\fP *, \fBuint8_t\fP)"
.br
.ti -1c
.RI "void \fBMRFI_Receive\fP (\fBmrfiPacket_t\fP *)"
.br
.ti -1c
.RI "void \fBMRFI_RxCompleteISR\fP (void)"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBMRFI_GetRadioState\fP (void)"
.br
.ti -1c
.RI "void \fBMRFI_RxOn\fP (void)"
.br
.ti -1c
.RI "void \fBMRFI_RxIdle\fP (void)"
.br
.ti -1c
.RI "\fBint8_t\fP \fBMRFI_Rssi\fP (void)"
.br
.ti -1c
.RI "void \fBMRFI_SetLogicalChannel\fP (\fBuint8_t\fP)"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBMRFI_SetRxAddrFilter\fP (\fBuint8_t\fP *)"
.br
.ti -1c
.RI "void \fBMRFI_EnableRxAddrFilter\fP (void)"
.br
.ti -1c
.RI "void \fBMRFI_DisableRxAddrFilter\fP (void)"
.br
.ti -1c
.RI "void \fBMRFI_Sleep\fP (void)"
.br
.ti -1c
.RI "void \fBMRFI_WakeUp\fP (void)"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBMRFI_RandomByte\fP (void)"
.br
.ti -1c
.RI "void \fBMRFI_DelayMs\fP (\fBuint16_t\fP)"
.br
.ti -1c
.RI "void \fBMRFI_ReplyDelay\fP (void)"
.br
.ti -1c
.RI "void \fBMRFI_PostKillSem\fP (void)"
.br
.ti -1c
.RI "void \fBMRFI_SetRFPwr\fP (\fBuint8_t\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBuint8_t\fP \fBmrfiBroadcastAddr\fP []"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBMRFI_ADDR_SIZE\fP   __mrfi_ADDR_SIZE__"
.PP
Definition at line 99 of file mrfi\&.h\&.
.SS "#define \fBMRFI_GET_PAYLOAD_LEN\fP(\fBp\fP)   __mrfi_GET_PAYLOAD_LEN__(\fBp\fP)"
.PP
Definition at line 131 of file mrfi\&.h\&.
.SS "#define \fBMRFI_MAX_FRAME_SIZE\fP   (\fBMRFI_MAX_PAYLOAD_SIZE\fP + __mrfi_FRAME_OVERHEAD_SIZE__)"
.PP
Definition at line 103 of file mrfi\&.h\&.
.SS "#define \fBMRFI_MAX_PAYLOAD_SIZE\fP   __mrfi_MAX_PAYLOAD_SIZE__"
.PP
Definition at line 101 of file mrfi\&.h\&.
.SS "#define \fBMRFI_NUM_LOGICAL_CHANS\fP   __mrfi_NUM_LOGICAL_CHANS__"
.PP
Definition at line 54 of file mrfi\&.h\&.
.SS "#define \fBMRFI_NUM_POWER_SETTINGS\fP   __mrfi_NUM_POWER_SETTINGS__"
.PP
Definition at line 56 of file mrfi\&.h\&.
.SS "#define \fBMRFI_P_DST_ADDR\fP(\fBp\fP)   \fB__mrfi_P_DST_ADDR__\fP(\fBp\fP)"
.PP
Definition at line 134 of file mrfi\&.h\&.
.SS "#define \fBMRFI_P_PAYLOAD\fP(\fBp\fP)   \fB__mrfi_P_PAYLOAD__\fP(\fBp\fP)"
.PP
Definition at line 136 of file mrfi\&.h\&.
.SS "#define \fBMRFI_P_SRC_ADDR\fP(\fBp\fP)   \fB__mrfi_P_SRC_ADDR__\fP(\fBp\fP)"
.PP
Definition at line 135 of file mrfi\&.h\&.
.SS "#define \fBMRFI_RADIO_STATE_IDLE\fP   2"
.PP
Definition at line 111 of file mrfi\&.h\&.
.SS "#define \fBMRFI_RADIO_STATE_OFF\fP   1"
.PP
Definition at line 110 of file mrfi\&.h\&.
.SS "#define \fBMRFI_RADIO_STATE_RX\fP   3"
.PP
Definition at line 112 of file mrfi\&.h\&.
.SS "#define \fBMRFI_RADIO_STATE_UNKNOWN\fP   0"
.PP
Definition at line 109 of file mrfi\&.h\&.
.SS "#define \fBMRFI_RX_METRICS_CRC_LQI_OFS\fP   __mrfi_RX_METRICS_CRC_LQI_OFS__"
.PP
Definition at line 106 of file mrfi\&.h\&.
.SS "#define \fBMRFI_RX_METRICS_RSSI_OFS\fP   __mrfi_RX_METRICS_RSSI_OFS__"
.PP
Definition at line 105 of file mrfi\&.h\&.
.SS "#define \fBMRFI_RX_METRICS_SIZE\fP   __mrfi_RX_METRICS_SIZE__"
.PP
Definition at line 104 of file mrfi\&.h\&.
.SS "#define \fBMRFI_SET_PAYLOAD_LEN\fP(\fBp\fP, x)   __mrfi_SET_PAYLOAD_LEN__(\fBp\fP,x)"
.PP
Definition at line 132 of file mrfi\&.h\&.
.SS "#define \fBMRFI_TX_RESULT_FAILED\fP   1"
.PP
Definition at line 60 of file mrfi\&.h\&.
.SS "#define \fBMRFI_TX_RESULT_SUCCESS\fP   0"
.PP
Definition at line 59 of file mrfi\&.h\&.
.SS "#define \fBMRFI_TX_TYPE_CCA\fP   1"
.PP
Definition at line 64 of file mrfi\&.h\&.
.SS "#define \fBMRFI_TX_TYPE_FORCED\fP   0"
.PP
Definition at line 63 of file mrfi\&.h\&.
.SS "#define \fBNWK_HDR_SIZE\fP   3"
.PP
Definition at line 77 of file mrfi\&.h\&.
.SS "#define \fBNWK_PAYLOAD\fP   MAX_NWK_PAYLOAD"
.PP
Definition at line 78 of file mrfi\&.h\&.
.SS "#define \fBPLATFORM_FACTOR_CONSTANT\fP   (2 + 2*(\fBMAX_HOPS\fP*(\fBMRFI_CCA_RETRIES\fP*(8*\fBMRFI_BACKOFF_PERIOD_USECS\fP)/1000)))"
.PP
Definition at line 124 of file mrfi\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBMRFI_DelayMs\fP (\fBuint16_t\fP)"
.PP
Definition at line 1450 of file mrfi_radio\&.c\&.
.SS "void \fBMRFI_DisableRxAddrFilter\fP (void)"
.PP
Definition at line 1657 of file mrfi_radio\&.c\&.
.SS "void \fBMRFI_EnableRxAddrFilter\fP (void)"
.PP
Definition at line 1635 of file mrfi_radio\&.c\&.
.SS "\fBuint8_t\fP \fBMRFI_GetRadioState\fP (void)"
.PP
Definition at line 1529 of file mrfi_radio\&.c\&.
.SS "void \fBMRFI_Init\fP (void)"
.PP
Definition at line 383 of file mrfi_radio\&.c\&.
.SS "void \fBMRFI_PostKillSem\fP (void)"
.PP
Definition at line 1508 of file mrfi_radio\&.c\&.
.SS "\fBuint8_t\fP \fBMRFI_RandomByte\fP (void)"
.PP
Definition at line 1337 of file mrfi_radio\&.c\&.
.SS "void \fBMRFI_Receive\fP (\fBmrfiPacket_t\fP *)"
.PP
Definition at line 787 of file mrfi_radio\&.c\&.
.SS "void \fBMRFI_ReplyDelay\fP (void)"
.PP
Definition at line 1472 of file mrfi_radio\&.c\&.
.SS "\fBint8_t\fP \fBMRFI_Rssi\fP (void)"
.PP
Definition at line 1267 of file mrfi_radio\&.c\&.
.SS "void \fBMRFI_RxCompleteISR\fP (void)"
.SS "void \fBMRFI_RxIdle\fP (void)"
.PP
Definition at line 1084 of file mrfi_radio\&.c\&.
.SS "void \fBMRFI_RxOn\fP (void)"
.PP
Definition at line 1034 of file mrfi_radio\&.c\&.
.SS "void \fBMRFI_SetLogicalChannel\fP (\fBuint8_t\fP)"
.PP
Definition at line 1545 of file mrfi_radio\&.c\&.
.SS "void \fBMRFI_SetRFPwr\fP (\fBuint8_t\fP)"
.PP
Definition at line 1572 of file mrfi_radio\&.c\&.
.SS "\fBuint8_t\fP \fBMRFI_SetRxAddrFilter\fP (\fBuint8_t\fP *)"
.PP
Definition at line 1592 of file mrfi_radio\&.c\&.
.SS "void \fBMRFI_Sleep\fP (void)"
.PP
Definition at line 1108 of file mrfi_radio\&.c\&.
.SS "\fBuint8_t\fP \fBMRFI_Transmit\fP (\fBmrfiPacket_t\fP *, \fBuint8_t\fP)"
.PP
Definition at line 605 of file mrfi_radio\&.c\&.
.SS "void \fBMRFI_WakeUp\fP (void)"
.PP
Definition at line 1148 of file mrfi_radio\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBuint8_t\fP \fBmrfiBroadcastAddr\fP[]"
.PP
Definition at line 56 of file mrfi_radio\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
