.TH "simpliciti/Components/mrfi/mrfi.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpliciti/Components/mrfi/mrfi.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mrfi_defs\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
