.TH "simpliciti/Components/nwk_applications/nwk_ioctl.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpliciti/Components/nwk_applications/nwk_ioctl.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsmplStatus_t\fP \fBnwk_rawSend\fP (\fBioctlRawSend_t\fP *)"
.br
.ti -1c
.RI "\fBsmplStatus_t\fP \fBnwk_rawReceive\fP (\fBioctlRawReceive_t\fP *)"
.br
.ti -1c
.RI "\fBsmplStatus_t\fP \fBnwk_radioControl\fP (\fBioctlAction_t\fP, void *)"
.br
.ti -1c
.RI "\fBsmplStatus_t\fP \fBnwk_deviceAddress\fP (\fBioctlAction_t\fP, \fBaddr_t\fP *)"
.br
.ti -1c
.RI "\fBsmplStatus_t\fP \fBnwk_connectionControl\fP (\fBioctlAction_t\fP, void *)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBsmplStatus_t\fP \fBnwk_connectionControl\fP (\fBioctlAction_t\fP, void *)"
.PP
Definition at line 330 of file nwk_ioctl\&.c\&.
.SS "\fBsmplStatus_t\fP \fBnwk_deviceAddress\fP (\fBioctlAction_t\fP, \fBaddr_t\fP *)"
.PP
Definition at line 293 of file nwk_ioctl\&.c\&.
.SS "\fBsmplStatus_t\fP \fBnwk_radioControl\fP (\fBioctlAction_t\fP, void *)"
.PP
Definition at line 176 of file nwk_ioctl\&.c\&.
.SS "\fBsmplStatus_t\fP \fBnwk_rawReceive\fP (\fBioctlRawReceive_t\fP *)"
.PP
Definition at line 154 of file nwk_ioctl\&.c\&.
.SS "\fBsmplStatus_t\fP \fBnwk_rawSend\fP (\fBioctlRawSend_t\fP *)"
.PP
Definition at line 102 of file nwk_ioctl\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
