.TH "simpliciti/Components/nwk_applications/nwk_security.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpliciti/Components/nwk_applications/nwk_security.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'mrfi\&.h'\fP
.br
\fC#include 'nwk_types\&.h'\fP
.br
\fC#include 'nwk_security\&.h'\fP
.br
\fC#include 'nwk_frame\&.h'\fP
.br
\fC#include 'nwk\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnwk_securityInit\fP (void)"
.br
.ti -1c
.RI "\fBfhStatus_t\fP \fBnwk_processSecurity\fP (\fBmrfiPacket_t\fP *frame)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBfhStatus_t\fP \fBnwk_processSecurity\fP (\fBmrfiPacket_t\fP *frame)"
.PP
Definition at line 185 of file nwk_security\&.c\&.
.SS "void \fBnwk_securityInit\fP (void)"
.PP
Definition at line 154 of file nwk_security\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
