.TH "simpliciti/Components/nwk_applications/nwk_freq.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpliciti/Components/nwk_applications/nwk_freq.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBFB_APP_INFO_OS\fP   0"
.br
.ti -1c
.RI "#define \fBFB_TID_OS\fP   1"
.br
.ti -1c
.RI "#define \fBF_CHAN_OS\fP   1"
.br
.ti -1c
.RI "#define \fBFREQ_REQ_MOVE\fP   0x01"
.br
.ti -1c
.RI "#define \fBFREQ_REQ_PING\fP   0x02"
.br
.ti -1c
.RI "#define \fBFREQ_REQ_REQ_MOVE\fP   0x03"
.br
.ti -1c
.RI "#define \fBMAX_FREQ_APP_FRAME\fP   2"
.br
.ti -1c
.RI "#define \fBFREQ_REQ_MOVE_FRAME_SIZE\fP   2"
.br
.ti -1c
.RI "#define \fBFREQ_REQ_PING_FRAME_SIZE\fP   2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnwk_freqInit\fP (void)"
.br
.ti -1c
.RI "\fBfhStatus_t\fP \fBnwk_processFreq\fP (\fBmrfiPacket_t\fP *)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBF_CHAN_OS\fP   1"
.PP
Definition at line 48 of file nwk_freq\&.h\&.
.SS "#define \fBFB_APP_INFO_OS\fP   0"
.PP
Definition at line 41 of file nwk_freq\&.h\&.
.SS "#define \fBFB_TID_OS\fP   1"
.PP
Definition at line 42 of file nwk_freq\&.h\&.
.SS "#define \fBFREQ_REQ_MOVE\fP   0x01"
.PP
Definition at line 51 of file nwk_freq\&.h\&.
.SS "#define \fBFREQ_REQ_MOVE_FRAME_SIZE\fP   2"
.PP
Definition at line 59 of file nwk_freq\&.h\&.
.SS "#define \fBFREQ_REQ_PING\fP   0x02"
.PP
Definition at line 52 of file nwk_freq\&.h\&.
.SS "#define \fBFREQ_REQ_PING_FRAME_SIZE\fP   2"
.PP
Definition at line 60 of file nwk_freq\&.h\&.
.SS "#define \fBFREQ_REQ_REQ_MOVE\fP   0x03"
.PP
Definition at line 53 of file nwk_freq\&.h\&.
.SS "#define \fBMAX_FREQ_APP_FRAME\fP   2"
.PP
Definition at line 56 of file nwk_freq\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBnwk_freqInit\fP (void)"
.PP
Definition at line 598 of file nwk_freq\&.c\&.
.SS "\fBfhStatus_t\fP \fBnwk_processFreq\fP (\fBmrfiPacket_t\fP *)"
.PP
Definition at line 614 of file nwk_freq\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
