.TH "simpliciti/Components/nwk_applications/nwk_mgmt.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpliciti/Components/nwk_applications/nwk_mgmt.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'bsp\&.h'\fP
.br
\fC#include 'mrfi\&.h'\fP
.br
\fC#include 'nwk_types\&.h'\fP
.br
\fC#include 'nwk_api\&.h'\fP
.br
\fC#include 'nwk_frame\&.h'\fP
.br
\fC#include 'nwk\&.h'\fP
.br
\fC#include 'nwk_mgmt\&.h'\fP
.br
\fC#include 'nwk_join\&.h'\fP
.br
\fC#include 'nwk_globals\&.h'\fP
.br
\fC#include 'nwk_QMgmt\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBsmpl_send_mgmt_reply\fP (\fBmrfiPacket_t\fP *)"
.br
.ti -1c
.RI "void \fBnwk_mgmtInit\fP (void)"
.br
.ti -1c
.RI "\fBfhStatus_t\fP \fBnwk_processMgmt\fP (\fBmrfiPacket_t\fP *frame)"
.br
.ti -1c
.RI "\fBsmplStatus_t\fP \fBnwk_poll\fP (\fBuint8_t\fP port, \fBuint8_t\fP *addr)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static \fBaddr_t\fP const * \fBsAPAddr\fP = \fBNULL\fP"
.br
.ti -1c
.RI "static volatile \fBuint8_t\fP \fBsTid\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBnwk_mgmtInit\fP (void)"
.PP
Definition at line 103 of file nwk_mgmt\&.c\&.
.SS "\fBsmplStatus_t\fP \fBnwk_poll\fP (\fBuint8_t\fPport, \fBuint8_t\fP *addr)"
.PP
Definition at line 317 of file nwk_mgmt\&.c\&.
.SS "\fBfhStatus_t\fP \fBnwk_processMgmt\fP (\fBmrfiPacket_t\fP *frame)"
.PP
Definition at line 128 of file nwk_mgmt\&.c\&.
.SS "static void \fBsmpl_send_mgmt_reply\fP (\fBmrfiPacket_t\fP *frame)\fC [static]\fP"
.PP
Definition at line 185 of file nwk_mgmt\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBaddr_t\fP const* \fBsAPAddr\fP = \fBNULL\fP\fC [static]\fP"
.PP
Definition at line 68 of file nwk_mgmt\&.c\&.
.SS "volatile \fBuint8_t\fP \fBsTid\fP = 0\fC [static]\fP"
.PP
Definition at line 73 of file nwk_mgmt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
