.TH "simpliciti/Components/nwk_applications/nwk_security.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpliciti/Components/nwk_applications/nwk_security.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAX_SEC_APP_FRAME\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnwk_securityInit\fP (void)"
.br
.ti -1c
.RI "\fBfhStatus_t\fP \fBnwk_processSecurity\fP (\fBmrfiPacket_t\fP *)"
.br
.ti -1c
.RI "void \fBnwk_setSecureFrame\fP (\fBmrfiPacket_t\fP *, \fBuint8_t\fP, \fBuint32_t\fP *)"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBnwk_getSecureFrame\fP (\fBmrfiPacket_t\fP *, \fBuint8_t\fP, \fBuint32_t\fP *)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBMAX_SEC_APP_FRAME\fP   0"
.PP
Definition at line 41 of file nwk_security\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBuint8_t\fP \fBnwk_getSecureFrame\fP (\fBmrfiPacket_t\fP *, \fBuint8_t\fP, \fBuint32_t\fP *)"
.SS "\fBfhStatus_t\fP \fBnwk_processSecurity\fP (\fBmrfiPacket_t\fP *)"
.PP
Definition at line 185 of file nwk_security\&.c\&.
.SS "void \fBnwk_securityInit\fP (void)"
.PP
Definition at line 154 of file nwk_security\&.c\&.
.SS "void \fBnwk_setSecureFrame\fP (\fBmrfiPacket_t\fP *, \fBuint8_t\fP, \fBuint32_t\fP *)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
