.TH "simpliciti/Components/nwk_applications/nwk_join.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpliciti/Components/nwk_applications/nwk_join.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'bsp\&.h'\fP
.br
\fC#include 'mrfi\&.h'\fP
.br
\fC#include 'nwk_types\&.h'\fP
.br
\fC#include 'nwk_api\&.h'\fP
.br
\fC#include 'nwk_frame\&.h'\fP
.br
\fC#include 'nwk\&.h'\fP
.br
\fC#include 'nwk_link\&.h'\fP
.br
\fC#include 'nwk_join\&.h'\fP
.br
\fC#include 'nwk_globals\&.h'\fP
.br
\fC#include 'nwk_freq\&.h'\fP
.br
\fC#include 'nwk_security\&.h'\fP
.br
\fC#include 'nwk_mgmt\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnwk_joinInit\fP (\fBuint8_t\fP(*pf)(\fBlinkID_t\fP))"
.br
.ti -1c
.RI "void \fBnwk_setJoinToken\fP (\fBuint32_t\fP token)"
.br
.ti -1c
.RI "void \fBnwk_getJoinToken\fP (\fBuint32_t\fP *pToken)"
.br
.ti -1c
.RI "\fBsmplStatus_t\fP \fBnwk_join\fP (void)"
.br
.ti -1c
.RI "\fBfhStatus_t\fP \fBnwk_processJoin\fP (\fBmrfiPacket_t\fP *frame)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static \fBuint32_t\fP \fBsJoinToken\fP = 0"
.br
.ti -1c
.RI "static \fBuint8_t\fP(* \fBspCallback\fP )(\fBlinkID_t\fP) = \fBNULL\fP"
.br
.ti -1c
.RI "static volatile \fBuint8_t\fP \fBsTid\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBnwk_getJoinToken\fP (\fBuint32_t\fP *pToken)"
.PP
Definition at line 170 of file nwk_join\&.c\&.
.SS "\fBsmplStatus_t\fP \fBnwk_join\fP (void)"
.PP
Definition at line 438 of file nwk_join\&.c\&.
.SS "void \fBnwk_joinInit\fP (\fBuint8_t\fP(*)(\fBlinkID_t\fP)pf)"
.PP
Definition at line 106 of file nwk_join\&.c\&.
.SS "\fBfhStatus_t\fP \fBnwk_processJoin\fP (\fBmrfiPacket_t\fP *frame)"
.PP
Definition at line 540 of file nwk_join\&.c\&.
.SS "void \fBnwk_setJoinToken\fP (\fBuint32_t\fPtoken)"
.PP
Definition at line 147 of file nwk_join\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBuint32_t\fP \fBsJoinToken\fP = 0\fC [static]\fP"
.PP
Definition at line 69 of file nwk_join\&.c\&.
.SS "\fBuint8_t\fP(* \fBspCallback\fP)(\fBlinkID_t\fP) = \fBNULL\fP\fC [static]\fP"
.PP
Definition at line 70 of file nwk_join\&.c\&.
.SS "volatile \fBuint8_t\fP \fBsTid\fP = 0\fC [static]\fP"
.PP
Definition at line 71 of file nwk_join\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
