.TH "Original Code/V2.2/simpliciti/Components/nwk/nwk_types.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/simpliciti/Components/nwk/nwk_types.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBaddr_t\fP"
.br
.ti -1c
.RI "struct \fBioctlRawSend_t\fP"
.br
.ti -1c
.RI "struct \fBioctlRawReceive_t\fP"
.br
.ti -1c
.RI "struct \fBrxMetrics_t\fP"
.br
.ti -1c
.RI "struct \fBioctlRadioSiginfo_t\fP"
.br
.ti -1c
.RI "union \fBtoken_t\fP"
.br
.ti -1c
.RI "struct \fBioctlToken_t\fP"
.br
.ti -1c
.RI "struct \fBfreqEntry_t\fP"
.br
.ti -1c
.RI "struct \fBioctlScanChan_t\fP"
.br
.ti -1c
.RI "struct \fBioctlNVObj_t\fP"
.br
.ti -1c
.RI "struct \fBrcvContext_t\fP"
.br
.ti -1c
.RI "struct \fBsmplVersionInfo_t\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNWK_TX_RETRY_COUNT\fP   10"
.br
.ti -1c
.RI "#define \fBNWK_RX_RETRY_COUNT\fP   10"
.br
.ti -1c
.RI "#define \fBNWK_APP_REPLY_BIT\fP   (0x80)"
.br
.ti -1c
.RI "#define \fBNET_ADDR_SIZE\fP   \fBMRFI_ADDR_SIZE\fP   /* size of address in bytes */"
.br
.ti -1c
.RI "#define \fBNWK_FREQ_TBL_SIZE\fP   1"
.br
.ti -1c
.RI "#define \fBSMPL_FWVERSION_SIZE\fP   4"
.br
.ti -1c
.RI "#define \fBNWK_DELAY\fP(spin)   \fBMRFI_DelayMs\fP(spin)"
.br
.ti -1c
.RI "#define \fBNWK_REPLY_DELAY\fP()   \fBMRFI_ReplyDelay\fP();"
.br
.ti -1c
.RI "#define \fBNWK_CHECK_FOR_SETRX\fP(s)"
.br
.ti -1c
.RI "#define \fBNWK_CHECK_FOR_RESTORE_STATE\fP(s)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBuint8_t\fP \fBlinkID_t\fP"
.br
.ti -1c
.RI "typedef \fBuint8_t\fP \fBccRadioStatus_t\fP"
.br
.ti -1c
.RI "typedef enum \fBioctlObject\fP \fBioctlObject_t\fP"
.br
.ti -1c
.RI "typedef enum \fBioctlAction\fP \fBioctlAction_t\fP"
.br
.ti -1c
.RI "typedef enum \fBioctlLevel\fP \fBioctlLevel_t\fP"
.br
.ti -1c
.RI "typedef \fBint8_t\fP \fBrssi_t\fP"
.br
.ti -1c
.RI "typedef enum \fBtokenType\fP \fBtokenType_t\fP"
.br
.ti -1c
.RI "typedef \fBuint8_t\fP \fBsecMAC_t\fP"
.br
.ti -1c
.RI "typedef \fBuint8_t\fP \fBsecFCS_t\fP"
.br
.ti -1c
.RI "typedef enum \fBsmplStatus\fP \fBsmplStatus_t\fP"
.br
.ti -1c
.RI "typedef enum \fBfhStatus\fP \fBfhStatus_t\fP"
.br
.ti -1c
.RI "typedef enum \fBrcvType\fP \fBrcvType_t\fP"
.br
.ti -1c
.RI "typedef \fBuint16_t\fP \fBtxOpt_t\fP"
.br
.ti -1c
.RI "typedef \fBuint8_t\fP \fBappPTid_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBioctlObject\fP { \fBIOCTL_OBJ_FREQ\fP, \fBIOCTL_OBJ_CRYPTKEY\fP, \fBIOCTL_OBJ_RAW_IO\fP, \fBIOCTL_OBJ_RADIO\fP, \fBIOCTL_OBJ_AP_JOIN\fP, \fBIOCTL_OBJ_ADDR\fP, \fBIOCTL_OBJ_CONNOBJ\fP, \fBIOCTL_OBJ_FWVER\fP, \fBIOCTL_OBJ_PROTOVER\fP, \fBIOCTL_OBJ_NVOBJ\fP, \fBIOCTL_OBJ_TOKEN\fP }"
.br
.ti -1c
.RI "enum \fBioctlAction\fP { \fBIOCTL_ACT_SET\fP, \fBIOCTL_ACT_GET\fP, \fBIOCTL_ACT_READ\fP, \fBIOCTL_ACT_WRITE\fP, \fBIOCTL_ACT_RADIO_SLEEP\fP, \fBIOCTL_ACT_RADIO_AWAKE\fP, \fBIOCTL_ACT_RADIO_SIGINFO\fP, \fBIOCTL_ACT_RADIO_RSSI\fP, \fBIOCTL_ACT_RADIO_RXON\fP, \fBIOCTL_ACT_RADIO_RXIDLE\fP, \fBIOCTL_ACT_RADIO_SETPWR\fP, \fBIOCTL_ACT_ON\fP, \fBIOCTL_ACT_OFF\fP, \fBIOCTL_ACT_SCAN\fP, \fBIOCTL_ACT_DELETE\fP }"
.br
.ti -1c
.RI "enum \fBioctlLevel\fP { \fBIOCTL_LEVEL_0\fP, \fBIOCTL_LEVEL_1\fP, \fBIOCTL_LEVEL_2\fP }"
.br
.ti -1c
.RI "enum \fBtokenType\fP { \fBTT_LINK\fP, \fBTT_JOIN\fP }"
.br
.ti -1c
.RI "enum \fBsmplStatus\fP { \fBSMPL_SUCCESS\fP, \fBSMPL_TIMEOUT\fP, \fBSMPL_BAD_PARAM\fP, \fBSMPL_NOMEM\fP, \fBSMPL_NO_FRAME\fP, \fBSMPL_NO_LINK\fP, \fBSMPL_NO_JOIN\fP, \fBSMPL_NO_CHANNEL\fP, \fBSMPL_NO_PEER_UNLINK\fP, \fBSMPL_TX_CCA_FAIL\fP, \fBSMPL_NO_PAYLOAD\fP, \fBSMPL_NO_AP_ADDRESS\fP, \fBSMPL_NO_ACK\fP }"
.br
.ti -1c
.RI "enum \fBfhStatus\fP { \fBFHS_RELEASE\fP, \fBFHS_KEEP\fP, \fBFHS_REPLAY\fP }"
.br
.ti -1c
.RI "enum \fBrcvType\fP { \fBRCV_NWK_PORT\fP, \fBRCV_APP_LID\fP, \fBRCV_RAW_POLL_FRAME\fP }"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBNET_ADDR_SIZE\fP   \fBMRFI_ADDR_SIZE\fP   /* size of address in bytes */"
.PP
Definition at line 44 of file nwk_types\&.h\&.
.SS "#define \fBNWK_APP_REPLY_BIT\fP   (0x80)"
.PP
Definition at line 42 of file nwk_types\&.h\&.
.SS "#define \fBNWK_CHECK_FOR_RESTORE_STATE\fP(s)"\fBValue:\fP
.PP
.nf
if (MRFI_RADIO_STATE_RX != s)    \
                                       {                                \
                                         if (MRFI_RADIO_STATE_OFF == s) \
                                         {                              \
                                           MRFI_Sleep();                \
                                         }                              \
                                         else                           \
                                         {                              \
                                           MRFI_RxIdle();               \
                                         }                              \
                                       }
.fi
.PP
Definition at line 333 of file nwk_types\&.h\&.
.SS "#define \fBNWK_CHECK_FOR_SETRX\fP(s)"\fBValue:\fP
.PP
.nf
if (MRFI_RADIO_STATE_RX != s)    \
                                {                                \
                                  if (MRFI_RADIO_STATE_OFF == s) \
                                  {                              \
                                    MRFI_WakeUp();               \
                                  }                              \
                                  MRFI_RxOn();                   \
                                }
.fi
.PP
Definition at line 324 of file nwk_types\&.h\&.
.SS "#define \fBNWK_DELAY\fP(spin)   \fBMRFI_DelayMs\fP(spin)"
.PP
Definition at line 311 of file nwk_types\&.h\&.
.SS "#define \fBNWK_FREQ_TBL_SIZE\fP   1"
.PP
Definition at line 49 of file nwk_types\&.h\&.
.SS "#define \fBNWK_REPLY_DELAY\fP()   \fBMRFI_ReplyDelay\fP();"
.PP
Definition at line 312 of file nwk_types\&.h\&.
.SS "#define \fBNWK_RX_RETRY_COUNT\fP   10"
.PP
Definition at line 40 of file nwk_types\&.h\&.
.SS "#define \fBNWK_TX_RETRY_COUNT\fP   10"
.PP
Definition at line 39 of file nwk_types\&.h\&.
.SS "#define \fBSMPL_FWVERSION_SIZE\fP   4"
.PP
Definition at line 275 of file nwk_types\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBuint8_t\fP \fBappPTid_t\fP"
.PP
Definition at line 289 of file nwk_types\&.h\&.
.SS "typedef \fBuint8_t\fP \fBccRadioStatus_t\fP"
.PP
Definition at line 58 of file nwk_types\&.h\&.
.SS "typedef enum \fBfhStatus\fP \fBfhStatus_t\fP"
.PP
Definition at line 248 of file nwk_types\&.h\&.
.SS "typedef enum \fBioctlAction\fP \fBioctlAction_t\fP"
.PP
Definition at line 98 of file nwk_types\&.h\&.
.SS "typedef enum \fBioctlLevel\fP \fBioctlLevel_t\fP"
.PP
Definition at line 107 of file nwk_types\&.h\&.
.SS "typedef enum \fBioctlObject\fP \fBioctlObject_t\fP"
.PP
Definition at line 97 of file nwk_types\&.h\&.
.SS "typedef \fBuint8_t\fP \fBlinkID_t\fP"
.PP
Definition at line 57 of file nwk_types\&.h\&.
.SS "typedef enum \fBrcvType\fP \fBrcvType_t\fP"
.PP
Definition at line 258 of file nwk_types\&.h\&.
.SS "typedef \fBint8_t\fP \fBrssi_t\fP"
.PP
Definition at line 129 of file nwk_types\&.h\&.
.SS "typedef \fBuint8_t\fP \fBsecFCS_t\fP"
.PP
Definition at line 184 of file nwk_types\&.h\&.
.SS "typedef \fBuint8_t\fP \fBsecMAC_t\fP"
.PP
Definition at line 183 of file nwk_types\&.h\&.
.SS "typedef enum \fBsmplStatus\fP \fBsmplStatus_t\fP"
.PP
Definition at line 238 of file nwk_types\&.h\&.
.SS "typedef enum \fBtokenType\fP \fBtokenType_t\fP"
.PP
Definition at line 151 of file nwk_types\&.h\&.
.SS "typedef \fBuint16_t\fP \fBtxOpt_t\fP"
.PP
Definition at line 261 of file nwk_types\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBfhStatus\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIFHS_RELEASE \fP\fP
.TP
\fB\fIFHS_KEEP \fP\fP
.TP
\fB\fIFHS_REPLAY \fP\fP

.PP
Definition at line 241 of file nwk_types\&.h\&.
.SS "enum \fBioctlAction\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIIOCTL_ACT_SET \fP\fP
.TP
\fB\fIIOCTL_ACT_GET \fP\fP
.TP
\fB\fIIOCTL_ACT_READ \fP\fP
.TP
\fB\fIIOCTL_ACT_WRITE \fP\fP
.TP
\fB\fIIOCTL_ACT_RADIO_SLEEP \fP\fP
.TP
\fB\fIIOCTL_ACT_RADIO_AWAKE \fP\fP
.TP
\fB\fIIOCTL_ACT_RADIO_SIGINFO \fP\fP
.TP
\fB\fIIOCTL_ACT_RADIO_RSSI \fP\fP
.TP
\fB\fIIOCTL_ACT_RADIO_RXON \fP\fP
.TP
\fB\fIIOCTL_ACT_RADIO_RXIDLE \fP\fP
.TP
\fB\fIIOCTL_ACT_RADIO_SETPWR \fP\fP
.TP
\fB\fIIOCTL_ACT_ON \fP\fP
.TP
\fB\fIIOCTL_ACT_OFF \fP\fP
.TP
\fB\fIIOCTL_ACT_SCAN \fP\fP
.TP
\fB\fIIOCTL_ACT_DELETE \fP\fP

.PP
Definition at line 79 of file nwk_types\&.h\&.
.SS "enum \fBioctlLevel\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIIOCTL_LEVEL_0 \fP\fP
.TP
\fB\fIIOCTL_LEVEL_1 \fP\fP
.TP
\fB\fIIOCTL_LEVEL_2 \fP\fP

.PP
Definition at line 100 of file nwk_types\&.h\&.
.SS "enum \fBioctlObject\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIIOCTL_OBJ_FREQ \fP\fP
.TP
\fB\fIIOCTL_OBJ_CRYPTKEY \fP\fP
.TP
\fB\fIIOCTL_OBJ_RAW_IO \fP\fP
.TP
\fB\fIIOCTL_OBJ_RADIO \fP\fP
.TP
\fB\fIIOCTL_OBJ_AP_JOIN \fP\fP
.TP
\fB\fIIOCTL_OBJ_ADDR \fP\fP
.TP
\fB\fIIOCTL_OBJ_CONNOBJ \fP\fP
.TP
\fB\fIIOCTL_OBJ_FWVER \fP\fP
.TP
\fB\fIIOCTL_OBJ_PROTOVER \fP\fP
.TP
\fB\fIIOCTL_OBJ_NVOBJ \fP\fP
.TP
\fB\fIIOCTL_OBJ_TOKEN \fP\fP

.PP
Definition at line 65 of file nwk_types\&.h\&.
.SS "enum \fBrcvType\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIRCV_NWK_PORT \fP\fP
.TP
\fB\fIRCV_APP_LID \fP\fP
.TP
\fB\fIRCV_RAW_POLL_FRAME \fP\fP

.PP
Definition at line 251 of file nwk_types\&.h\&.
.SS "enum \fBsmplStatus\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fISMPL_SUCCESS \fP\fP
.TP
\fB\fISMPL_TIMEOUT \fP\fP
.TP
\fB\fISMPL_BAD_PARAM \fP\fP
.TP
\fB\fISMPL_NOMEM \fP\fP
.TP
\fB\fISMPL_NO_FRAME \fP\fP
.TP
\fB\fISMPL_NO_LINK \fP\fP
.TP
\fB\fISMPL_NO_JOIN \fP\fP
.TP
\fB\fISMPL_NO_CHANNEL \fP\fP
.TP
\fB\fISMPL_NO_PEER_UNLINK \fP\fP
.TP
\fB\fISMPL_TX_CCA_FAIL \fP\fP
.TP
\fB\fISMPL_NO_PAYLOAD \fP\fP
.TP
\fB\fISMPL_NO_AP_ADDRESS \fP\fP
.TP
\fB\fISMPL_NO_ACK \fP\fP

.PP
Definition at line 222 of file nwk_types\&.h\&.
.SS "enum \fBtokenType\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fITT_LINK \fP\fP
.TP
\fB\fITT_JOIN \fP\fP

.PP
Definition at line 145 of file nwk_types\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
