.TH "driver/radio.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
driver/radio.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBradio_reset\fP (void)"
.br
.ti -1c
.RI "void \fBradio_powerdown\fP (void)"
.br
.ti -1c
.RI "void \fBradio_sxoff\fP (void)"
.br
.ti -1c
.RI "void \fBradio_idle\fP (void)"
.br
.ti -1c
.RI "void \fBopen_radio\fP (void)"
.br
.ti -1c
.RI "void \fBclose_radio\fP (void)"
.br
.ti -1c
.RI "void \fBpmm_set_high_current_mode\fP (void)"
.br
.ti -1c
.RI "void \fBpmm_set_low_current_mode\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBclose_radio\fP (void)"
.PP
Definition at line 146 of file radio\&.c\&.
.SS "void \fBopen_radio\fP (void)"
.PP
Definition at line 127 of file radio\&.c\&.
.SS "void \fBpmm_set_high_current_mode\fP (void)"
.SS "void \fBpmm_set_low_current_mode\fP (void)"
.SS "void \fBradio_idle\fP (void)"
.SS "void \fBradio_powerdown\fP (void)"
.PP
Definition at line 90 of file radio\&.c\&.
.SS "void \fBradio_reset\fP (void)"
.PP
Definition at line 66 of file radio\&.c\&.
.SS "void \fBradio_sxoff\fP (void)"
.PP
Definition at line 109 of file radio\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
