.TH "Original Code/V2.2/logic/random.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/logic/random.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'ports\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'buzzer\&.h'\fP
.br
\fC#include 'user\&.h'\fP
.br
\fC#include 'menu\&.h'\fP
.br
\fC#include 'random\&.h'\fP
.br
\fC#include 'clock\&.h'\fP
.br
\fC#include 'date\&.h'\fP
.br
\fC#include 'altitude\&.h'\fP
.br
\fC#include 'display2\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBRANDOM_MAX\fP   9999"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstart_random\fP (void)"
.br
.ti -1c
.RI "void \fBstop_random\fP (void)"
.br
.ti -1c
.RI "void \fBreset_random\fP (void)"
.br
.ti -1c
.RI "void \fBrandom_tick\fP (void)"
.br
.ti -1c
.RI "void \fBmx_random\fP (u8 line)"
.br
.ti -1c
.RI "void \fBsx_random\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_random\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBset_random\fP (void)"
.br
.ti -1c
.RI "void \fBdisplay_special\fP (u8 segments, u32 value, u8 digits, u8 blanks)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBrandom\fP \fBsrandom\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBRANDOM_MAX\fP   9999"
.PP
Definition at line 74 of file random\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void \fBdisplay_random\fP (u8line, u8update)"
.PP
Definition at line 254 of file random\&.c\&.
.SS "void \fBdisplay_special\fP (u8segments, u32value, u8digits, u8blanks)"
.PP
Definition at line 239 of file random\&.c\&.
.SS "void \fBmx_random\fP (u8line)"
.PP
Definition at line 183 of file random\&.c\&.
.SS "void \fBrandom_tick\fP (void)"
.PP
Definition at line 91 of file random\&.c\&.
.SS "void \fBreset_random\fP (void)"
.PP
Definition at line 128 of file random\&.c\&.
.SS "void \fBset_random\fP (void)"
.PP
Definition at line 286 of file random\&.c\&.
.SS "void \fBstart_random\fP (void)"
.PP
Definition at line 154 of file random\&.c\&.
.SS "void \fBstop_random\fP (void)"
.PP
Definition at line 169 of file random\&.c\&.
.SS "void \fBsx_random\fP (u8line)"
.PP
Definition at line 206 of file random\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBrandom\fP \fBsrandom\fP"
.PP
Definition at line 79 of file random\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
