.TH "random" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
random \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'random\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBstate\fP"
.br
.ti -1c
.RI "u8 \fBmode\fP"
.br
.ti -1c
.RI "u8 \fBStyle\fP"
.br
.ti -1c
.RI "u8 \fBDigit\fP [5]"
.br
.ti -1c
.RI "\fBu16\fP \fBRandomNumber\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBRandomMin\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBRandomMax\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 72 of file random\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u8 \fBDigit\fP[5]"
.PP
Definition at line 77 of file random\&.h\&.
.SS "u8 \fBmode\fP"
.PP
Definition at line 75 of file random\&.h\&.
.SS "\fBu16\fP \fBRandomMax\fP"
.PP
Definition at line 80 of file random\&.h\&.
.SS "\fBu16\fP \fBRandomMin\fP"
.PP
Definition at line 79 of file random\&.h\&.
.SS "\fBu16\fP \fBRandomNumber\fP"
.PP
Definition at line 78 of file random\&.h\&.
.SS "u8 \fBstate\fP"
.PP
Definition at line 74 of file random\&.h\&.
.SS "u8 \fBStyle\fP"
.PP
Definition at line 76 of file random\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
