.TH "s_button_flags" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_button_flags \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'ports\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBu16\fP \fBstar\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBnum\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBup\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBdown\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBbacklight\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBstar_long\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBnum_long\fP: 1"
.br
.ti -1c
.RI "} \fBflag\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBall_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 89 of file ports\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBu16\fP \fBall_flags\fP"
.PP
Definition at line 102 of file ports\&.h\&.
.SS "\fBu16\fP \fBbacklight\fP"
.PP
Definition at line 98 of file ports\&.h\&.
.SS "\fBu16\fP \fBdown\fP"
.PP
Definition at line 97 of file ports\&.h\&.
.SS "struct { \&.\&.\&. }   \fBflag\fP"
.SS "\fBu16\fP \fBnum\fP"
.PP
Definition at line 95 of file ports\&.h\&.
.SS "\fBu16\fP \fBnum_long\fP"
.PP
Definition at line 100 of file ports\&.h\&.
.SS "\fBu16\fP \fBstar\fP"
.PP
Definition at line 94 of file ports\&.h\&.
.SS "\fBu16\fP \fBstar_long\fP"
.PP
Definition at line 99 of file ports\&.h\&.
.SS "\fBu16\fP \fBup\fP"
.PP
Definition at line 96 of file ports\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
