.TH "simpliciti/simpliciti.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpliciti/simpliciti.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSIMPLICITI_MAX_PAYLOAD_LENGTH\fP   (32u)"
.br
.ti -1c
.RI "#define \fBSIMPLICITI_STATUS_LINKING\fP   (BIT0)"
.br
.ti -1c
.RI "#define \fBSIMPLICITI_STATUS_LINKED\fP   (BIT1)"
.br
.ti -1c
.RI "#define \fBSIMPLICITI_STATUS_ERROR\fP   (BIT2)"
.br
.ti -1c
.RI "#define \fBSIMPLICITI_TRIGGER_SEND_DATA\fP   (BIT3)"
.br
.ti -1c
.RI "#define \fBSIMPLICITI_TRIGGER_RECEIVED_DATA\fP   (BIT4)"
.br
.ti -1c
.RI "#define \fBSIMPLICITI_TRIGGER_STOP\fP   (BIT5)"
.br
.ti -1c
.RI "#define \fBgetFlag\fP(val, flag)   ((val&flag)==flag)"
.br
.ti -1c
.RI "#define \fBsetFlag\fP(val, flag)   (val|=flag)"
.br
.ti -1c
.RI "#define \fBclearFlag\fP(val, flag)   (val&=(~flag))"
.br
.ti -1c
.RI "#define \fBtoggleFlag\fP(val, flag)   (val^=flag)"
.br
.ti -1c
.RI "#define \fBBM_SYNC_DATA_LENGTH\fP   (19u)"
.br
.ti -1c
.RI "#define \fBSYNC_ED_TYPE_R2R\fP   (1u)"
.br
.ti -1c
.RI "#define \fBSYNC_ED_TYPE_MEMORY\fP   (2u)"
.br
.ti -1c
.RI "#define \fBSYNC_ED_TYPE_STATUS\fP   (3u)"
.br
.ti -1c
.RI "#define \fBSYNC_AP_CMD_NOP\fP   (1u)"
.br
.ti -1c
.RI "#define \fBSYNC_AP_CMD_GET_STATUS\fP   (2u)"
.br
.ti -1c
.RI "#define \fBSYNC_AP_CMD_SET_WATCH\fP   (3u)"
.br
.ti -1c
.RI "#define \fBSYNC_AP_CMD_GET_MEMORY_BLOCKS_MODE_1\fP   (4u)"
.br
.ti -1c
.RI "#define \fBSYNC_AP_CMD_GET_MEMORY_BLOCKS_MODE_2\fP   (5u)"
.br
.ti -1c
.RI "#define \fBSYNC_AP_CMD_ERASE_MEMORY\fP   (6u)"
.br
.ti -1c
.RI "#define \fBSYNC_AP_CMD_EXIT\fP   (7u)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned char \fBsimpliciti_link\fP (void)"
.br
.ti -1c
.RI "void \fBsimpliciti_main_tx_only\fP (void)"
.br
.ti -1c
.RI "void \fBsimpliciti_get_ed_data_callback\fP (void)"
.br
.ti -1c
.RI "void \fBsimpliciti_main_sync\fP (void)"
.br
.ti -1c
.RI "void \fBsimpliciti_sync_decode_ap_cmd_callback\fP (void)"
.br
.ti -1c
.RI "void \fBsimpliciti_sync_get_data_callback\fP (unsigned int index)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned char \fBsimpliciti_ed_address\fP [4]"
.br
.ti -1c
.RI "unsigned char \fBsimpliciti_data\fP [(32u)]"
.br
.ti -1c
.RI "unsigned char \fBsimpliciti_flag\fP"
.br
.ti -1c
.RI "unsigned char \fBrf_frequoffset\fP"
.br
.ti -1c
.RI "unsigned char \fBsimpliciti_reply_count\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBBM_SYNC_DATA_LENGTH\fP   (19u)"
.PP
Definition at line 135 of file simpliciti\&.h\&.
.SS "#define \fBclearFlag\fP(val, flag)   (val&=(~flag))"
.PP
Definition at line 117 of file simpliciti\&.h\&.
.SS "#define \fBgetFlag\fP(val, flag)   ((val&flag)==flag)"
.PP
Definition at line 115 of file simpliciti\&.h\&.
.SS "#define \fBsetFlag\fP(val, flag)   (val|=flag)"
.PP
Definition at line 116 of file simpliciti\&.h\&.
.SS "#define \fBSIMPLICITI_MAX_PAYLOAD_LENGTH\fP   (32u)"
.PP
Definition at line 95 of file simpliciti\&.h\&.
.SS "#define \fBSIMPLICITI_STATUS_ERROR\fP   (BIT2)"
.PP
Definition at line 105 of file simpliciti\&.h\&.
.SS "#define \fBSIMPLICITI_STATUS_LINKED\fP   (BIT1)"
.PP
Definition at line 104 of file simpliciti\&.h\&.
.SS "#define \fBSIMPLICITI_STATUS_LINKING\fP   (BIT0)"
.PP
Definition at line 103 of file simpliciti\&.h\&.
.SS "#define \fBSIMPLICITI_TRIGGER_RECEIVED_DATA\fP   (BIT4)"
.PP
Definition at line 107 of file simpliciti\&.h\&.
.SS "#define \fBSIMPLICITI_TRIGGER_SEND_DATA\fP   (BIT3)"
.PP
Definition at line 106 of file simpliciti\&.h\&.
.SS "#define \fBSIMPLICITI_TRIGGER_STOP\fP   (BIT5)"
.PP
Definition at line 108 of file simpliciti\&.h\&.
.SS "#define \fBSYNC_AP_CMD_ERASE_MEMORY\fP   (6u)"
.PP
Definition at line 148 of file simpliciti\&.h\&.
.SS "#define \fBSYNC_AP_CMD_EXIT\fP   (7u)"
.PP
Definition at line 149 of file simpliciti\&.h\&.
.SS "#define \fBSYNC_AP_CMD_GET_MEMORY_BLOCKS_MODE_1\fP   (4u)"
.PP
Definition at line 146 of file simpliciti\&.h\&.
.SS "#define \fBSYNC_AP_CMD_GET_MEMORY_BLOCKS_MODE_2\fP   (5u)"
.PP
Definition at line 147 of file simpliciti\&.h\&.
.SS "#define \fBSYNC_AP_CMD_GET_STATUS\fP   (2u)"
.PP
Definition at line 144 of file simpliciti\&.h\&.
.SS "#define \fBSYNC_AP_CMD_NOP\fP   (1u)"
.PP
Definition at line 143 of file simpliciti\&.h\&.
.SS "#define \fBSYNC_AP_CMD_SET_WATCH\fP   (3u)"
.PP
Definition at line 145 of file simpliciti\&.h\&.
.SS "#define \fBSYNC_ED_TYPE_MEMORY\fP   (2u)"
.PP
Definition at line 139 of file simpliciti\&.h\&.
.SS "#define \fBSYNC_ED_TYPE_R2R\fP   (1u)"
.PP
Definition at line 138 of file simpliciti\&.h\&.
.SS "#define \fBSYNC_ED_TYPE_STATUS\fP   (3u)"
.PP
Definition at line 140 of file simpliciti\&.h\&.
.SS "#define \fBtoggleFlag\fP(val, flag)   (val^=flag)"
.PP
Definition at line 118 of file simpliciti\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBsimpliciti_get_ed_data_callback\fP (void)"
.PP
Definition at line 347 of file rfsimpliciti\&.c\&.
.SS "unsigned char \fBsimpliciti_link\fP (void)"
.PP
Definition at line 75 of file main_ED_BM\&.c\&.
.SS "void \fBsimpliciti_main_sync\fP (void)"
.PP
Definition at line 208 of file main_ED_BM\&.c\&.
.SS "void \fBsimpliciti_main_tx_only\fP (void)"
.PP
Definition at line 167 of file main_ED_BM\&.c\&.
.SS "void \fBsimpliciti_sync_decode_ap_cmd_callback\fP (void)"
.PP
Definition at line 500 of file rfsimpliciti\&.c\&.
.SS "void \fBsimpliciti_sync_get_data_callback\fP (unsigned intindex)"
.PP
Definition at line 581 of file rfsimpliciti\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "unsigned char \fBrf_frequoffset\fP"
.PP
Definition at line 110 of file main\&.c\&.
.SS "unsigned char \fBsimpliciti_data\fP[(32u)]"
.PP
Definition at line 87 of file rfsimpliciti\&.c\&.
.SS "unsigned char \fBsimpliciti_ed_address\fP[4]"
.PP
Definition at line 90 of file rfsimpliciti\&.c\&.
.SS "unsigned char \fBsimpliciti_flag\fP"
.PP
Definition at line 84 of file rfsimpliciti\&.c\&.
.SS "unsigned char \fBsimpliciti_reply_count\fP"
.PP
Definition at line 97 of file rfsimpliciti\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
