.TH "simpliciti/Components/mrfi/smartrf/CC1101/smartrf_CC1101.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpliciti/Components/mrfi/smartrf/CC1101/smartrf_CC1101.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSMARTRF_RADIO_CC1101\fP"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FSCTRL1\fP   0x08"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FSCTRL0\fP   0x00"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_MDMCFG4\fP   0x7B"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_MDMCFG3\fP   0x83"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_MDMCFG2\fP   0x13"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_MDMCFG1\fP   0x22"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_MDMCFG0\fP   0xF8"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_CHANNR\fP   0x00"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_DEVIATN\fP   0x42"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FREND1\fP   0xB6"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FREND0\fP   0x10"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_MCSM0\fP   0x18"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FOCCFG\fP   0x1D"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_BSCFG\fP   0x1C"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_AGCCTRL2\fP   0xC7"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_AGCCTRL1\fP   0x00"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_AGCCTRL0\fP   0xB2"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FSCAL3\fP   0xEA"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FSCAL2\fP   0x2A"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FSCAL1\fP   0x00"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FSCAL0\fP   0x1F"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FSTEST\fP   0x59"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_TEST2\fP   0x81"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_TEST1\fP   0x35"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_TEST0\fP   0x09"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FIFOTHR\fP   0x47"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_IOCFG2\fP   0x29"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_IOCFG0D\fP   0x06"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_PKTCTRL1\fP   0x04"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_PKTCTRL0\fP   0x05"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_ADDR\fP   0x00"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_PKTLEN\fP   0xFF"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBSMARTRF_RADIO_CC1101\fP"
.PP
Definition at line 74 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_ADDR\fP   0x00"
.PP
Definition at line 127 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_AGCCTRL0\fP   0xB2"
.PP
Definition at line 113 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_AGCCTRL1\fP   0x00"
.PP
Definition at line 112 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_AGCCTRL2\fP   0xC7"
.PP
Definition at line 111 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_BSCFG\fP   0x1C"
.PP
Definition at line 110 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_CHANNR\fP   0x00"
.PP
Definition at line 104 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_DEVIATN\fP   0x42"
.PP
Definition at line 105 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FIFOTHR\fP   0x47"
.PP
Definition at line 122 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FOCCFG\fP   0x1D"
.PP
Definition at line 109 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FREND0\fP   0x10"
.PP
Definition at line 107 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FREND1\fP   0xB6"
.PP
Definition at line 106 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FSCAL0\fP   0x1F"
.PP
Definition at line 117 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FSCAL1\fP   0x00"
.PP
Definition at line 116 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FSCAL2\fP   0x2A"
.PP
Definition at line 115 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FSCAL3\fP   0xEA"
.PP
Definition at line 114 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FSCTRL0\fP   0x00"
.PP
Definition at line 77 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FSCTRL1\fP   0x08"
.PP
Definition at line 76 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FSTEST\fP   0x59"
.PP
Definition at line 118 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_IOCFG0D\fP   0x06"
.PP
Definition at line 124 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_IOCFG2\fP   0x29"
.PP
Definition at line 123 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_MCSM0\fP   0x18"
.PP
Definition at line 108 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_MDMCFG0\fP   0xF8"
.PP
Definition at line 103 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_MDMCFG1\fP   0x22"
.PP
Definition at line 102 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_MDMCFG2\fP   0x13"
.PP
Definition at line 101 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_MDMCFG3\fP   0x83"
.PP
Definition at line 100 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_MDMCFG4\fP   0x7B"
.PP
Definition at line 99 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_PKTCTRL0\fP   0x05"
.PP
Definition at line 126 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_PKTCTRL1\fP   0x04"
.PP
Definition at line 125 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_PKTLEN\fP   0xFF"
.PP
Definition at line 128 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_TEST0\fP   0x09"
.PP
Definition at line 121 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_TEST1\fP   0x35"
.PP
Definition at line 120 of file smartrf_CC1101\&.h\&.
.SS "#define \fBSMARTRF_SETTING_TEST2\fP   0x81"
.PP
Definition at line 119 of file smartrf_CC1101\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
