.TH "logic/stopwatch.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/stopwatch.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'stopwatch\&.h'\fP
.br
\fC#include 'ports\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'user\&.h'\fP
.br
\fC#include 'menu\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMODE_STOPTIMER\fP   0"
.br
.ti -1c
.RI "#define \fBMODE_LAPTIMER\fP   1"
.br
.ti -1c
.RI "#define \fBLAP_RUNNING\fP   0"
.br
.ti -1c
.RI "#define \fBLAP_CATCHED\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstart_stopwatch\fP (void)"
.br
.ti -1c
.RI "void \fBstop_stopwatch\fP (void)"
.br
.ti -1c
.RI "void \fBreset_stopwatch\fP (void)"
.br
.ti -1c
.RI "void \fBstopwatch_tick\fP (void)"
.br
.ti -1c
.RI "void \fBupdate_stopwatch_timer\fP (void)"
.br
.ti -1c
.RI "void \fBmx_stopwatch\fP (u8 line)"
.br
.ti -1c
.RI "void \fBsx_stopwatch\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_stopwatch\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBset_stopwatchmode\fP (void)"
.br
.ti -1c
.RI "void \fBinit_stopwatch\fP (void)"
.br
.ti -1c
.RI "u8 \fBis_stopwatch\fP (void)"
.br
.ti -1c
.RI "void \fBdisplay_special3\fP (u8 segments, u32 value, u8 digits, u8 blanks)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBstopwatch\fP \fBsStopwatch\fP"
.br
.ti -1c
.RI "u8 \fBStopwatchMode\fP"
.br
.ti -1c
.RI "u8 \fBLAP_Time\fP [8]"
.br
.ti -1c
.RI "u8 \fBLAP_TimeFlag\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBLAP_CATCHED\fP   1"
.PP
Definition at line 75 of file stopwatch\&.c\&.
.SS "#define \fBLAP_RUNNING\fP   0"
.PP
Definition at line 74 of file stopwatch\&.c\&.
.SS "#define \fBMODE_LAPTIMER\fP   1"
.PP
Definition at line 73 of file stopwatch\&.c\&.
.SS "#define \fBMODE_STOPTIMER\fP   0"
.PP
Definition at line 72 of file stopwatch\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void \fBdisplay_special3\fP (u8segments, u32value, u8digits, u8blanks)"
.PP
Definition at line 531 of file stopwatch\&.c\&.
.SS "void \fBdisplay_stopwatch\fP (u8line, u8update)"
.PP
Definition at line 428 of file stopwatch\&.c\&.
.SS "void \fBinit_stopwatch\fP (void)"
.PP
Definition at line 96 of file stopwatch\&.c\&.
.SS "u8 \fBis_stopwatch\fP (void)"
.PP
Definition at line 300 of file stopwatch\&.c\&.
.SS "void \fBmx_stopwatch\fP (u8line)"
.PP
Definition at line 378 of file stopwatch\&.c\&.
.SS "void \fBreset_stopwatch\fP (void)"
.PP
Definition at line 120 of file stopwatch\&.c\&.
.SS "void \fBset_stopwatchmode\fP (void)"
.PP
Definition at line 543 of file stopwatch\&.c\&.
.SS "void \fBstart_stopwatch\fP (void)"
.PP
Definition at line 312 of file stopwatch\&.c\&.
.SS "void \fBstop_stopwatch\fP (void)"
.PP
Definition at line 341 of file stopwatch\&.c\&.
.SS "void \fBstopwatch_tick\fP (void)"
.PP
Definition at line 181 of file stopwatch\&.c\&.
.SS "void \fBsx_stopwatch\fP (u8line)"
.PP
Definition at line 401 of file stopwatch\&.c\&.
.SS "void \fBupdate_stopwatch_timer\fP (void)"
.PP
Definition at line 134 of file stopwatch\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "u8 \fBLAP_Time\fP[8]"
.PP
Definition at line 81 of file stopwatch\&.c\&.
.SS "u8 \fBLAP_TimeFlag\fP"
.PP
Definition at line 82 of file stopwatch\&.c\&.
.SS "struct \fBstopwatch\fP \fBsStopwatch\fP"
.PP
Definition at line 79 of file stopwatch\&.c\&.
.SS "u8 \fBStopwatchMode\fP"
.PP
Definition at line 80 of file stopwatch\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
