.TH "Original Code/V2.2/logic/stopwatch.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/logic/stopwatch.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <project\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBstopwatch\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSTOPWATCH_1HZ_TICK\fP   (32768/1)"
.br
.ti -1c
.RI "#define \fBSTOPWATCH_100HZ_TICK\fP   (32768/100)"
.br
.ti -1c
.RI "#define \fBSTOPWATCH_STOP\fP   (0u)"
.br
.ti -1c
.RI "#define \fBSTOPWATCH_RUN\fP   (1u)"
.br
.ti -1c
.RI "#define \fBSTOPWATCH_HIDE\fP   (2u)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstart_stopwatch\fP (void)"
.br
.ti -1c
.RI "void \fBstop_stopwatch\fP (void)"
.br
.ti -1c
.RI "void \fBreset_stopwatch\fP (void)"
.br
.ti -1c
.RI "u8 \fBis_stopwatch\fP (void)"
.br
.ti -1c
.RI "void \fBstopwatch_tick\fP (void)"
.br
.ti -1c
.RI "void \fBupdate_stopwatch_timer\fP (void)"
.br
.ti -1c
.RI "void \fBmx_stopwatch\fP (u8 line)"
.br
.ti -1c
.RI "void \fBsx_stopwatch\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_stopwatch\fP (u8 line, u8 update)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBstopwatch\fP \fBsStopwatch\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBSTOPWATCH_100HZ_TICK\fP   (32768/100)"
.PP
Definition at line 60 of file stopwatch\&.h\&.
.SS "#define \fBSTOPWATCH_1HZ_TICK\fP   (32768/1)"
.PP
Definition at line 59 of file stopwatch\&.h\&.
.SS "#define \fBSTOPWATCH_HIDE\fP   (2u)"
.PP
Definition at line 63 of file stopwatch\&.h\&.
.SS "#define \fBSTOPWATCH_RUN\fP   (1u)"
.PP
Definition at line 62 of file stopwatch\&.h\&.
.SS "#define \fBSTOPWATCH_STOP\fP   (0u)"
.PP
Definition at line 61 of file stopwatch\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBdisplay_stopwatch\fP (u8line, u8update)"
.PP
Definition at line 428 of file stopwatch\&.c\&.
.SS "u8 \fBis_stopwatch\fP (void)"
.PP
Definition at line 300 of file stopwatch\&.c\&.
.SS "void \fBmx_stopwatch\fP (u8line)"
.PP
Definition at line 378 of file stopwatch\&.c\&.
.SS "void \fBreset_stopwatch\fP (void)"
.PP
Definition at line 120 of file stopwatch\&.c\&.
.SS "void \fBstart_stopwatch\fP (void)"
.PP
Definition at line 312 of file stopwatch\&.c\&.
.SS "void \fBstop_stopwatch\fP (void)"
.PP
Definition at line 341 of file stopwatch\&.c\&.
.SS "void \fBstopwatch_tick\fP (void)"
.PP
Definition at line 181 of file stopwatch\&.c\&.
.SS "void \fBsx_stopwatch\fP (u8line)"
.PP
Definition at line 401 of file stopwatch\&.c\&.
.SS "void \fBupdate_stopwatch_timer\fP (void)"
.PP
Definition at line 134 of file stopwatch\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBstopwatch\fP \fBsStopwatch\fP"
.PP
Definition at line 79 of file stopwatch\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
