.TH "token_t" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
token_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'nwk_types\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBlinkToken\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBjoinToken\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 154 of file nwk_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint32_t\fP \fBjoinToken\fP"
.PP
Definition at line 157 of file nwk_types\&.h\&.
.SS "\fBuint32_t\fP \fBlinkToken\fP"
.PP
Definition at line 156 of file nwk_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
