.TH "Arduino_ADK_USB_HOST/USB_Implementation Directory Reference" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/USB_Implementation Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBUSB_Functions\&.cpp\fP"
.br
.ti -1c
.RI "file \fBUSB_Functions\&.h\fP"
.br
.ti -1c
.RI "file \fBUSB_Reports\&.h\fP"
.br
.ti -1c
.RI "file \fBusbconfig\&.h\fP"
.br
.in -1c
