.TH "Arduino_ADK_USB_HOST/USB_HID_API Directory Reference" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/USB_HID_API Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBasmcommon\&.inc\fP"
.br
.ti -1c
.RI "file \fBoddebug\&.c\fP"
.br
.ti -1c
.RI "file \fBoddebug\&.h\fP"
.br
.ti -1c
.RI "file \fBusbconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBusbdrv\&.c\fP"
.br
.ti -1c
.RI "file \fBusbdrv\&.h\fP"
.br
.ti -1c
.RI "file \fBusbdrvasm12\&.inc\fP"
.br
.ti -1c
.RI "file \fBusbdrvasm128\&.inc\fP"
.br
.ti -1c
.RI "file \fBusbdrvasm15\&.inc\fP"
.br
.ti -1c
.RI "file \fBusbdrvasm16\&.inc\fP"
.br
.ti -1c
.RI "file \fBusbdrvasm165\&.inc\fP"
.br
.ti -1c
.RI "file \fBusbdrvasm18-crc\&.inc\fP"
.br
.ti -1c
.RI "file \fBusbdrvasm20\&.inc\fP"
.br
.ti -1c
.RI "file \fBusbportability\&.h\fP"
.br
.in -1c
