.TH "Arduino_ADK_USB_HOST Directory Reference" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBDebug_API\fP"
.br
.ti -1c
.RI "directory \fBEmulation_Device_Implementation\fP"
.br
.ti -1c
.RI "directory \fBSensor_Parser_Implementation\fP"
.br
.ti -1c
.RI "directory \fBSystem_Defines\fP"
.br
.ti -1c
.RI "directory \fBUSB_Device_Implementation\fP"
.br
.ti -1c
.RI "directory \fBUSB_HID_API\fP"
.br
.ti -1c
.RI "directory \fBUSB_Implementation\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMain_USB_Host\&.cpp\fP"
.br
.in -1c
