.TH "COMMAND_INTERPRETER" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
COMMAND_INTERPRETER \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Command_Interpreter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCOMMAND_INTERPRETER\fP (\fBNVRAM\fP *nvram_object)"
.br
.RI "\fISets up our non volatile nvram object, our command db\&. \fP"
.ti -1c
.RI "void \fBsend_cmd\fP (byte packet_id, void *buf)"
.br
.RI "\fIThe public send command method\&. \fP"
.ti -1c
.RI "void \fBload\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class handles commands sent from the sensor nodes to the base station, and executes them\&. We can also send commands through this class\&. 
.PP
Definition at line 38 of file Command_Interpreter\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "COMMAND_INTERPRETER::COMMAND_INTERPRETER (\fBNVRAM\fP *nvram_object)"

.PP
Sets up our non volatile nvram object, our command db\&. Default constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fInvram_object\fP 
.RE
.PP

.PP
Definition at line 12 of file Command_Interpreter\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void COMMAND_INTERPRETER::load (void)"
Load all of the saved variables\&. 
.SS "void COMMAND_INTERPRETER::send_cmd (bytepacket_id, void *buf)"

.PP
The public send command method\&. Sends a command via the public domain\&.
.PP
\fBParameters:\fP
.RS 4
\fIbuf\fP - void* 
.RE
.PP
Process String 
.PP
Definition at line 160 of file Command_Interpreter\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
