.TH "Arduino_ADK_USB_HOST/System_Defines/Command_Interpreter.h" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/System_Defines/Command_Interpreter.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./System_Defines/Includes\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCOMMAND_INTERPRETER\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWAKEUP_ROUTER\fP   0x01"
.br
.ti -1c
.RI "#define \fBWAKEUP_SENSOR\fP   0x02"
.br
.ti -1c
.RI "#define \fBPOWEROFF_ROUTER\fP   0x03"
.br
.ti -1c
.RI "#define \fBPOWEROFF_SENSOR\fP   0x04"
.br
.ti -1c
.RI "#define \fBPOWERON_ROUTER\fP   0x05"
.br
.ti -1c
.RI "#define \fBPOWERON_SENSOR\fP   0x06"
.br
.ti -1c
.RI "#define \fBPAUSE_ROUTER\fP   0x07"
.br
.ti -1c
.RI "#define \fBPAUSE_SENSOR\fP   0x08"
.br
.ti -1c
.RI "#define \fBREQUEST_ROUTER_STATUS\fP   0x09"
.br
.ti -1c
.RI "#define \fBREQUEST_NMAP\fP   0x0A"
.br
.ti -1c
.RI "#define \fBREQUEST_SENSOR_CHANNEL\fP   0x0B"
.br
.ti -1c
.RI "#define \fBREQUEST_SENSOR_ENABLE\fP   0x0C"
.br
.ti -1c
.RI "#define \fBREQUEST_SENSOR_CONFIG\fP   0X0D"
.br
.ti -1c
.RI "#define \fBREQUEST_ROUTER_RUN\fP   0x0F"
.br
.ti -1c
.RI "#define \fBPING_ROUTER\fP   0x10"
.br
.ti -1c
.RI "#define \fBPING_SENSOR\fP   0x11"
.br
.ti -1c
.RI "#define \fBREQUEST_ROUTER_CONFIG\fP   0x12"
.br
.ti -1c
.RI "#define \fBREQUEST_NUMBER_SENSORS\fP   0x13"
.br
.ti -1c
.RI "#define \fBREQUEST_NUMBER_CHANNELS\fP   0x14"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PAUSE_ROUTER   0x07"

.PP
Definition at line 19 of file Command_Interpreter\&.h\&.
.SS "#define PAUSE_SENSOR   0x08"

.PP
Definition at line 20 of file Command_Interpreter\&.h\&.
.SS "#define PING_ROUTER   0x10"

.PP
Definition at line 27 of file Command_Interpreter\&.h\&.
.SS "#define PING_SENSOR   0x11"

.PP
Definition at line 28 of file Command_Interpreter\&.h\&.
.SS "#define POWEROFF_ROUTER   0x03"

.PP
Definition at line 15 of file Command_Interpreter\&.h\&.
.SS "#define POWEROFF_SENSOR   0x04"

.PP
Definition at line 16 of file Command_Interpreter\&.h\&.
.SS "#define POWERON_ROUTER   0x05"

.PP
Definition at line 17 of file Command_Interpreter\&.h\&.
.SS "#define POWERON_SENSOR   0x06"

.PP
Definition at line 18 of file Command_Interpreter\&.h\&.
.SS "#define REQUEST_NMAP   0x0A"

.PP
Definition at line 22 of file Command_Interpreter\&.h\&.
.SS "#define REQUEST_NUMBER_CHANNELS   0x14"

.PP
Definition at line 31 of file Command_Interpreter\&.h\&.
.SS "#define REQUEST_NUMBER_SENSORS   0x13"

.PP
Definition at line 30 of file Command_Interpreter\&.h\&.
.SS "#define REQUEST_ROUTER_CONFIG   0x12"

.PP
Definition at line 29 of file Command_Interpreter\&.h\&.
.SS "#define REQUEST_ROUTER_RUN   0x0F"

.PP
Definition at line 26 of file Command_Interpreter\&.h\&.
.SS "#define REQUEST_ROUTER_STATUS   0x09"

.PP
Definition at line 21 of file Command_Interpreter\&.h\&.
.SS "#define REQUEST_SENSOR_CHANNEL   0x0B"

.PP
Definition at line 23 of file Command_Interpreter\&.h\&.
.SS "#define REQUEST_SENSOR_CONFIG   0X0D"

.PP
Definition at line 25 of file Command_Interpreter\&.h\&.
.SS "#define REQUEST_SENSOR_ENABLE   0x0C"

.PP
Definition at line 24 of file Command_Interpreter\&.h\&.
.SS "#define WAKEUP_ROUTER   0x01"

.PP
Definition at line 13 of file Command_Interpreter\&.h\&.
.SS "#define WAKEUP_SENSOR   0x02"

.PP
Definition at line 14 of file Command_Interpreter\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
