.TH "DEBUG_CODES_STRUCT" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DEBUG_CODES_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Debug_LED_Function\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "byte \fBERROR_INDEX\fP"
.br
.RI "\fIThe index to the arrays\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This structure holds all the definitions for states and strings associated debug messages\&. 
.PP
Definition at line 72 of file Debug_LED_Function\&.h\&.
.SH "Field Documentation"
.PP 
.SS "byte DEBUG_CODES_STRUCT::ERROR_INDEX"

.PP
The index to the arrays\&. 
.PP
Definition at line 75 of file Debug_LED_Function\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
