.TH "DEBUG_API" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DEBUG_API \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Debug_LED_Function\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDEBUG_API\fP ()"
.br
.RI "\fIInitialize the object\&. \fP"
.ti -1c
.RI "void \fBprint_error\fP (byte error_index, String *string)"
.br
.RI "\fIThe public access to the print error method\&. \fP"
.ti -1c
.RI "void \fBenable_debug\fP ()"
.br
.RI "\fIEnables the api\&. \fP"
.ti -1c
.RI "void \fBdisable_debug\fP ()"
.br
.ti -1c
.RI "byte \fBget_number_of\fP (String debug_type)"
.br
.RI "\fIGet the number of errors\&. \fP"
.ti -1c
.RI "void \fBtest_leds\fP ()"
.br
.RI "\fIThis tests the leds\&. \fP"
.ti -1c
.RI "void \fBset_leds\fP (byte error_index)"
.br
.RI "\fIThis sets LEDS\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class is implemented to handle debug commands and states to then output the LED states and show a debug code\&. 
.PP
Definition at line 99 of file Debug_LED_Function\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "void DEBUG_API::DEBUG_API ()"

.PP
Initialize the object\&. The default constructor 
.PP
Definition at line 12 of file Debug_LED_Function\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void DEBUG_API::disable_debug ()"
This disables the api\&. 
.PP
Definition at line 90 of file Debug_LED_Function\&.cpp\&.
.SS "void DEBUG_API::enable_debug ()"

.PP
Enables the api\&. This enables the api\&. 
.PP
Definition at line 85 of file Debug_LED_Function\&.cpp\&.
.SS "byte DEBUG_API::get_number_of (Stringdebug_type)"

.PP
Get the number of errors\&. This gets the number of specified errors\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdebug_type\fP - String 
.RE
.PP
\fBReturns:\fP
.RS 4
byte - number 
.RE
.PP

.PP
Definition at line 95 of file Debug_LED_Function\&.cpp\&.
.SS "void DEBUG_API::print_error (byteerror_index, String *string)"

.PP
The public access to the print error method\&. The print error externally from the api\&. 
.PP
\fBParameters:\fP
.RS 4
\fIerror_index\fP - byte 
.br
\fIstring\fP - String 
.RE
.PP

.PP
Definition at line 46 of file Debug_LED_Function\&.cpp\&.
.SS "void DEBUG_API::set_leds (byteerror_index)"

.PP
This sets LEDS\&. Sets the leds based on the error_message index passed\&. 
.PP
\fBParameters:\fP
.RS 4
\fIerror_index\fP - byte 
.RE
.PP

.PP
Definition at line 113 of file Debug_LED_Function\&.cpp\&.
.SS "void DEBUG_API::test_leds ()"

.PP
This tests the leds\&. Tests the leds\&. Only happens if there are defined\&. turn them on\&.\&.\&.
.PP
delay
.PP
Turn them off 
.PP
Definition at line 125 of file Debug_LED_Function\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
