.TH "Arduino_ADK_USB_HOST/Debug_API/Debug_LED_Function.h" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/Debug_API/Debug_LED_Function.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBDEBUG_CODES_STRUCT\fP"
.br
.ti -1c
.RI "struct \fBERROR_TYPE_COUNTS\fP"
.br
.RI "\fIDefining a type\&. \fP"
.ti -1c
.RI "class \fBDEBUG_API\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFATAL\fP   1"
.br
.RI "\fIDebug indexes\&. \fP"
.ti -1c
.RI "#define \fBWARNING\fP   2"
.br
.ti -1c
.RI "#define \fBINFO\fP   3"
.br
.ti -1c
.RI "#define \fBDEBUG_LED\fP   4"
.br
.ti -1c
.RI "#define \fBMEMORY\fP   5"
.br
.ti -1c
.RI "#define \fBREBOOT\fP   7"
.br
.ti -1c
.RI "#define \fBDEBUG_ERROR\fP   6"
.br
.ti -1c
.RI "#define \fBSTATE_CHANGE\fP   8"
.br
.ti -1c
.RI "#define \fBFATAL_ERROR\fP   0"
.br
.RI "\fILED error codes\&. \fP"
.ti -1c
.RI "#define \fBCLEAR_ERRORS\fP   1"
.br
.ti -1c
.RI "#define \fBWARNING_ERROR\fP   2"
.br
.ti -1c
.RI "#define \fBINFO_ERROR\fP   3"
.br
.ti -1c
.RI "#define \fBDEBUG_INFO\fP   4"
.br
.ti -1c
.RI "#define \fBMEMORY_ERROR\fP   5"
.br
.ti -1c
.RI "#define \fBREBOOT_ERROR\fP   7"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBDEBUG_CODES_STRUCT\fP \fBdebug_code_struct_t\fP"
.br
.ti -1c
.RI "typedef struct \fBERROR_TYPE_COUNTS\fP \fBerror_type_counts_t\fP"
.br
.RI "\fIDefining a type\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const String \fBDEBUG_STRINGS\fP [9]"
.br
.RI "\fIThe Strings needed\&. \fP"
.ti -1c
.RI "const byte \fBDEBUG_CODES\fP [9]"
.br
.RI "\fIThe debug codes\&. \fP"
.ti -1c
.RI "const byte \fBDEBUG_LED_CODES\fP [9]"
.br
.RI "\fIThe LED codes\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CLEAR_ERRORS   1"

.PP
Definition at line 20 of file Debug_LED_Function\&.h\&.
.SS "#define DEBUG_ERROR   6"

.PP
Definition at line 15 of file Debug_LED_Function\&.h\&.
.SS "#define DEBUG_INFO   4"

.PP
Definition at line 23 of file Debug_LED_Function\&.h\&.
.SS "#define DEBUG_LED   4"

.PP
Definition at line 12 of file Debug_LED_Function\&.h\&.
.SS "#define FATAL   1"

.PP
Debug indexes\&. 
.PP
Definition at line 9 of file Debug_LED_Function\&.h\&.
.SS "#define FATAL_ERROR   0"

.PP
LED error codes\&. 
.PP
Definition at line 19 of file Debug_LED_Function\&.h\&.
.SS "#define INFO   3"

.PP
Definition at line 11 of file Debug_LED_Function\&.h\&.
.SS "#define INFO_ERROR   3"

.PP
Definition at line 22 of file Debug_LED_Function\&.h\&.
.SS "#define MEMORY   5"

.PP
Definition at line 13 of file Debug_LED_Function\&.h\&.
.SS "#define MEMORY_ERROR   5"

.PP
Definition at line 24 of file Debug_LED_Function\&.h\&.
.SS "#define REBOOT   7"

.PP
Definition at line 14 of file Debug_LED_Function\&.h\&.
.SS "#define REBOOT_ERROR   7"

.PP
Definition at line 25 of file Debug_LED_Function\&.h\&.
.SS "#define STATE_CHANGE   8"

.PP
Definition at line 16 of file Debug_LED_Function\&.h\&.
.SS "#define WARNING   2"

.PP
Definition at line 10 of file Debug_LED_Function\&.h\&.
.SS "#define WARNING_ERROR   2"

.PP
Definition at line 21 of file Debug_LED_Function\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBDEBUG_CODES_STRUCT\fP \fBdebug_code_struct_t\fP"
This structure holds all the definitions for states and strings associated debug messages\&. 
.SS "typedef struct \fBERROR_TYPE_COUNTS\fP \fBerror_type_counts_t\fP"

.PP
Defining a type\&. This is a structure that holds the total errors for each class of errors\&. 
.SH "Variable Documentation"
.PP 
.SS "const byte DEBUG_CODES[9]"
\fBInitial value:\fP
.PP
.nf
= {

                0b0000001,  
                0b0000010,  
                0b0000100,  
                0b0001000,  
                0b0010000,  
                0b0100000,  
                0b1000000,  
                0b1111111,  
                0b0000000   
        }
.fi
.PP
The debug codes\&. 
.PP
Definition at line 42 of file Debug_LED_Function\&.h\&.
.SS "const byte DEBUG_LED_CODES[9]"
\fBInitial value:\fP
.PP
.nf
= {

                0b0001,     
                0b0000,     
                0b0010,     
                0b0100,     
                0b1000,     
                0b0011,     
                0b0101,     
                0b1111      
        }
.fi
.PP
The LED codes\&. 
.PP
Definition at line 56 of file Debug_LED_Function\&.h\&.
.SS "const String DEBUG_STRINGS[9]"
\fBInitial value:\fP
.PP
.nf
= {

                "FATAL  ",
                "WARNING",
                "INFO   ",
                "DEBUG  ",
                "MEMORY ",
                "REBOOT ",
                "DEBUG E",
                "STATE  "
        }
.fi
.PP
The Strings needed\&. 
.PP
Definition at line 29 of file Debug_LED_Function\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
