.TH "error_message_t" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
error_message_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Network_Protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "byte \fBsensor_id\fP"
.br
.ti -1c
.RI "byte \fBsensor_address\fP"
.br
.ti -1c
.RI "byte \fBerror_code\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 121 of file Network_Protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "byte error_message_t::error_code"

.PP
Definition at line 125 of file Network_Protocol\&.h\&.
.SS "byte error_message_t::sensor_address"

.PP
Definition at line 124 of file Network_Protocol\&.h\&.
.SS "byte error_message_t::sensor_id"

.PP
Definition at line 123 of file Network_Protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
