.TH "ERROR_TYPE_COUNTS" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ERROR_TYPE_COUNTS \- 
.PP
Defining a type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Debug_LED_Function\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "byte \fBwarnings_errors\fP"
.br
.RI "\fIThe counts for each errors\&. \fP"
.ti -1c
.RI "byte \fBinfo_errors\fP"
.br
.ti -1c
.RI "byte \fBdebug_errors\fP"
.br
.ti -1c
.RI "byte \fBmemory_errors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defining a type\&. 

This is a structure that holds the total errors for each class of errors\&. 
.PP
Definition at line 83 of file Debug_LED_Function\&.h\&.
.SH "Field Documentation"
.PP 
.SS "byte ERROR_TYPE_COUNTS::debug_errors"

.PP
Definition at line 88 of file Debug_LED_Function\&.h\&.
.SS "byte ERROR_TYPE_COUNTS::info_errors"

.PP
Definition at line 87 of file Debug_LED_Function\&.h\&.
.SS "byte ERROR_TYPE_COUNTS::memory_errors"

.PP
Definition at line 89 of file Debug_LED_Function\&.h\&.
.SS "byte ERROR_TYPE_COUNTS::warnings_errors"

.PP
The counts for each errors\&. 
.PP
Definition at line 86 of file Debug_LED_Function\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
