.TH "Arduino_ADK_USB_HOST/System_Defines/Hardware_Defines.h" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/System_Defines/Hardware_Defines.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMOUSE_REPORT\fP"
.br
.RI "\fIONLY ONE OF THE FOLLOWING SHOULD BE CHOSEN! \fP"
.ti -1c
.RI "#define \fBDEBUG_development\fP"
.br
.ti -1c
.RI "#define \fBUSER_INPUT\fP"
.br
.ti -1c
.RI "#define \fBDEBUG_LEDs\fP"
.br
.ti -1c
.RI "#define \fBNUMBER_OF_LEDS\fP   4"
.br
.ti -1c
.RI "#define \fBSERIAL_OUTPUT\fP   \fBSerial1\fP"
.br
.RI "\fINormal Output Stream\&. \fP"
.ti -1c
.RI "#define \fBPRINT\fP   Serial1\&.print"
.br
.ti -1c
.RI "#define \fBPRINTLN\fP   Serial1\&.println"
.br
.ti -1c
.RI "#define \fBRF_SERIAL\fP   \fBSerial2\fP"
.br
.RI "\fIRF output stream\&. \fP"
.ti -1c
.RI "#define \fBRF_PRINT\fP   Serial2\&.print"
.br
.ti -1c
.RI "#define \fBRF_PRINTLN\fP   Serial2\&.println"
.br
.ti -1c
.RI "#define \fBSELECT_BUTTON_1\fP   2"
.br
.RI "\fIDebug Output Stream\&. \fP"
.ti -1c
.RI "#define \fBSELECT_BUTTON_2\fP   3"
.br
.ti -1c
.RI "#define \fBDBG_LED_1\fP   3"
.br
.ti -1c
.RI "#define \fBDBG_LED_2\fP   4"
.br
.ti -1c
.RI "#define \fBDBG_LED_3\fP   5"
.br
.ti -1c
.RI "#define \fBDBG_LED_4\fP   6"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "HardwareSerial \fBSerial1\fP"
.br
.ti -1c
.RI "HardwareSerial \fBSerial2\fP"
.br
.ti -1c
.RI "HardwareSerial \fBSerial3\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DBG_LED_1   3"
Debug LEDs Activation TODO - ADD THE PORT MAP 
.PP
Definition at line 63 of file Hardware_Defines\&.h\&.
.SS "#define DBG_LED_2   4"

.PP
Definition at line 64 of file Hardware_Defines\&.h\&.
.SS "#define DBG_LED_3   5"

.PP
Definition at line 65 of file Hardware_Defines\&.h\&.
.SS "#define DBG_LED_4   6"

.PP
Definition at line 66 of file Hardware_Defines\&.h\&.
.SS "#define DEBUG_development"

.PP
Definition at line 16 of file Hardware_Defines\&.h\&.
.SS "#define DEBUG_LEDs"

.PP
Definition at line 19 of file Hardware_Defines\&.h\&.
.SS "#define MOUSE_REPORT"

.PP
ONLY ONE OF THE FOLLOWING SHOULD BE CHOSEN! 
.PP
Definition at line 12 of file Hardware_Defines\&.h\&.
.SS "#define NUMBER_OF_LEDS   4"

.PP
Definition at line 21 of file Hardware_Defines\&.h\&.
.SS "#define PRINT   Serial1\&.print"

.PP
Definition at line 36 of file Hardware_Defines\&.h\&.
.SS "#define PRINTLN   Serial1\&.println"

.PP
Definition at line 37 of file Hardware_Defines\&.h\&.
.SS "#define RF_PRINT   Serial2\&.print"

.PP
Definition at line 41 of file Hardware_Defines\&.h\&.
.SS "#define RF_PRINTLN   Serial2\&.println"

.PP
Definition at line 42 of file Hardware_Defines\&.h\&.
.SS "#define RF_SERIAL   \fBSerial2\fP"

.PP
RF output stream\&. 
.PP
Definition at line 40 of file Hardware_Defines\&.h\&.
.SS "#define SELECT_BUTTON_1   2"

.PP
Debug Output Stream\&. User Button Activation TODO - ADD THE PORT MAP 
.PP
Definition at line 55 of file Hardware_Defines\&.h\&.
.SS "#define SELECT_BUTTON_2   3"

.PP
Definition at line 56 of file Hardware_Defines\&.h\&.
.SS "#define SERIAL_OUTPUT   \fBSerial1\fP"

.PP
Normal Output Stream\&. 
.PP
Definition at line 35 of file Hardware_Defines\&.h\&.
.SS "#define USER_INPUT"

.PP
Definition at line 18 of file Hardware_Defines\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "HardwareSerial Serial1"
Serial device map
.IP "\(bu" 2
Serial 1 - USB Endpoint - PC COMS
.IP "\(bu" 2
Serial 2 - USB Host - RF COMS
.IP "\(bu" 2
Serial 3 - Debug - FTDI COMS 
.PP

.SS "HardwareSerial Serial2"

.SS "HardwareSerial Serial3"

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
