.TH "local_command_t" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
local_command_t \- 
.PP
This executes a command on the local system\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Network_Protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "byte \fBcommand_id\fP"
.br
.ti -1c
.RI "byte \fBtarget_address\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This executes a command on the local system\&. 
.PP
Definition at line 177 of file Network_Protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "byte local_command_t::command_id"

.PP
Definition at line 178 of file Network_Protocol\&.h\&.
.SS "byte local_command_t::target_address"

.PP
Definition at line 179 of file Network_Protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
