.TH "Arduino_ADK_USB_HOST/System_Defines/Main_Defines.cpp" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/System_Defines/Main_Defines.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Main_Defines\&.h'\fP
.br
\fC#include 'Debug_API/Debug_LED_Function\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "word \fBmemory_check\fP ()"
.br
.ti -1c
.RI "void \fBerror\fP (void *line, void *function)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "void(* \fBreset_device\fP )(void)=0"
.br
.RI "\fIReset the device\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void error (void *line, void *function)"
This function is accessible throughout the code repo it allows the functions to return and terminate the process as an error\&. Print if defined
.PP
Disconnect the device\&. 
.PP
Definition at line 30 of file Main_Defines\&.cpp\&.
.SS "word memory_check ()"
This does a memory check of the whole system, and checks to see how much free mem there is\&. 
.PP
Definition at line 19 of file Main_Defines\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "void(* reset_device)(void)=0"

.PP
Reset the device\&. 
.PP
Definition at line 13 of file Main_Defines\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
