.TH "Arduino_ADK_USB_HOST/Sensor_Parser_Implementation/Network_Protocol.h" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/Sensor_Parser_Implementation/Network_Protocol.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBpacket_header_t\fP"
.br
.RI "\fIMain packet header structure\&. \fP"
.ti -1c
.RI "struct \fBrouter_ack_info_t\fP"
.br
.RI "\fIRouter acknowledge message structure\&. \fP"
.ti -1c
.RI "struct \fBrouter_heartbeat_t\fP"
.br
.ti -1c
.RI "struct \fBrouter_status_info_t\fP"
.br
.RI "\fISystem status information\&. \fP"
.ti -1c
.RI "struct \fBrouter_debug_status_t\fP"
.br
.RI "\fIIf we are debugging structure\&. \fP"
.ti -1c
.RI "struct \fBrouter_nmap_info_t\fP"
.br
.ti -1c
.RI "struct \fBrouter_sensor_enable_report_t\fP"
.br
.ti -1c
.RI "struct \fBerror_message_t\fP"
.br
.ti -1c
.RI "class \fBsensor_configs_t\fP"
.br
.RI "\fIThis is the top level structure\&. \fP"
.ti -1c
.RI "class \fBremote_sensor_data_t\fP"
.br
.RI "\fIThe container for each sensor input\&. \fP"
.ti -1c
.RI "struct \fBremote_radio_configs_t\fP"
.br
.RI "\fIThis is the remote radio configs\&. \fP"
.ti -1c
.RI "struct \fBnumber_of_sensors_t\fP"
.br
.RI "\fIThis is the ack message for the number of sensors\&. \fP"
.ti -1c
.RI "struct \fBnumber_of_channels_t\fP"
.br
.RI "\fIThis is the ack message for the number of channels for a sensor\&. \fP"
.ti -1c
.RI "struct \fBlocal_command_t\fP"
.br
.RI "\fIThis executes a command on the local system\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBROUTER_COMS_DEBUG\fP"
.br
.RI "\fIInternal State Machine\&. \fP"
.ti -1c
.RI "#define \fBROUTER_ACK\fP   0x01"
.br
.RI "\fIMessage IDs\&. \fP"
.ti -1c
.RI "#define \fBROUTER_HEARTBEAT\fP   0x02"
.br
.ti -1c
.RI "#define \fBROUTER_STATUS\fP   0x03"
.br
.ti -1c
.RI "#define \fBROUTER_NMAP\fP   0x04"
.br
.ti -1c
.RI "#define \fBROUTER_CONFIG\fP   0x05"
.br
.ti -1c
.RI "#define \fBSENSOR_ENABLE\fP   0x06"
.br
.ti -1c
.RI "#define \fBSENSOR_CONFIGS\fP   0x07"
.br
.ti -1c
.RI "#define \fBSENSOR_DATA\fP   0x08"
.br
.ti -1c
.RI "#define \fBSENSOR_NUMBER\fP   0x09"
.br
.ti -1c
.RI "#define \fBSENSOR_CHANNELS\fP   0x0A"
.br
.ti -1c
.RI "#define \fBUSB_DEVICE_CMD\fP   0x31"
.br
.RI "\fICommand Descriptors\&. \fP"
.ti -1c
.RI "#define \fBROUTER_DEBUG\fP   0x07"
.br
.RI "\fIOptional\&. \fP"
.ti -1c
.RI "#define \fBERROR_MSG\fP   0x0A"
.br
.ti -1c
.RI "#define \fBPACKET_ANY\fP   0xFE"
.br
.RI "\fIInternal packet_id values\&. \fP"
.ti -1c
.RI "#define \fBPACKET_NULL\fP   0xFF"
.br
.ti -1c
.RI "#define \fBERROR_MODE\fP   0xFF"
.br
.RI "\fIRouter modes\&. \fP"
.ti -1c
.RI "#define \fBPWR_ERROR_MODE\fP   0xFE"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ERROR_MODE   0xFF"

.PP
Router modes\&. 
.PP
Definition at line 38 of file Network_Protocol\&.h\&.
.SS "#define ERROR_MSG   0x0A"

.PP
Definition at line 31 of file Network_Protocol\&.h\&.
.SS "#define PACKET_ANY   0xFE"

.PP
Internal packet_id values\&. 
.PP
Definition at line 34 of file Network_Protocol\&.h\&.
.SS "#define PACKET_NULL   0xFF"

.PP
Definition at line 35 of file Network_Protocol\&.h\&.
.SS "#define PWR_ERROR_MODE   0xFE"

.PP
Definition at line 39 of file Network_Protocol\&.h\&.
.SS "#define ROUTER_ACK   0x01"

.PP
Message IDs\&. 
.PP
Definition at line 15 of file Network_Protocol\&.h\&.
.SS "#define ROUTER_COMS_DEBUG"

.PP
Internal State Machine\&. 
.PP
Definition at line 12 of file Network_Protocol\&.h\&.
.SS "#define ROUTER_CONFIG   0x05"

.PP
Definition at line 19 of file Network_Protocol\&.h\&.
.SS "#define ROUTER_DEBUG   0x07"

.PP
Optional\&. 
.PP
Definition at line 30 of file Network_Protocol\&.h\&.
.SS "#define ROUTER_HEARTBEAT   0x02"

.PP
Definition at line 16 of file Network_Protocol\&.h\&.
.SS "#define ROUTER_NMAP   0x04"

.PP
Definition at line 18 of file Network_Protocol\&.h\&.
.SS "#define ROUTER_STATUS   0x03"

.PP
Definition at line 17 of file Network_Protocol\&.h\&.
.SS "#define SENSOR_CHANNELS   0x0A"

.PP
Definition at line 24 of file Network_Protocol\&.h\&.
.SS "#define SENSOR_CONFIGS   0x07"

.PP
Definition at line 21 of file Network_Protocol\&.h\&.
.SS "#define SENSOR_DATA   0x08"

.PP
Definition at line 22 of file Network_Protocol\&.h\&.
.SS "#define SENSOR_ENABLE   0x06"

.PP
Definition at line 20 of file Network_Protocol\&.h\&.
.SS "#define SENSOR_NUMBER   0x09"

.PP
Definition at line 23 of file Network_Protocol\&.h\&.
.SS "#define USB_DEVICE_CMD   0x31"

.PP
Command Descriptors\&. 
.PP
Definition at line 27 of file Network_Protocol\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
