.TH "number_of_channels_t" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
number_of_channels_t \- 
.PP
This is the ack message for the number of channels for a sensor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Network_Protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "byte \fBsensor_id\fP"
.br
.ti -1c
.RI "byte \fBnumber_of_channels\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the ack message for the number of channels for a sensor\&. 
.PP
Definition at line 166 of file Network_Protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "byte number_of_channels_t::number_of_channels"

.PP
Definition at line 168 of file Network_Protocol\&.h\&.
.SS "byte number_of_channels_t::sensor_id"

.PP
Definition at line 167 of file Network_Protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
