.TH "Arduino_ADK_USB_HOST/System_Defines/NVRAM_API.cpp" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/System_Defines/NVRAM_API.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'NVRAM_API\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPACE\fP   ' '"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBNVRAM::nv_data_t\fP 
.br
NVRAM_default \fBPROGMEM\fP"
.br
.RI "\fIDefine the structure\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SPACE   ' '"

.PP
Definition at line 10 of file NVRAM_API\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBNVRAM::nv_data_t\fP NVRAM_default PROGMEM"

.PP
Define the structure\&. 
.PP
Definition at line 13 of file NVRAM_API\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
