.TH "Arduino_ADK_USB_HOST/System_Defines/NVRAM_API.h" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/System_Defines/NVRAM_API.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./System_Defines/Includes\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBNVRAM\fP"
.br
.ti -1c
.RI "struct \fBNVRAM::nv_data_t\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
