.TH "NVRAM" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NVRAM \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NVRAM_API\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBnv_data_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBload\fP (void)"
.br
.RI "\fILoad the saved args\&. \fP"
.ti -1c
.RI "void \fBsave\fP (void)"
.br
.RI "\fISave the args\&. \fP"
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBnv_data_t\fP \fBnv\fP"
.br
.RI "\fIThe exported structure definition\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class handles the \fBNVRAM\fP accesses and storage structure\&. 
.PP
Definition at line 14 of file NVRAM_API\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void NVRAM::load (void)"

.PP
Load the saved args\&. Load all of the saved variables\&. 
.PP
Definition at line 56 of file NVRAM_API\&.cpp\&.
.SS "void NVRAM::save (void)"

.PP
Save the args\&. Save all of the loaded variables\&. 
.PP
Definition at line 69 of file NVRAM_API\&.cpp\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBnv_data_t\fP NVRAM::nv"

.PP
The exported structure definition\&. 
.PP
Definition at line 103 of file NVRAM_API\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
