.TH "NVRAM::nv_data_t" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NVRAM::nv_data_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NVRAM_API\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "word \fBserial1_speed\fP"
.br
.RI "\fISerial settings\&. \fP"
.ti -1c
.RI "word \fBserial2_speed\fP"
.br
.ti -1c
.RI "word \fBserial3_speed\fP"
.br
.ti -1c
.RI "byte \fBnode_address\fP"
.br
.RI "\fIRF settings\&. \fP"
.ti -1c
.RI "byte \fBdevice_mode\fP"
.br
.ti -1c
.RI "byte \fBbutton_1\fP"
.br
.ti -1c
.RI "byte \fBbutton1_setting\fP"
.br
.ti -1c
.RI "byte \fBbutton_2\fP"
.br
.ti -1c
.RI "byte \fBbutton2_setting\fP"
.br
.ti -1c
.RI "byte \fBled_1\fP"
.br
.RI "\fILEDs: \fP"
.ti -1c
.RI "byte \fBled1_setting\fP"
.br
.ti -1c
.RI "byte \fBled_2\fP"
.br
.ti -1c
.RI "byte \fBled2_setting\fP"
.br
.ti -1c
.RI "byte \fBled_3\fP"
.br
.ti -1c
.RI "byte \fBled3_setting\fP"
.br
.ti -1c
.RI "byte \fBled_4\fP"
.br
.ti -1c
.RI "byte \fBled4_setting\fP"
.br
.ti -1c
.RI "byte \fB_ping_router\fP [6]"
.br
.RI "\fIPossible Commands;\&. \fP"
.ti -1c
.RI "byte \fB_ping_sensor\fP [6]"
.br
.ti -1c
.RI "byte \fB_request_router_run\fP [3]"
.br
.ti -1c
.RI "byte \fB_request_router_config\fP [7]"
.br
.ti -1c
.RI "byte \fB_request_sensor_config\fP [7]"
.br
.ti -1c
.RI "byte \fB_request_sensor_enable\fP [7]"
.br
.ti -1c
.RI "byte \fB_request_sensor_channel\fP [10]"
.br
.ti -1c
.RI "byte \fB_request_nmap\fP [4]"
.br
.ti -1c
.RI "byte \fB_request_router_status\fP [6]"
.br
.ti -1c
.RI "byte \fB_pause_sensor\fP [7]"
.br
.ti -1c
.RI "byte \fB_pause_router\fP [7]"
.br
.ti -1c
.RI "byte \fB_power_on_router\fP [6]"
.br
.ti -1c
.RI "byte \fB_power_on_sensor\fP [6]"
.br
.ti -1c
.RI "byte \fB_poweroff_router\fP [6]"
.br
.ti -1c
.RI "byte \fB_poweroff_sensor\fP [6]"
.br
.ti -1c
.RI "byte \fB_wakeup_router\fP [6]"
.br
.ti -1c
.RI "byte \fB_wakeup_sensor\fP [6]"
.br
.ti -1c
.RI "byte \fB_request_sensor_number\fP [7]"
.br
.ti -1c
.RI "byte \fB_request_sensor_channels\fP [7]"
.br
.in -1c
.SH "Detailed Description"
.PP 
The structure for the nvram varialbes\&. 
.PP
Definition at line 51 of file NVRAM_API\&.h\&.
.SH "Field Documentation"
.PP 
.SS "byte NVRAM::nv_data_t::_pause_router[7]"

.PP
Definition at line 90 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_pause_sensor[7]"

.PP
Definition at line 89 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_ping_router[6]"

.PP
Possible Commands;\&. 
.PP
Definition at line 80 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_ping_sensor[6]"

.PP
Definition at line 81 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_power_on_router[6]"

.PP
Definition at line 91 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_power_on_sensor[6]"

.PP
Definition at line 92 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_poweroff_router[6]"

.PP
Definition at line 93 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_poweroff_sensor[6]"

.PP
Definition at line 94 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_request_nmap[4]"

.PP
Definition at line 87 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_request_router_config[7]"

.PP
Definition at line 83 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_request_router_run[3]"

.PP
Definition at line 82 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_request_router_status[6]"

.PP
Definition at line 88 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_request_sensor_channel[10]"

.PP
Definition at line 86 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_request_sensor_channels[7]"

.PP
Definition at line 98 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_request_sensor_config[7]"

.PP
Definition at line 84 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_request_sensor_enable[7]"

.PP
Definition at line 85 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_request_sensor_number[7]"

.PP
Definition at line 97 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_wakeup_router[6]"

.PP
Definition at line 95 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::_wakeup_sensor[6]"

.PP
Definition at line 96 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::button1_setting"

.PP
Definition at line 65 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::button2_setting"

.PP
Definition at line 67 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::button_1"
GPIO settings buttons: 
.PP
Definition at line 64 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::button_2"

.PP
Definition at line 66 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::device_mode"

.PP
Definition at line 60 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::led1_setting"

.PP
Definition at line 71 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::led2_setting"

.PP
Definition at line 73 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::led3_setting"

.PP
Definition at line 75 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::led4_setting"

.PP
Definition at line 77 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::led_1"

.PP
LEDs: 
.PP
Definition at line 70 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::led_2"

.PP
Definition at line 72 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::led_3"

.PP
Definition at line 74 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::led_4"

.PP
Definition at line 76 of file NVRAM_API\&.h\&.
.SS "byte NVRAM::nv_data_t::node_address"

.PP
RF settings\&. 
.PP
Definition at line 59 of file NVRAM_API\&.h\&.
.SS "word NVRAM::nv_data_t::serial1_speed"

.PP
Serial settings\&. 
.PP
Definition at line 54 of file NVRAM_API\&.h\&.
.SS "word NVRAM::nv_data_t::serial2_speed"

.PP
Definition at line 55 of file NVRAM_API\&.h\&.
.SS "word NVRAM::nv_data_t::serial3_speed"

.PP
Definition at line 56 of file NVRAM_API\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
