.TH "Arduino_ADK_USB_HOST/USB_HID_API/oddebug.h" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/USB_HID_API/oddebug.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'usbportability\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBF_CPU\fP   12000000    /* 12 MHz */"
.br
.ti -1c
.RI "#define \fBuchar\fP   unsigned char"
.br
.ti -1c
.RI "#define \fBDEBUG_LEVEL\fP   0"
.br
.ti -1c
.RI "#define \fBDBG1\fP(prefix, \fBdata\fP, len)"
.br
.ti -1c
.RI "#define \fBDBG2\fP(prefix, \fBdata\fP, len)"
.br
.ti -1c
.RI "#define \fBodDebugInit\fP()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DBG1(prefix, \fBdata\fP, len)"

.PP
Definition at line 52 of file oddebug\&.h\&.
.SS "#define DBG2(prefix, \fBdata\fP, len)"

.PP
Definition at line 58 of file oddebug\&.h\&.
.SS "#define DEBUG_LEVEL   0"

.PP
Definition at line 44 of file oddebug\&.h\&.
.SS "#define F_CPU   12000000    /* 12 MHz */"

.PP
Definition at line 28 of file oddebug\&.h\&.
.SS "#define odDebugInit()"

.PP
Definition at line 118 of file oddebug\&.h\&.
.SS "#define uchar   unsigned char"

.PP
Definition at line 35 of file oddebug\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
