.TH "packet_handler_t" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packet_handler_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Packet_Handler\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "byte \fBpacket_id\fP"
.br
.ti -1c
.RI "void(* \fBhandler\fP )(void *arg, byte \fBpacket_id\fP, byte packet_ver, void *packet_data)"
.br
.ti -1c
.RI "void * \fBargs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the packet handler structure\&. It handles the incoming packets based in the ids, and the args\&. 
.PP
Definition at line 27 of file Packet_Handler\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* packet_handler_t::args"

.PP
Definition at line 31 of file Packet_Handler\&.h\&.
.SS "void(*  packet_handler_t::handler)(void *arg, byte \fBpacket_id\fP, byte packet_ver, void *packet_data)"

.PP
Definition at line 30 of file Packet_Handler\&.h\&.
.SS "byte packet_handler_t::packet_id"

.PP
Definition at line 29 of file Packet_Handler\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
