.TH "packet_header_t" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packet_header_t \- 
.PP
Main packet header structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Network_Protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "byte \fBmessage_size\fP"
.br
.ti -1c
.RI "byte \fBpacket_id\fP"
.br
.ti -1c
.RI "byte \fBnode_id\fP"
.br
.ti -1c
.RI "byte \fBsensor_id\fP"
.br
.ti -1c
.RI "uint32_t \fBtime_stamp\fP"
.br
.ti -1c
.RI "uint32_t \fBsensor_run_time\fP"
.br
.ti -1c
.RI "byte \fBpacket_version\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main packet header structure\&. 
.PP
Definition at line 46 of file Network_Protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "byte packet_header_t::message_size"

.PP
Definition at line 48 of file Network_Protocol\&.h\&.
.SS "byte packet_header_t::node_id"

.PP
Definition at line 50 of file Network_Protocol\&.h\&.
.SS "byte packet_header_t::packet_id"

.PP
Definition at line 49 of file Network_Protocol\&.h\&.
.SS "byte packet_header_t::packet_version"

.PP
Definition at line 54 of file Network_Protocol\&.h\&.
.SS "byte packet_header_t::sensor_id"

.PP
Definition at line 51 of file Network_Protocol\&.h\&.
.SS "uint32_t packet_header_t::sensor_run_time"

.PP
Definition at line 53 of file Network_Protocol\&.h\&.
.SS "uint32_t packet_header_t::time_stamp"

.PP
Definition at line 52 of file Network_Protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
