.TH "Arduino_ADK_USB_HOST/Sensor_Parser_Implementation/Packet_Parser.h" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/Sensor_Parser_Implementation/Packet_Parser.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'System_Defines/Main_Defines\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPACKET_PARSER\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_TOKENS\fP   40"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_TOKENS   40"

.PP
Definition at line 13 of file Packet_Parser\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
