.TH "PACKET_DECODER" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PACKET_DECODER \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Packet_Handler\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPACKET_DECODER\fP (struct \fBpacket_handler_t\fP *handler_table)"
.br
.ti -1c
.RI "void \fBpoll\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class contains the methods that handle and decode the packets, as they come in the state machine\&. 
.PP
Definition at line 38 of file Packet_Handler\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PACKET_DECODER::PACKET_DECODER (struct \fBpacket_handler_t\fP *handler_table)"
The overwritten default constructor, that takes in a handler table\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhandler_table\fP - \fBpacket_handler_t\fP
.RE
.PP
This is the packet decoder, over written with a past handler_table structure\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhandler_table\fP - \fBpacket_handler_t\fP 
.RE
.PP
Assign the default variables\&.
.PP
Set to 0 
.PP
Definition at line 15 of file Packet_Handler\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void PACKET_DECODER::poll (void)"
This is the poll loop for the incoming bytes\&.
.PP
Poll loop reading is data from the Serial device\&. 
.PP
Definition at line 36 of file Packet_Handler\&.cpp\&.
.SH "Field Documentation"
.PP 
.SS "byte PACKET_DECODER::bytes[1]"

.PP
Definition at line 61 of file Packet_Handler\&.h\&.
.SS "struct \fBpacket_header_t\fP PACKET_DECODER::header"

.PP
Definition at line 62 of file Packet_Handler\&.h\&.
.SS "union packet_structure PACKET_DECODER::packet"

.PP
Definition at line 63 of file Packet_Handler\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
