.TH "PACKET_PARSER" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PACKET_PARSER \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Packet_Parser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPACKET_PARSER\fP ()"
.br
.RI "\fIDefault constructor\&. \fP"
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBparse\fP (void *arg, byte packet_id, byte packet_ver, void *buf)"
.br
.RI "\fIParse the structures\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Packet Structure Definition\&. [HEADER][ID][MESSAGE_LENGTH][JSON_STRING][TAIL] [+][##][##][{SRINGS}][*] This class takes care of the packet parsing\&. 
.PP
Definition at line 24 of file Packet_Parser\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PACKET_PARSER::PACKET_PARSER ()"

.PP
Default constructor\&. Default constructor 
.PP
Definition at line 12 of file Packet_Parser\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static void PACKET_PARSER::parse (void *arg, bytepacket_id, bytepacket_ver, void *buf)\fC [static]\fP"

.PP
Parse the structures\&. Publicly accessible parsing method\&.
.PP
\fBParameters:\fP
.RS 4
\fIarg\fP - void* 
.br
\fIpacket_id\fP - byte 
.br
\fIpacket_ver\fP - byte 
.br
\fIbuf\fP - void* 
.RE
.PP
Check if there is space left
.PP
Check if the string is ok to process\&.
.PP
Process String 
.PP
Definition at line 17 of file Packet_Parser\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
