.TH "Arduino_ADK_USB_HOST/Sensor_Parser_Implementation/Packet_Handler.h" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/Sensor_Parser_Implementation/Packet_Handler.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'System_Defines/Main_Defines\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBpacket_handler_t\fP"
.br
.ti -1c
.RI "class \fBPACKET_DECODER\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPACKET_WAIT_PHASE_1\fP   0"
.br
.RI "\fIInternal State Machine\&. \fP"
.ti -1c
.RI "#define \fBPACKET_WAIT_PHASE_2\fP   1"
.br
.ti -1c
.RI "#define \fBPACKET_WAIT_HEADER\fP   2"
.br
.ti -1c
.RI "#define \fBPACKET_WAIT_PACKET\fP   3"
.br
.ti -1c
.RI "#define \fBPACKET_WAIT_SUM_A\fP   4"
.br
.ti -1c
.RI "#define \fBPACEKT_WAIT_SUM_B\fP   5"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PACEKT_WAIT_SUM_B   5"

.PP
Definition at line 21 of file Packet_Handler\&.h\&.
.SS "#define PACKET_WAIT_HEADER   2"

.PP
Definition at line 18 of file Packet_Handler\&.h\&.
.SS "#define PACKET_WAIT_PACKET   3"

.PP
Definition at line 19 of file Packet_Handler\&.h\&.
.SS "#define PACKET_WAIT_PHASE_1   0"

.PP
Internal State Machine\&. 
.PP
Definition at line 16 of file Packet_Handler\&.h\&.
.SS "#define PACKET_WAIT_PHASE_2   1"

.PP
Definition at line 17 of file Packet_Handler\&.h\&.
.SS "#define PACKET_WAIT_SUM_A   4"

.PP
Definition at line 20 of file Packet_Handler\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
