.TH "remote_radio_configs_t" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
remote_radio_configs_t \- 
.PP
This is the remote radio configs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Network_Protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "word \fBvalues\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the remote radio configs\&. 
.PP
Definition at line 154 of file Network_Protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "word remote_radio_configs_t::values[8]"

.PP
Definition at line 155 of file Network_Protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
