.TH "router_ack_info_t" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
router_ack_info_t \- 
.PP
Router acknowledge message structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Network_Protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBack\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Router acknowledge message structure\&. 
.PP
Definition at line 59 of file Network_Protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "bool router_ack_info_t::ack"

.PP
Definition at line 61 of file Network_Protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
