.TH "router_status_info_t" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
router_status_info_t \- 
.PP
System status information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Network_Protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "byte \fBpower_state\fP"
.br
.ti -1c
.RI "byte \fBrouter_mode\fP"
.br
.ti -1c
.RI "byte \fBerror_count\fP"
.br
.ti -1c
.RI "byte \fBdebug_enable_flag\fP"
.br
.ti -1c
.RI "byte \fBbattery_voltage\fP"
.br
.ti -1c
.RI "byte \fBrouter_address\fP"
.br
.ti -1c
.RI "String \fBrouter_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
System status information\&. 
.PP
Definition at line 75 of file Network_Protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "byte router_status_info_t::battery_voltage"

.PP
Definition at line 83 of file Network_Protocol\&.h\&.
.SS "byte router_status_info_t::debug_enable_flag"

.PP
Definition at line 82 of file Network_Protocol\&.h\&.
.SS "byte router_status_info_t::error_count"

.PP
Definition at line 81 of file Network_Protocol\&.h\&.
.SS "byte router_status_info_t::power_state"

.PP
Definition at line 78 of file Network_Protocol\&.h\&.
.SS "byte router_status_info_t::router_address"

.PP
Definition at line 86 of file Network_Protocol\&.h\&.
.SS "String router_status_info_t::router_id"

.PP
Definition at line 87 of file Network_Protocol\&.h\&.
.SS "byte router_status_info_t::router_mode"

.PP
Definition at line 79 of file Network_Protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
