.TH "router_debug_status_t" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
router_debug_status_t \- 
.PP
If we are debugging structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Network_Protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "word \fBrouter_acks_sent_counter\fP"
.br
.ti -1c
.RI "word \fBrouter_sent_request_counter\fP"
.br
.ti -1c
.RI "word \fBrouter_packet_counter\fP"
.br
.ti -1c
.RI "word \fBrouter_rx_count\fP"
.br
.ti -1c
.RI "word \fBrouter_tx_count\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
If we are debugging structure\&. 
.PP
Definition at line 93 of file Network_Protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "word router_debug_status_t::router_acks_sent_counter"

.PP
Definition at line 96 of file Network_Protocol\&.h\&.
.SS "word router_debug_status_t::router_packet_counter"

.PP
Definition at line 98 of file Network_Protocol\&.h\&.
.SS "word router_debug_status_t::router_rx_count"

.PP
Definition at line 99 of file Network_Protocol\&.h\&.
.SS "word router_debug_status_t::router_sent_request_counter"

.PP
Definition at line 97 of file Network_Protocol\&.h\&.
.SS "word router_debug_status_t::router_tx_count"

.PP
Definition at line 100 of file Network_Protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
