.TH "router_nmap_info_t" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
router_nmap_info_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Network_Protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "byte \fBsensor_id\fP"
.br
.ti -1c
.RI "byte \fBsensor_address\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
We need to make this for each sensor Network map object 
.PP
Definition at line 106 of file Network_Protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "byte router_nmap_info_t::sensor_address"

.PP
Definition at line 109 of file Network_Protocol\&.h\&.
.SS "byte router_nmap_info_t::sensor_id"

.PP
Definition at line 108 of file Network_Protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
