.TH "router_heartbeat_t" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
router_heartbeat_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Network_Protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "byte \fBrouter_mode\fP"
.br
.ti -1c
.RI "byte \fBbattery_voltage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The heartbeat sent to the ground station THIS OCCURS EVERY 2 SECS 
.PP
Definition at line 67 of file Network_Protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "byte router_heartbeat_t::battery_voltage"

.PP
Definition at line 70 of file Network_Protocol\&.h\&.
.SS "byte router_heartbeat_t::router_mode"

.PP
Definition at line 69 of file Network_Protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
