.TH "router_sensor_enable_report_t" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
router_sensor_enable_report_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Network_Protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "byte \fBnumber_sensors\fP"
.br
.ti -1c
.RI "byte \fBsensor_config_enable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 114 of file Network_Protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "byte router_sensor_enable_report_t::number_sensors"

.PP
Definition at line 116 of file Network_Protocol\&.h\&.
.SS "byte router_sensor_enable_report_t::sensor_config_enable"

.PP
Definition at line 117 of file Network_Protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
