.TH "Arduino_ADK_USB_HOST/USB_Device_Implementation/USB_State_Machine.h" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/USB_Device_Implementation/USB_State_Machine.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./System_Defines/Main_Defines\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBUSB_STATE_MACHINE\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOCAL_RESET\fP   -1"
.br
.RI "\fIUSB State machine\&. \fP"
.ti -1c
.RI "#define \fBNETWORK_RESET\fP   -2"
.br
.ti -1c
.RI "#define \fBLOCAL_DEVICE_SETUP\fP   0"
.br
.ti -1c
.RI "#define \fBNETWORK_SETUP\fP   1"
.br
.ti -1c
.RI "#define \fBNETWORK_WAKE_ID_REQUEST\fP   2"
.br
.ti -1c
.RI "#define \fBNETWORK_STATUS_REQUEST\fP   3"
.br
.ti -1c
.RI "#define \fBNETWORK_MAP_REQUEST\fP   4"
.br
.ti -1c
.RI "#define \fBNETWORK_SENSOR_CONFIGS\fP   5"
.br
.ti -1c
.RI "#define \fBLOCAL_CONFIGURATION\fP   6"
.br
.ti -1c
.RI "#define \fBNETWORK_REQUEST_ROUTER_STATE_RUN\fP   7"
.br
.ti -1c
.RI "#define \fBLOCAL_ERROR_MODE\fP(state)   (20 + state)"
.br
.ti -1c
.RI "#define \fBNETWORK_ERROR_MODE\fP(state)   (40 + state)"
.br
.ti -1c
.RI "#define \fBLOCAL_COMMAND_MODE\fP   70"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOCAL_COMMAND_MODE   70"

.PP
Definition at line 25 of file USB_State_Machine\&.h\&.
.SS "#define LOCAL_CONFIGURATION   6"

.PP
Definition at line 19 of file USB_State_Machine\&.h\&.
.SS "#define LOCAL_DEVICE_SETUP   0"

.PP
Definition at line 13 of file USB_State_Machine\&.h\&.
.SS "#define LOCAL_ERROR_MODE(state)   (20 + state)"

.PP
Definition at line 22 of file USB_State_Machine\&.h\&.
.SS "#define LOCAL_RESET   -1"

.PP
USB State machine\&. 
.PP
Definition at line 11 of file USB_State_Machine\&.h\&.
.SS "#define NETWORK_ERROR_MODE(state)   (40 + state)"

.PP
Definition at line 23 of file USB_State_Machine\&.h\&.
.SS "#define NETWORK_MAP_REQUEST   4"

.PP
Definition at line 17 of file USB_State_Machine\&.h\&.
.SS "#define NETWORK_REQUEST_ROUTER_STATE_RUN   7"

.PP
Definition at line 20 of file USB_State_Machine\&.h\&.
.SS "#define NETWORK_RESET   -2"

.PP
Definition at line 12 of file USB_State_Machine\&.h\&.
.SS "#define NETWORK_SENSOR_CONFIGS   5"

.PP
Definition at line 18 of file USB_State_Machine\&.h\&.
.SS "#define NETWORK_SETUP   1"

.PP
Definition at line 14 of file USB_State_Machine\&.h\&.
.SS "#define NETWORK_STATUS_REQUEST   3"

.PP
Definition at line 16 of file USB_State_Machine\&.h\&.
.SS "#define NETWORK_WAKE_ID_REQUEST   2"

.PP
Definition at line 15 of file USB_State_Machine\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
