.TH "Arduino_ADK_USB_HOST/USB_Device_Implementation/USB_Device_Implementation.h" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/USB_Device_Implementation/USB_Device_Implementation.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'System_Defines/Main_Defines\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBUSB_DEVICE\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
