.TH "USB_STATE_MACHINE" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USB_STATE_MACHINE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <USB_State_Machine\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUSB_STATE_MACHINE\fP ()"
.br
.RI "\fISetup the state machine\&. \fP"
.ti -1c
.RI "void \fBmove_state_forward\fP ()"
.br
.RI "\fIMove forawards\&. \fP"
.ti -1c
.RI "void \fBmove_state_backwards\fP ()"
.br
.RI "\fIMove backwards\&. \fP"
.ti -1c
.RI "void \fBmove_state_to_local_error\fP (byte previous_state)"
.br
.RI "\fIMove to local error\&. \fP"
.ti -1c
.RI "void \fBmove_state_to_network_error\fP (byte previous_state)"
.br
.RI "\fIMove to network error\&. \fP"
.ti -1c
.RI "void \fBmove_state_to_local_reset\fP ()"
.br
.RI "\fIMove to local reset\&. \fP"
.ti -1c
.RI "void \fBmove_state_to_network_reset\fP ()"
.br
.RI "\fIMove to network reset\&. \fP"
.ti -1c
.RI "byte \fBget_current_state\fP ()"
.br
.RI "\fIGets the current state\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class handles the operations with the USB state machine\&. 
.PP
Definition at line 32 of file USB_State_Machine\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "USB_STATE_MACHINE::USB_STATE_MACHINE ()"

.PP
Setup the state machine\&. Default constructor\&. 
.PP
Definition at line 12 of file USB_State_Machine\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "byte USB_STATE_MACHINE::get_current_state ()"

.PP
Gets the current state\&. Gets the state current state\&. 
.PP
Definition at line 73 of file USB_State_Machine\&.cpp\&.
.SS "void USB_STATE_MACHINE::move_state_backwards ()"

.PP
Move backwards\&. Move state backwards by 1 
.PP
Definition at line 20 of file USB_State_Machine\&.cpp\&.
.SS "void USB_STATE_MACHINE::move_state_forward ()"

.PP
Move forawards\&. Move state forwards by 1 
.PP
Definition at line 27 of file USB_State_Machine\&.cpp\&.
.SS "void USB_STATE_MACHINE::move_state_to_local_error (byteprevious_state)"

.PP
Move to local error\&. Move state to the local error hang state\&. 
.PP
Definition at line 37 of file USB_State_Machine\&.cpp\&.
.SS "void USB_STATE_MACHINE::move_state_to_local_reset ()"

.PP
Move to local reset\&. Move the state to reset\&.\&.\&. calls reset_device\&. 
.PP
Definition at line 44 of file USB_State_Machine\&.cpp\&.
.SS "void USB_STATE_MACHINE::move_state_to_network_error (byteprevious_state)"

.PP
Move to network error\&. Move state to the network error hang state\&. 
.PP
Definition at line 51 of file USB_State_Machine\&.cpp\&.
.SS "void USB_STATE_MACHINE::move_state_to_network_reset ()"

.PP
Move to network reset\&. Move the state to the network reset states, and polls until ack\&. 
.PP
Definition at line 62 of file USB_State_Machine\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
