.TH "Arduino_ADK_USB_HOST/USB_Device_Implementation/USB_Device_Implementation.cpp" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/USB_Device_Implementation/USB_Device_Implementation.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'USB_Device_Implementation\&.h'\fP
.br
\fC#include 'System_Defines/Main_Defines\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBROUTER\fP   0"
.br
.ti -1c
.RI "#define \fBBUTTONS\fP   0"
.br
.ti -1c
.RI "#define \fBWHEEL\fP   1"
.br
.ti -1c
.RI "#define \fBX_AXIS\fP   2"
.br
.ti -1c
.RI "#define \fBY_AXIS\fP   3"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUTTONS   0"

.PP
Definition at line 12 of file USB_Device_Implementation\&.cpp\&.
.SS "#define ROUTER   0"

.PP
Definition at line 11 of file USB_Device_Implementation\&.cpp\&.
.SS "#define WHEEL   1"

.PP
Definition at line 13 of file USB_Device_Implementation\&.cpp\&.
.SS "#define X_AXIS   2"

.PP
Definition at line 14 of file USB_Device_Implementation\&.cpp\&.
.SS "#define Y_AXIS   3"

.PP
Definition at line 15 of file USB_Device_Implementation\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
