.TH "Arduino_ADK_USB_HOST/USB_Implementation/USB_Reports.h" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/USB_Implementation/USB_Reports.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./System_Defines/Includes\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
