.TH "Arduino_ADK_USB_HOST/USB_Implementation/USB_Functions.cpp" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/USB_Implementation/USB_Functions.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'USB_Functions\&.h'\fP
.br
\fC#include '\&.\&./System_Defines/Main_Defines\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBusbMsgLen_t\fP \fBusbFunctionSetup\fP (byte \fBdata\fP[8])"
.br
.ti -1c
.RI "void \fBusbSendHidReport\fP (byte *\fBdata\fP, \fBuchar\fP len)"
.br
.ti -1c
.RI "void \fBsend_mouse_report\fP (struct mouse_report_t *report)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void send_mouse_report (struct mouse_report_t *report)"
This function by definition takes in a usb report structure and sends it to the host\&.
.PP
\fBParameters:\fP
.RS 4
\fIreport\fP - mouse_report_t* 
.RE
.PP

.PP
Definition at line 106 of file USB_Functions\&.cpp\&.
.SS "\fBusbMsgLen_t\fP usbFunctionSetup (bytedata[8])"
This function is used to setup the USB functionality\&. Its sets up the structure of the report, and also filters to the preferred HID report to send\&.
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP - Setup data 
.RE
.PP
\fBReturns:\fP
.RS 4
- usbMsgLen 
.RE
.PP
see HID1_11\&.pdf sect 7\&.2 and http://vusb.wikidot.com/driver-api
.PP
ignore request if it's not a class specific request
.PP
see HID1_11\&.pdf sect 7\&.2
.PP
send data starting from this byte
.PP
send 1 byte
.PP
read in idle rate
.PP
send nothing
.PP
send data starting from this byte
.PP
send 1 byte
.PP
send nothing
.PP
no such report, send nothing
.PP
no 'output' or 'feature' implemented, so ignore
.PP
send nothing
.PP
do not understand data, ignore
.PP
send nothing 
.PP
Definition at line 19 of file USB_Functions\&.cpp\&.
.SS "void usbSendHidReport (byte *data, \fBuchar\fPlen)"
This function is used to guarantee that the data is sent to the computer once\&. Sends the usb report through the serial interface\&.
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP - USB Report type 
.br
\fIlen\fP - sizeof(USB Report) 
.RE
.PP

.PP
Definition at line 77 of file USB_Functions\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
