.TH "Arduino_ADK_USB_HOST/USB_Implementation/usbconfig.h" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/USB_Implementation/usbconfig.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSB_CFG_IOPORTNAME\fP   D"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DMINUS_BIT\fP   7"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DPLUS_BIT\fP   2"
.br
.ti -1c
.RI "#define \fBUSB_CFG_CLOCK_KHZ\fP   (\fBF_CPU\fP/1000)"
.br
.ti -1c
.RI "#define \fBUSB_CFG_CHECK_CRC\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_HAVE_INTRIN_ENDPOINT\fP   1"
.br
.ti -1c
.RI "#define \fBUSB_CFG_HAVE_INTRIN_ENDPOINT3\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_EP3_NUMBER\fP   3"
.br
.ti -1c
.RI "#define \fBUSB_CFG_IMPLEMENT_HALT\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_SUPPRESS_INTR_CODE\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_INTR_POLL_INTERVAL\fP   10"
.br
.ti -1c
.RI "#define \fBUSB_CFG_IS_SELF_POWERED\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_MAX_BUS_POWER\fP   200"
.br
.ti -1c
.RI "#define \fBUSB_CFG_IMPLEMENT_FN_WRITE\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_IMPLEMENT_FN_READ\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_IMPLEMENT_FN_WRITEOUT\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_HAVE_FLOWCONTROL\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DRIVER_FLASH_PAGE\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_LONG_TRANSFERS\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_COUNT_SOF\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_CHECK_DATA_TOGGLING\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_HAVE_MEASURE_FRAME_LENGTH\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_USE_FAST_CRC\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_VENDOR_ID\fP   0xc0, 0x16 /* = 0x16c0 = 5824 = voti\&.nl */"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DEVICE_ID\fP   0xdc, 0x06 /* = 0x05dc = 1500 */"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DEVICE_VERSION\fP   0x00, 0x01"
.br
.ti -1c
.RI "#define \fBUSB_CFG_VENDOR_NAME\fP   'C', 'a', 'r', 'l', 'e', 't', 'o', 'n', ' ', 'U', 'n', 'i', 'v', 'e', 'r', 's', 'i', 't', 'y',"
.br
.ti -1c
.RI "#define \fBUSB_CFG_VENDOR_NAME_LEN\fP   19"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DEVICE_NAME\fP   'U', 'S', 'B', ' ', 'H', 'I', 'D', ' ', 'D', 'e', 'v', 'i', 'c', 'e', 's',"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DEVICE_NAME_LEN\fP   15"
.br
.ti -1c
.RI "#define \fBUSB_CFG_SERIAL_NUMBER\fP   '0', 'x', '0', '1'"
.br
.ti -1c
.RI "#define \fBUSB_CFG_SERIAL_NUMBER_LEN\fP   4"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DEVICE_CLASS\fP   0x00    /* set to 0 if deferred to interface */"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DEVICE_SUBCLASS\fP   0x00"
.br
.ti -1c
.RI "#define \fBUSB_CFG_INTERFACE_CLASS\fP   0x03   /* HID */"
.br
.ti -1c
.RI "#define \fBUSB_CFG_INTERFACE_SUBCLASS\fP   0x00"
.br
.ti -1c
.RI "#define \fBUSB_CFG_INTERFACE_PROTOCOL\fP   0x00"
.br
.ti -1c
.RI "#define \fBUSB_CFG_HID_REPORT_DESCRIPTOR_LENGTH\fP"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DESCR_PROPS_DEVICE\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DESCR_PROPS_CONFIGURATION\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DESCR_PROPS_STRINGS\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DESCR_PROPS_STRING_0\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DESCR_PROPS_STRING_VENDOR\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DESCR_PROPS_STRING_PRODUCT\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DESCR_PROPS_STRING_SERIAL_NUMBER\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DESCR_PROPS_HID\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DESCR_PROPS_HID_REPORT\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DESCR_PROPS_UNKNOWN\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define USB_CFG_CHECK_CRC   0"

.PP
Definition at line 55 of file usbconfig\&.h\&.
.SS "#define USB_CFG_CHECK_DATA_TOGGLING   0"

.PP
Definition at line 199 of file usbconfig\&.h\&.
.SS "#define USB_CFG_CLOCK_KHZ   (\fBF_CPU\fP/1000)"

.PP
Definition at line 46 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DESCR_PROPS_CONFIGURATION   0"

.PP
Definition at line 349 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DESCR_PROPS_DEVICE   0"

.PP
Definition at line 348 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DESCR_PROPS_HID   0"

.PP
Definition at line 355 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DESCR_PROPS_HID_REPORT   0"

.PP
Definition at line 356 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DESCR_PROPS_STRING_0   0"

.PP
Definition at line 351 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DESCR_PROPS_STRING_PRODUCT   0"

.PP
Definition at line 353 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DESCR_PROPS_STRING_SERIAL_NUMBER   0"

.PP
Definition at line 354 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DESCR_PROPS_STRING_VENDOR   0"

.PP
Definition at line 352 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DESCR_PROPS_STRINGS   0"

.PP
Definition at line 350 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DESCR_PROPS_UNKNOWN   0"

.PP
Definition at line 357 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DEVICE_CLASS   0x00    /* set to 0 if deferred to interface */"

.PP
Definition at line 270 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DEVICE_ID   0xdc, 0x06 /* = 0x05dc = 1500 */"

.PP
Definition at line 231 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DEVICE_NAME   'U', 'S', 'B', ' ', 'H', 'I', 'D', ' ', 'D', 'e', 'v', 'i', 'c', 'e', 's',"

.PP
Definition at line 255 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DEVICE_NAME_LEN   15"

.PP
Definition at line 256 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DEVICE_SUBCLASS   0x00"

.PP
Definition at line 271 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DEVICE_VERSION   0x00, 0x01"

.PP
Definition at line 242 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DMINUS_BIT   7"

.PP
Definition at line 33 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DPLUS_BIT   2"

.PP
Definition at line 37 of file usbconfig\&.h\&.
.SS "#define USB_CFG_DRIVER_FLASH_PAGE   0"

.PP
Definition at line 149 of file usbconfig\&.h\&.
.SS "#define USB_CFG_EP3_NUMBER   3"

.PP
Definition at line 89 of file usbconfig\&.h\&.
.SS "#define USB_CFG_HAVE_FLOWCONTROL   0"

.PP
Definition at line 144 of file usbconfig\&.h\&.
.SS "#define USB_CFG_HAVE_INTRIN_ENDPOINT   1"

.PP
Definition at line 78 of file usbconfig\&.h\&.
.SS "#define USB_CFG_HAVE_INTRIN_ENDPOINT3   0"

.PP
Definition at line 83 of file usbconfig\&.h\&.
.SS "#define USB_CFG_HAVE_MEASURE_FRAME_LENGTH   0"

.PP
Definition at line 207 of file usbconfig\&.h\&.
.SS "#define USB_CFG_HID_REPORT_DESCRIPTOR_LENGTH"

.PP
Definition at line 283 of file usbconfig\&.h\&.
.SS "#define USB_CFG_IMPLEMENT_FN_READ   0"

.PP
Definition at line 132 of file usbconfig\&.h\&.
.SS "#define USB_CFG_IMPLEMENT_FN_WRITE   0"

.PP
Definition at line 127 of file usbconfig\&.h\&.
.SS "#define USB_CFG_IMPLEMENT_FN_WRITEOUT   0"

.PP
Definition at line 138 of file usbconfig\&.h\&.
.SS "#define USB_CFG_IMPLEMENT_HALT   0"

.PP
Definition at line 99 of file usbconfig\&.h\&.
.SS "#define USB_CFG_INTERFACE_CLASS   0x03   /* HID */"

.PP
Definition at line 275 of file usbconfig\&.h\&.
.SS "#define USB_CFG_INTERFACE_PROTOCOL   0x00"

.PP
Definition at line 277 of file usbconfig\&.h\&.
.SS "#define USB_CFG_INTERFACE_SUBCLASS   0x00"

.PP
Definition at line 276 of file usbconfig\&.h\&.
.SS "#define USB_CFG_INTR_POLL_INTERVAL   10"

.PP
Definition at line 113 of file usbconfig\&.h\&.
.SS "#define USB_CFG_IOPORTNAME   D"

.PP
Definition at line 29 of file usbconfig\&.h\&.
.SS "#define USB_CFG_IS_SELF_POWERED   0"

.PP
Definition at line 118 of file usbconfig\&.h\&.
.SS "#define USB_CFG_LONG_TRANSFERS   0"

.PP
Definition at line 154 of file usbconfig\&.h\&.
.SS "#define USB_CFG_MAX_BUS_POWER   200"

.PP
Definition at line 122 of file usbconfig\&.h\&.
.SS "#define USB_CFG_SERIAL_NUMBER   '0', 'x', '0', '1'"

.PP
Definition at line 261 of file usbconfig\&.h\&.
.SS "#define USB_CFG_SERIAL_NUMBER_LEN   4"

.PP
Definition at line 262 of file usbconfig\&.h\&.
.SS "#define USB_CFG_SUPPRESS_INTR_CODE   0"

.PP
Definition at line 105 of file usbconfig\&.h\&.
.SS "#define USB_CFG_VENDOR_ID   0xc0, 0x16 /* = 0x16c0 = 5824 = voti\&.nl */"

.PP
Definition at line 222 of file usbconfig\&.h\&.
.SS "#define USB_CFG_VENDOR_NAME   'C', 'a', 'r', 'l', 'e', 't', 'o', 'n', ' ', 'U', 'n', 'i', 'v', 'e', 'r', 's', 'i', 't', 'y',"

.PP
Definition at line 245 of file usbconfig\&.h\&.
.SS "#define USB_CFG_VENDOR_NAME_LEN   19"

.PP
Definition at line 246 of file usbconfig\&.h\&.
.SS "#define USB_COUNT_SOF   0"

.PP
Definition at line 175 of file usbconfig\&.h\&.
.SS "#define USB_USE_FAST_CRC   0"

.PP
Definition at line 211 of file usbconfig\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
