.TH "Arduino_ADK_USB_HOST/USB_HID_API/usbdrv.h" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/USB_HID_API/usbdrv.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'usbconfig\&.h'\fP
.br
\fC#include 'usbportability\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBusbTxStatus\fP"
.br
.ti -1c
.RI "union \fBusbWord\fP"
.br
.ti -1c
.RI "struct \fBusbRequest\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSBDRV_VERSION\fP   20100715"
.br
.ti -1c
.RI "#define \fBUSB_PUBLIC\fP"
.br
.ti -1c
.RI "#define \fBuchar\fP   unsigned char"
.br
.ti -1c
.RI "#define \fBschar\fP   signed char"
.br
.ti -1c
.RI "#define \fBusbMsgLen_t\fP   \fBuchar\fP"
.br
.ti -1c
.RI "#define \fBUSB_NO_MSG\fP   ((\fBusbMsgLen_t\fP)-1)   /* constant meaning 'no message' */"
.br
.ti -1c
.RI "#define \fBusbInterruptIsReady\fP()   (\fBusbTxLen1\fP & 0x10)"
.br
.ti -1c
.RI "#define \fBusbDeviceConnect\fP()   (\fBUSBDDR\fP &= ~(1<<\fBUSBMINUS\fP))"
.br
.ti -1c
.RI "#define \fBusbDeviceDisconnect\fP()   (\fBUSBDDR\fP |= (1<<\fBUSBMINUS\fP))"
.br
.ti -1c
.RI "#define \fBusbCrc16\fP(\fBdata\fP, len)   usbCrc16((unsigned)(\fBdata\fP), len)"
.br
.ti -1c
.RI "#define \fBusbCrc16Append\fP(\fBdata\fP, len)   usbCrc16Append((unsigned)(\fBdata\fP), len)"
.br
.ti -1c
.RI "#define \fBUSB_STRING_DESCRIPTOR_HEADER\fP(stringLength)   ((2*(stringLength)+2) | (3<<8))"
.br
.ti -1c
.RI "#define \fBUSB_SET_DATATOKEN1\fP(token)   \fBusbTxBuf1\fP[0] = token"
.br
.ti -1c
.RI "#define \fBUSB_SET_DATATOKEN3\fP(token)   \fBusbTxBuf3\fP[0] = token"
.br
.ti -1c
.RI "#define \fBUSB_PROP_IS_DYNAMIC\fP   (1 << 14)"
.br
.ti -1c
.RI "#define \fBUSB_PROP_IS_RAM\fP   (1 << 15)"
.br
.ti -1c
.RI "#define \fBUSB_PROP_LENGTH\fP(len)   ((len) & 0x3fff)"
.br
.ti -1c
.RI "#define \fBUSB_CFG_DESCR_PROPS_HID_REPORT\fP   0"
.br
.ti -1c
.RI "#define \fBUSB_CONCAT\fP(a, b)   a ## b"
.br
.ti -1c
.RI "#define \fBUSB_CONCAT_EXPANDED\fP(a, b)   \fBUSB_CONCAT\fP(a, b)"
.br
.ti -1c
.RI "#define \fBUSB_OUTPORT\fP(name)   \fBUSB_CONCAT\fP(PORT, name)"
.br
.ti -1c
.RI "#define \fBUSB_INPORT\fP(name)   \fBUSB_CONCAT\fP(PIN, name)"
.br
.ti -1c
.RI "#define \fBUSB_DDRPORT\fP(name)   \fBUSB_CONCAT\fP(DDR, name)"
.br
.ti -1c
.RI "#define \fBUSBOUT\fP   \fBUSB_OUTPORT\fP(\fBUSB_CFG_IOPORTNAME\fP)"
.br
.ti -1c
.RI "#define \fBUSB_PULLUP_OUT\fP   \fBUSB_OUTPORT\fP(USB_CFG_PULLUP_IOPORTNAME)"
.br
.ti -1c
.RI "#define \fBUSBIN\fP   \fBUSB_INPORT\fP(\fBUSB_CFG_IOPORTNAME\fP)"
.br
.ti -1c
.RI "#define \fBUSBDDR\fP   \fBUSB_DDRPORT\fP(\fBUSB_CFG_IOPORTNAME\fP)"
.br
.ti -1c
.RI "#define \fBUSB_PULLUP_DDR\fP   \fBUSB_DDRPORT\fP(USB_CFG_PULLUP_IOPORTNAME)"
.br
.ti -1c
.RI "#define \fBUSBMINUS\fP   \fBUSB_CFG_DMINUS_BIT\fP"
.br
.ti -1c
.RI "#define \fBUSBPLUS\fP   \fBUSB_CFG_DPLUS_BIT\fP"
.br
.ti -1c
.RI "#define \fBUSBIDLE\fP   (1<<\fBUSB_CFG_DMINUS_BIT\fP) /* value representing J state */"
.br
.ti -1c
.RI "#define \fBUSBMASK\fP   ((1<<\fBUSB_CFG_DPLUS_BIT\fP) | (1<<\fBUSB_CFG_DMINUS_BIT\fP))  /* mask for USB I/O bits */"
.br
.ti -1c
.RI "#define \fBUSB_CFG_IOPORT\fP   \fBUSB_OUTPORT\fP(\fBUSB_CFG_IOPORTNAME\fP)"
.br
.ti -1c
.RI "#define \fBUSB_BUFSIZE\fP   11  /* PID, 8 bytes \fBdata\fP, 2 bytes CRC */"
.br
.ti -1c
.RI "#define \fBUSB_INTR_CFG\fP   MCUCR"
.br
.ti -1c
.RI "#define \fBUSB_INTR_CFG_SET\fP   (1 << ISC01)                    /* cfg for falling edge */"
.br
.ti -1c
.RI "#define \fBUSB_INTR_CFG_CLR\fP   0    /* no bits to clear */"
.br
.ti -1c
.RI "#define \fBUSB_INTR_ENABLE\fP   GICR"
.br
.ti -1c
.RI "#define \fBUSB_INTR_ENABLE_BIT\fP   INT0"
.br
.ti -1c
.RI "#define \fBUSB_INTR_PENDING\fP   GIFR"
.br
.ti -1c
.RI "#define \fBUSB_INTR_PENDING_BIT\fP   INTF0"
.br
.ti -1c
.RI "#define \fBUSBPID_SETUP\fP   0x2d"
.br
.ti -1c
.RI "#define \fBUSBPID_OUT\fP   0xe1"
.br
.ti -1c
.RI "#define \fBUSBPID_IN\fP   0x69"
.br
.ti -1c
.RI "#define \fBUSBPID_DATA0\fP   0xc3"
.br
.ti -1c
.RI "#define \fBUSBPID_DATA1\fP   0x4b"
.br
.ti -1c
.RI "#define \fBUSBPID_ACK\fP   0xd2"
.br
.ti -1c
.RI "#define \fBUSBPID_NAK\fP   0x5a"
.br
.ti -1c
.RI "#define \fBUSBPID_STALL\fP   0x1e"
.br
.ti -1c
.RI "#define \fBUSB_INITIAL_DATATOKEN\fP   \fBUSBPID_DATA1\fP"
.br
.ti -1c
.RI "#define \fBusbTxLen1\fP   usbTxStatus1\&.len"
.br
.ti -1c
.RI "#define \fBusbTxBuf1\fP   usbTxStatus1\&.buffer"
.br
.ti -1c
.RI "#define \fBusbTxLen3\fP   usbTxStatus3\&.len"
.br
.ti -1c
.RI "#define \fBusbTxBuf3\fP   usbTxStatus3\&.buffer"
.br
.ti -1c
.RI "#define \fBUSBRQ_RCPT_MASK\fP   0x1f"
.br
.ti -1c
.RI "#define \fBUSBRQ_RCPT_DEVICE\fP   0"
.br
.ti -1c
.RI "#define \fBUSBRQ_RCPT_INTERFACE\fP   1"
.br
.ti -1c
.RI "#define \fBUSBRQ_RCPT_ENDPOINT\fP   2"
.br
.ti -1c
.RI "#define \fBUSBRQ_TYPE_MASK\fP   0x60"
.br
.ti -1c
.RI "#define \fBUSBRQ_TYPE_STANDARD\fP   (0<<5)"
.br
.ti -1c
.RI "#define \fBUSBRQ_TYPE_CLASS\fP   (1<<5)"
.br
.ti -1c
.RI "#define \fBUSBRQ_TYPE_VENDOR\fP   (2<<5)"
.br
.ti -1c
.RI "#define \fBUSBRQ_DIR_MASK\fP   0x80"
.br
.ti -1c
.RI "#define \fBUSBRQ_DIR_HOST_TO_DEVICE\fP   (0<<7)"
.br
.ti -1c
.RI "#define \fBUSBRQ_DIR_DEVICE_TO_HOST\fP   (1<<7)"
.br
.ti -1c
.RI "#define \fBUSBRQ_GET_STATUS\fP   0"
.br
.ti -1c
.RI "#define \fBUSBRQ_CLEAR_FEATURE\fP   1"
.br
.ti -1c
.RI "#define \fBUSBRQ_SET_FEATURE\fP   3"
.br
.ti -1c
.RI "#define \fBUSBRQ_SET_ADDRESS\fP   5"
.br
.ti -1c
.RI "#define \fBUSBRQ_GET_DESCRIPTOR\fP   6"
.br
.ti -1c
.RI "#define \fBUSBRQ_SET_DESCRIPTOR\fP   7"
.br
.ti -1c
.RI "#define \fBUSBRQ_GET_CONFIGURATION\fP   8"
.br
.ti -1c
.RI "#define \fBUSBRQ_SET_CONFIGURATION\fP   9"
.br
.ti -1c
.RI "#define \fBUSBRQ_GET_INTERFACE\fP   10"
.br
.ti -1c
.RI "#define \fBUSBRQ_SET_INTERFACE\fP   11"
.br
.ti -1c
.RI "#define \fBUSBRQ_SYNCH_FRAME\fP   12"
.br
.ti -1c
.RI "#define \fBUSBDESCR_DEVICE\fP   1"
.br
.ti -1c
.RI "#define \fBUSBDESCR_CONFIG\fP   2"
.br
.ti -1c
.RI "#define \fBUSBDESCR_STRING\fP   3"
.br
.ti -1c
.RI "#define \fBUSBDESCR_INTERFACE\fP   4"
.br
.ti -1c
.RI "#define \fBUSBDESCR_ENDPOINT\fP   5"
.br
.ti -1c
.RI "#define \fBUSBDESCR_HID\fP   0x21"
.br
.ti -1c
.RI "#define \fBUSBDESCR_HID_REPORT\fP   0x22"
.br
.ti -1c
.RI "#define \fBUSBDESCR_HID_PHYS\fP   0x23"
.br
.ti -1c
.RI "#define \fBUSBATTR_SELFPOWER\fP   0x40"
.br
.ti -1c
.RI "#define \fBUSBATTR_REMOTEWAKE\fP   0x20"
.br
.ti -1c
.RI "#define \fBUSBRQ_HID_GET_REPORT\fP   0x01"
.br
.ti -1c
.RI "#define \fBUSBRQ_HID_GET_IDLE\fP   0x02"
.br
.ti -1c
.RI "#define \fBUSBRQ_HID_GET_PROTOCOL\fP   0x03"
.br
.ti -1c
.RI "#define \fBUSBRQ_HID_SET_REPORT\fP   0x09"
.br
.ti -1c
.RI "#define \fBUSBRQ_HID_SET_IDLE\fP   0x0a"
.br
.ti -1c
.RI "#define \fBUSBRQ_HID_SET_PROTOCOL\fP   0x0b"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBusbTxStatus\fP \fBusbTxStatus_t\fP"
.br
.ti -1c
.RI "typedef union \fBusbWord\fP \fBusbWord_t\fP"
.br
.ti -1c
.RI "typedef struct \fBusbRequest\fP \fBusbRequest_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUSB_PUBLIC\fP void \fBusbInit\fP (void)"
.br
.ti -1c
.RI "\fBUSB_PUBLIC\fP void \fBusbPoll\fP (void)"
.br
.ti -1c
.RI "\fBUSB_PUBLIC\fP \fBusbMsgLen_t\fP \fBusbFunctionSetup\fP (\fBuchar\fP \fBdata\fP[8])"
.br
.ti -1c
.RI "\fBUSB_PUBLIC\fP \fBusbMsgLen_t\fP \fBusbFunctionDescriptor\fP (struct \fBusbRequest\fP *rq)"
.br
.ti -1c
.RI "\fBUSB_PUBLIC\fP void \fBusbSetInterrupt\fP (\fBuchar\fP *\fBdata\fP, \fBuchar\fP len)"
.br
.ti -1c
.RI "unsigned \fBusbCrc16\fP (unsigned \fBdata\fP, \fBuchar\fP len)"
.br
.ti -1c
.RI "unsigned \fBusbCrc16Append\fP (unsigned \fBdata\fP, \fBuchar\fP len)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBuchar\fP * \fBusbMsgPtr\fP"
.br
.ti -1c
.RI "\fBuchar\fP \fBusbRxToken\fP"
.br
.ti -1c
.RI "\fBuchar\fP \fBusbConfiguration\fP"
.br
.ti -1c
.RI "\fBPROGMEM\fP char \fBusbDescriptorDevice\fP []"
.br
.ti -1c
.RI "\fBPROGMEM\fP char \fBusbDescriptorConfiguration\fP []"
.br
.ti -1c
.RI "\fBPROGMEM\fP char \fBusbDescriptorHidReport\fP []"
.br
.ti -1c
.RI "\fBPROGMEM\fP char \fBusbDescriptorString0\fP []"
.br
.ti -1c
.RI "\fBPROGMEM\fP int \fBusbDescriptorStringVendor\fP []"
.br
.ti -1c
.RI "\fBPROGMEM\fP int \fBusbDescriptorStringDevice\fP []"
.br
.ti -1c
.RI "\fBPROGMEM\fP int \fBusbDescriptorStringSerialNumber\fP []"
.br
.ti -1c
.RI "\fBusbTxStatus_t\fP \fBusbTxStatus1\fP"
.br
.ti -1c
.RI "\fBusbTxStatus_t\fP \fBusbTxStatus3\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define schar   signed char"

.PP
Definition at line 149 of file usbdrv\&.h\&.
.SS "#define uchar   unsigned char"

.PP
Definition at line 146 of file usbdrv\&.h\&.
.SS "#define USB_BUFSIZE   11  /* PID, 8 bytes \fBdata\fP, 2 bytes CRC */"

.PP
Definition at line 565 of file usbdrv\&.h\&.
.SS "#define USB_CFG_DESCR_PROPS_HID_REPORT   0"

.PP
Definition at line 439 of file usbdrv\&.h\&.
.SS "#define USB_CFG_IOPORT   \fBUSB_OUTPORT\fP(\fBUSB_CFG_IOPORTNAME\fP)"

.PP
Definition at line 552 of file usbdrv\&.h\&.
.SS "#define USB_CONCAT(a, b)   a ## b"

.PP
Definition at line 499 of file usbdrv\&.h\&.
.SS "#define USB_CONCAT_EXPANDED(a, b)   \fBUSB_CONCAT\fP(a, b)"

.PP
Definition at line 500 of file usbdrv\&.h\&.
.SS "#define USB_DDRPORT(name)   \fBUSB_CONCAT\fP(DDR, name)"

.PP
Definition at line 504 of file usbdrv\&.h\&.
.SS "#define USB_INITIAL_DATATOKEN   \fBUSBPID_DATA1\fP"

.PP
Definition at line 642 of file usbdrv\&.h\&.
.SS "#define USB_INPORT(name)   \fBUSB_CONCAT\fP(PIN, name)"

.PP
Definition at line 503 of file usbdrv\&.h\&.
.SS "#define USB_INTR_CFG   MCUCR"

.PP
Definition at line 573 of file usbdrv\&.h\&.
.SS "#define USB_INTR_CFG_CLR   0    /* no bits to clear */"

.PP
Definition at line 587 of file usbdrv\&.h\&.
.SS "#define USB_INTR_CFG_SET   (1 << ISC01)                    /* cfg for falling edge */"

.PP
Definition at line 578 of file usbdrv\&.h\&.
.SS "#define USB_INTR_ENABLE   GICR"

.PP
Definition at line 596 of file usbdrv\&.h\&.
.SS "#define USB_INTR_ENABLE_BIT   INT0"

.PP
Definition at line 600 of file usbdrv\&.h\&.
.SS "#define USB_INTR_PENDING   GIFR"

.PP
Definition at line 607 of file usbdrv\&.h\&.
.SS "#define USB_INTR_PENDING_BIT   INTF0"

.PP
Definition at line 611 of file usbdrv\&.h\&.
.SS "#define USB_NO_MSG   ((\fBusbMsgLen_t\fP)-1)   /* constant meaning 'no message' */"

.PP
Definition at line 164 of file usbdrv\&.h\&.
.SS "#define USB_OUTPORT(name)   \fBUSB_CONCAT\fP(PORT, name)"

.PP
Definition at line 502 of file usbdrv\&.h\&.
.SS "#define USB_PROP_IS_DYNAMIC   (1 << 14)"

.PP
Definition at line 393 of file usbdrv\&.h\&.
.SS "#define USB_PROP_IS_RAM   (1 << 15)"

.PP
Definition at line 399 of file usbdrv\&.h\&.
.SS "#define USB_PROP_LENGTH(len)   ((len) & 0x3fff)"

.PP
Definition at line 404 of file usbdrv\&.h\&.
.SS "#define USB_PUBLIC"

.PP
Definition at line 135 of file usbdrv\&.h\&.
.SS "#define USB_PULLUP_DDR   \fBUSB_DDRPORT\fP(USB_CFG_PULLUP_IOPORTNAME)"

.PP
Definition at line 544 of file usbdrv\&.h\&.
.SS "#define USB_PULLUP_OUT   \fBUSB_OUTPORT\fP(USB_CFG_PULLUP_IOPORTNAME)"

.PP
Definition at line 541 of file usbdrv\&.h\&.
.SS "#define USB_SET_DATATOKEN1(token)   \fBusbTxBuf1\fP[0] = token"

.PP
Definition at line 375 of file usbdrv\&.h\&.
.SS "#define USB_SET_DATATOKEN3(token)   \fBusbTxBuf3\fP[0] = token"

.PP
Definition at line 376 of file usbdrv\&.h\&.
.SS "#define USB_STRING_DESCRIPTOR_HEADER(stringLength)   ((2*(stringLength)+2) | (3<<8))"

.PP
Definition at line 353 of file usbdrv\&.h\&.
.SS "#define USBATTR_REMOTEWAKE   0x20"

.PP
Definition at line 723 of file usbdrv\&.h\&.
.SS "#define USBATTR_SELFPOWER   0x40"

.PP
Definition at line 722 of file usbdrv\&.h\&.
.SS "#define usbCrc16(\fBdata\fP, len)   usbCrc16((unsigned)(\fBdata\fP), len)"

.PP
Definition at line 310 of file usbdrv\&.h\&.
.SS "#define usbCrc16Append(\fBdata\fP, len)   usbCrc16Append((unsigned)(\fBdata\fP), len)"

.PP
Definition at line 318 of file usbdrv\&.h\&.
.SS "#define USBDDR   \fBUSB_DDRPORT\fP(\fBUSB_CFG_IOPORTNAME\fP)"

.PP
Definition at line 543 of file usbdrv\&.h\&.
.SS "#define USBDESCR_CONFIG   2"

.PP
Definition at line 713 of file usbdrv\&.h\&.
.SS "#define USBDESCR_DEVICE   1"

.PP
Definition at line 712 of file usbdrv\&.h\&.
.SS "#define USBDESCR_ENDPOINT   5"

.PP
Definition at line 716 of file usbdrv\&.h\&.
.SS "#define USBDESCR_HID   0x21"

.PP
Definition at line 717 of file usbdrv\&.h\&.
.SS "#define USBDESCR_HID_PHYS   0x23"

.PP
Definition at line 719 of file usbdrv\&.h\&.
.SS "#define USBDESCR_HID_REPORT   0x22"

.PP
Definition at line 718 of file usbdrv\&.h\&.
.SS "#define USBDESCR_INTERFACE   4"

.PP
Definition at line 715 of file usbdrv\&.h\&.
.SS "#define USBDESCR_STRING   3"

.PP
Definition at line 714 of file usbdrv\&.h\&.
.SS "#define usbDeviceConnect()   (\fBUSBDDR\fP &= ~(1<<\fBUSBMINUS\fP))"

.PP
Definition at line 294 of file usbdrv\&.h\&.
.SS "#define usbDeviceDisconnect()   (\fBUSBDDR\fP |= (1<<\fBUSBMINUS\fP))"

.PP
Definition at line 295 of file usbdrv\&.h\&.
.SS "#define USBDRV_VERSION   20100715"

.PP
Definition at line 125 of file usbdrv\&.h\&.
.SS "#define USBIDLE   (1<<\fBUSB_CFG_DMINUS_BIT\fP) /* value representing J state */"

.PP
Definition at line 548 of file usbdrv\&.h\&.
.SS "#define USBIN   \fBUSB_INPORT\fP(\fBUSB_CFG_IOPORTNAME\fP)"

.PP
Definition at line 542 of file usbdrv\&.h\&.
.SS "#define usbInterruptIsReady()   (\fBusbTxLen1\fP & 0x10)"

.PP
Definition at line 227 of file usbdrv\&.h\&.
.SS "#define USBMASK   ((1<<\fBUSB_CFG_DPLUS_BIT\fP) | (1<<\fBUSB_CFG_DMINUS_BIT\fP))  /* mask for USB I/O bits */"

.PP
Definition at line 549 of file usbdrv\&.h\&.
.SS "#define USBMINUS   \fBUSB_CFG_DMINUS_BIT\fP"

.PP
Definition at line 546 of file usbdrv\&.h\&.
.SS "#define usbMsgLen_t   \fBuchar\fP"

.PP
Definition at line 156 of file usbdrv\&.h\&.
.SS "#define USBOUT   \fBUSB_OUTPORT\fP(\fBUSB_CFG_IOPORTNAME\fP)"

.PP
Definition at line 540 of file usbdrv\&.h\&.
.SS "#define USBPID_ACK   0xd2"

.PP
Definition at line 637 of file usbdrv\&.h\&.
.SS "#define USBPID_DATA0   0xc3"

.PP
Definition at line 634 of file usbdrv\&.h\&.
.SS "#define USBPID_DATA1   0x4b"

.PP
Definition at line 635 of file usbdrv\&.h\&.
.SS "#define USBPID_IN   0x69"

.PP
Definition at line 633 of file usbdrv\&.h\&.
.SS "#define USBPID_NAK   0x5a"

.PP
Definition at line 638 of file usbdrv\&.h\&.
.SS "#define USBPID_OUT   0xe1"

.PP
Definition at line 632 of file usbdrv\&.h\&.
.SS "#define USBPID_SETUP   0x2d"

.PP
Definition at line 631 of file usbdrv\&.h\&.
.SS "#define USBPID_STALL   0x1e"

.PP
Definition at line 639 of file usbdrv\&.h\&.
.SS "#define USBPLUS   \fBUSB_CFG_DPLUS_BIT\fP"

.PP
Definition at line 547 of file usbdrv\&.h\&.
.SS "#define USBRQ_CLEAR_FEATURE   1"

.PP
Definition at line 700 of file usbdrv\&.h\&.
.SS "#define USBRQ_DIR_DEVICE_TO_HOST   (1<<7)"

.PP
Definition at line 696 of file usbdrv\&.h\&.
.SS "#define USBRQ_DIR_HOST_TO_DEVICE   (0<<7)"

.PP
Definition at line 695 of file usbdrv\&.h\&.
.SS "#define USBRQ_DIR_MASK   0x80"

.PP
Definition at line 694 of file usbdrv\&.h\&.
.SS "#define USBRQ_GET_CONFIGURATION   8"

.PP
Definition at line 705 of file usbdrv\&.h\&.
.SS "#define USBRQ_GET_DESCRIPTOR   6"

.PP
Definition at line 703 of file usbdrv\&.h\&.
.SS "#define USBRQ_GET_INTERFACE   10"

.PP
Definition at line 707 of file usbdrv\&.h\&.
.SS "#define USBRQ_GET_STATUS   0"

.PP
Definition at line 699 of file usbdrv\&.h\&.
.SS "#define USBRQ_HID_GET_IDLE   0x02"

.PP
Definition at line 727 of file usbdrv\&.h\&.
.SS "#define USBRQ_HID_GET_PROTOCOL   0x03"

.PP
Definition at line 728 of file usbdrv\&.h\&.
.SS "#define USBRQ_HID_GET_REPORT   0x01"

.PP
Definition at line 726 of file usbdrv\&.h\&.
.SS "#define USBRQ_HID_SET_IDLE   0x0a"

.PP
Definition at line 730 of file usbdrv\&.h\&.
.SS "#define USBRQ_HID_SET_PROTOCOL   0x0b"

.PP
Definition at line 731 of file usbdrv\&.h\&.
.SS "#define USBRQ_HID_SET_REPORT   0x09"

.PP
Definition at line 729 of file usbdrv\&.h\&.
.SS "#define USBRQ_RCPT_DEVICE   0"

.PP
Definition at line 683 of file usbdrv\&.h\&.
.SS "#define USBRQ_RCPT_ENDPOINT   2"

.PP
Definition at line 685 of file usbdrv\&.h\&.
.SS "#define USBRQ_RCPT_INTERFACE   1"

.PP
Definition at line 684 of file usbdrv\&.h\&.
.SS "#define USBRQ_RCPT_MASK   0x1f"

.PP
Definition at line 682 of file usbdrv\&.h\&.
.SS "#define USBRQ_SET_ADDRESS   5"

.PP
Definition at line 702 of file usbdrv\&.h\&.
.SS "#define USBRQ_SET_CONFIGURATION   9"

.PP
Definition at line 706 of file usbdrv\&.h\&.
.SS "#define USBRQ_SET_DESCRIPTOR   7"

.PP
Definition at line 704 of file usbdrv\&.h\&.
.SS "#define USBRQ_SET_FEATURE   3"

.PP
Definition at line 701 of file usbdrv\&.h\&.
.SS "#define USBRQ_SET_INTERFACE   11"

.PP
Definition at line 708 of file usbdrv\&.h\&.
.SS "#define USBRQ_SYNCH_FRAME   12"

.PP
Definition at line 709 of file usbdrv\&.h\&.
.SS "#define USBRQ_TYPE_CLASS   (1<<5)"

.PP
Definition at line 690 of file usbdrv\&.h\&.
.SS "#define USBRQ_TYPE_MASK   0x60"

.PP
Definition at line 688 of file usbdrv\&.h\&.
.SS "#define USBRQ_TYPE_STANDARD   (0<<5)"

.PP
Definition at line 689 of file usbdrv\&.h\&.
.SS "#define USBRQ_TYPE_VENDOR   (2<<5)"

.PP
Definition at line 691 of file usbdrv\&.h\&.
.SS "#define usbTxBuf1   usbTxStatus1\&.buffer"

.PP
Definition at line 654 of file usbdrv\&.h\&.
.SS "#define usbTxBuf3   usbTxStatus3\&.buffer"

.PP
Definition at line 656 of file usbdrv\&.h\&.
.SS "#define usbTxLen1   usbTxStatus1\&.len"

.PP
Definition at line 653 of file usbdrv\&.h\&.
.SS "#define usbTxLen3   usbTxStatus3\&.len"

.PP
Definition at line 655 of file usbdrv\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBusbRequest\fP \fBusbRequest_t\fP"

.SS "typedef struct \fBusbTxStatus\fP \fBusbTxStatus_t\fP"

.SS "typedef union \fBusbWord\fP \fBusbWord_t\fP"

.SH "Function Documentation"
.PP 
.SS "unsigned usbCrc16 (unsigneddata, \fBuchar\fPlen)"

.SS "unsigned usbCrc16Append (unsigneddata, \fBuchar\fPlen)"

.SS "\fBUSB_PUBLIC\fP \fBusbMsgLen_t\fP usbFunctionDescriptor (struct \fBusbRequest\fP *rq)"

.SS "\fBUSB_PUBLIC\fP \fBusbMsgLen_t\fP usbFunctionSetup (\fBuchar\fPdata[8])"

.SS "\fBUSB_PUBLIC\fP void usbInit (void)"

.PP
Definition at line 607 of file usbdrv\&.c\&.
.SS "\fBUSB_PUBLIC\fP void usbPoll (void)"

.PP
Definition at line 565 of file usbdrv\&.c\&.
.SS "\fBUSB_PUBLIC\fP void usbSetInterrupt (\fBuchar\fP *data, \fBuchar\fPlen)"

.PP
Definition at line 245 of file usbdrv\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBuchar\fP usbConfiguration"

.PP
Definition at line 28 of file usbdrv\&.c\&.
.SS "\fBPROGMEM\fP char usbDescriptorConfiguration[]"

.PP
Definition at line 142 of file usbdrv\&.c\&.
.SS "\fBPROGMEM\fP char usbDescriptorDevice[]"

.PP
Definition at line 111 of file usbdrv\&.c\&.
.SS "\fBPROGMEM\fP char usbDescriptorHidReport[]"

.SS "\fBPROGMEM\fP char usbDescriptorString0[]"

.PP
Definition at line 70 of file usbdrv\&.c\&.
.SS "\fBPROGMEM\fP int usbDescriptorStringDevice[]"

.PP
Definition at line 89 of file usbdrv\&.c\&.
.SS "\fBPROGMEM\fP int usbDescriptorStringSerialNumber[]"

.SS "\fBPROGMEM\fP int usbDescriptorStringVendor[]"

.PP
Definition at line 80 of file usbdrv\&.c\&.
.SS "\fBuchar\fP* usbMsgPtr"

.PP
Definition at line 48 of file usbdrv\&.c\&.
.SS "\fBuchar\fP usbRxToken"

.PP
Definition at line 31 of file usbdrv\&.c\&.
.SS "\fBusbTxStatus_t\fP usbTxStatus1"

.PP
Definition at line 38 of file usbdrv\&.c\&.
.SS "\fBusbTxStatus_t\fP usbTxStatus3"

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
