.TH "Arduino_ADK_USB_HOST/USB_HID_API/usbdrvasm128.inc" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/USB_HID_API/usbdrvasm128.inc \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBprintCmdBuffer\fP ($thisBit)"
.br
.ti -1c
.RI "\fBprintBit\fP ($isAfterSet, $bitNum)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$bitStartCycles\fP = array(1, 9, 17, 26, 34, 42, 51, 59)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "printBit ($isAfterSet, $bitNum)"

.PP
Definition at line 686 of file usbdrvasm128\&.inc\&.
.SS "printCmdBuffer ($thisBit)"

.PP
Definition at line 665 of file usbdrvasm128\&.inc\&.
.SH "Variable Documentation"
.PP 
.SS "$bitStartCycles = array(1, 9, 17, 26, 34, 42, 51, 59)"

.PP
Definition at line 731 of file usbdrvasm128\&.inc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
