.TH "Arduino_ADK_USB_HOST/USB_HID_API/usbportability.h" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino_ADK_USB_HOST/USB_HID_API/usbportability.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br
\fC#include <avr/pgmspace\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSB_READ_FLASH\fP(addr)   pgm_read_byte(addr)"
.br
.ti -1c
.RI "#define \fBmacro\fP   \&.macro"
.br
.ti -1c
.RI "#define \fBendm\fP   \&.endm"
.br
.ti -1c
.RI "#define \fBnop2\fP   rjmp    \&.+0 /* jump to next instruction */"
.br
.ti -1c
.RI "#define \fBPRG_RDB\fP(addr)   \fBUSB_READ_FLASH\fP(addr)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define endm   \&.endm"

.PP
Definition at line 135 of file usbportability\&.h\&.
.SS "#define macro   \&.macro"

.PP
Definition at line 134 of file usbportability\&.h\&.
.SS "#define nop2   rjmp    \&.+0 /* jump to next instruction */"

.PP
Definition at line 136 of file usbportability\&.h\&.
.SS "#define PRG_RDB(addr)   \fBUSB_READ_FLASH\fP(addr)"

.PP
Definition at line 142 of file usbportability\&.h\&.
.SS "#define USB_READ_FLASH(addr)   pgm_read_byte(addr)"

.PP
Definition at line 131 of file usbportability\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
