.TH "usbRequest" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usbRequest \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usbdrv\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuchar\fP \fBbmRequestType\fP"
.br
.ti -1c
.RI "\fBuchar\fP \fBbRequest\fP"
.br
.ti -1c
.RI "\fBusbWord_t\fP \fBwValue\fP"
.br
.ti -1c
.RI "\fBusbWord_t\fP \fBwIndex\fP"
.br
.ti -1c
.RI "\fBusbWord_t\fP \fBwLength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 664 of file usbdrv\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBuchar\fP usbRequest::bmRequestType"

.PP
Definition at line 665 of file usbdrv\&.h\&.
.SS "\fBuchar\fP usbRequest::bRequest"

.PP
Definition at line 666 of file usbdrv\&.h\&.
.SS "\fBusbWord_t\fP usbRequest::wIndex"

.PP
Definition at line 668 of file usbdrv\&.h\&.
.SS "\fBusbWord_t\fP usbRequest::wLength"

.PP
Definition at line 669 of file usbdrv\&.h\&.
.SS "\fBusbWord_t\fP usbRequest::wValue"

.PP
Definition at line 667 of file usbdrv\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
