.TH "usbTxStatus" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usbTxStatus \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usbdrv\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile \fBuchar\fP \fBlen\fP"
.br
.ti -1c
.RI "\fBuchar\fP \fBbuffer\fP [\fBUSB_BUFSIZE\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 647 of file usbdrv\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBuchar\fP usbTxStatus::buffer[\fBUSB_BUFSIZE\fP]"

.PP
Definition at line 649 of file usbdrv\&.h\&.
.SS "volatile \fBuchar\fP usbTxStatus::len"

.PP
Definition at line 648 of file usbdrv\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
