.TH "usbWord" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usbWord \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usbdrv\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBword\fP"
.br
.ti -1c
.RI "\fBuchar\fP \fBbytes\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 659 of file usbdrv\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBuchar\fP usbWord::bytes[2]"

.PP
Definition at line 661 of file usbdrv\&.h\&.
.SS "unsigned usbWord::word"

.PP
Definition at line 660 of file usbdrv\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
