.TH "WATCHDOG" 3 "Thu Aug 15 2013" "Version 1.0" "Arduino Medical Assitive Device Base Station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WATCHDOG \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Packet_Watchdog\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcheck_watchdog\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBreset\fP (void *arg, byte packet_id, byte packet_ver, void *packet_data)"
.br
.RI "\fIReset the timer, accessible publicly\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class implements the timeout packet receive watchdog, and also implements the check for the timing basis and checks\&. 
.PP
Definition at line 19 of file Packet_Watchdog\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void WATCHDOG::check_watchdog (void)"
Checks the watchdog varialbe
.PP
The check watchdog method\&. we have never seen a packet
.PP
Swap the bug character to 'where is the link' Doing this every iteration is a bit wasteful, but we only do this while there is nothing else to do\&.
.PP
we are not currently in an alarm condition
.PP
if we have just timed out, next time around the alarm will sound
.PP
XXX we should save the last GPS data here in \fBNVRAM\fP for lost-model recovery purposes\&.
.PP
we are currently in an alarm condition
.PP
is it time to sound the alarm beep again?
.PP
toggle the bug glyph between 'where is the link' and 'hey you!' 
.PP
Definition at line 18 of file Packet_Watchdog\&.cpp\&.
.SS "void WATCHDOG::reset (void *arg, bytepacket_id, bytepacket_ver, void *packet_data)\fC [static]\fP"

.PP
Reset the timer, accessible publicly\&. The publicly accessible method to reset the watchdog\&. 
.PP
\fBParameters:\fP
.RS 4
\fIarg\fP - void* 
.br
\fIpacket_id\fP - byte 
.br
\fIpacket_ver\fP byte 
.br
\fIpacket_data\fP - void* 
.RE
.PP

.PP
Definition at line 11 of file Packet_Watchdog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arduino Medical Assitive Device Base Station from the source code\&.
