.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/bsp/boards/CC430EM/ Directory Reference" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/bsp/boards/CC430EM/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbsp_external\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbsp_board\&.c\fP"
.br
.ti -1c
.RI "file \fBbsp_board_defs\&.h\fP"
.br
.ti -1c
.RI "file \fBbsp_button_defs\&.h\fP"
.br
.ti -1c
.RI "file \fBbsp_config\&.h\fP"
.br
.ti -1c
.RI "file \fBbsp_driver_defs\&.h\fP"
.br
.ti -1c
.RI "file \fBbsp_drivers\&.c\fP"
.br
.ti -1c
.RI "file \fBbsp_led_defs\&.h\fP"
.br
.in -1c
