.TH "agil" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
agil \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'agility\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBstate\fP"
.br
.ti -1c
.RI "u8 \fBxyz\fP [3]"
.br
.ti -1c
.RI "s16 \fBCurrentData\fP [3]"
.br
.ti -1c
.RI "s16 \fBPreviousData\fP [3]"
.br
.ti -1c
.RI "u32 \fBAgilityIndicator\fP"
.br
.ti -1c
.RI "u32 \fBScaleFactor\fP"
.br
.ti -1c
.RI "u32 \fBHistory\fP [16]"
.br
.ti -1c
.RI "u8 \fBHistoryIndex\fP"
.br
.ti -1c
.RI "u32 \fBtimeout\fP"
.br
.ti -1c
.RI "u32 \fBTimeoutSetting\fP"
.br
.ti -1c
.RI "u8 \fBcycles\fP"
.br
.ti -1c
.RI "u8 \fBCycleSetting\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 69 of file agility\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u32 \fBAgilityIndicator\fP"
.PP
Definition at line 82 of file agility\&.h\&.
.SS "s16 \fBCurrentData\fP[3]"
.PP
Definition at line 78 of file agility\&.h\&.
.SS "u8 \fBcycles\fP"
.PP
Definition at line 96 of file agility\&.h\&.
.SS "u8 \fBCycleSetting\fP"
.PP
Definition at line 97 of file agility\&.h\&.
.SS "u32 \fBHistory\fP[16]"
.PP
Definition at line 88 of file agility\&.h\&.
.SS "u8 \fBHistoryIndex\fP"
.PP
Definition at line 89 of file agility\&.h\&.
.SS "s16 \fBPreviousData\fP[3]"
.PP
Definition at line 79 of file agility\&.h\&.
.SS "u32 \fBScaleFactor\fP"
.PP
Definition at line 85 of file agility\&.h\&.
.SS "u8 \fBstate\fP"
.PP
Definition at line 72 of file agility\&.h\&.
.SS "u32 \fBtimeout\fP"
.PP
Definition at line 92 of file agility\&.h\&.
.SS "u32 \fBTimeoutSetting\fP"
.PP
Definition at line 93 of file agility\&.h\&.
.SS "u8 \fBxyz\fP[3]"
.PP
Definition at line 75 of file agility\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
