.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/agility.h" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/agility.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBagil\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBAGIL_STOP\fP   (0u)"
.br
.ti -1c
.RI "#define \fBAGIL_RUN\fP   (1u)"
.br
.ti -1c
.RI "#define \fBSECONDS_OF_ONE_HOUR\fP   (60ul*60ul)"
.br
.ti -1c
.RI "#define \fBAGIL_MEASUREMENT_TIMEOUT_DEFAULT\fP   (1ul*SECONDS_OF_ONE_HOUR)"
.br
.ti -1c
.RI "#define \fBAGIL_MEASUREMENT_CYCLES_DEFAULT\fP   1"
.br
.ti -1c
.RI "#define \fBAGIL_HISTORY_MAX\fP   16"
.br
.ti -1c
.RI "#define \fBAGIL_SCALE_DEFAULT\fP   10"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreset_agility\fP (void)"
.br
.ti -1c
.RI "void \fBmx_agility\fP (u8 line)"
.br
.ti -1c
.RI "void \fBsx_agility\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_agility\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBagility_tick\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBagil\fP \fBsAgil\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBAGIL_HISTORY_MAX\fP   16"
.PP
Definition at line 62 of file agility\&.h\&.
.SS "#define \fBAGIL_MEASUREMENT_CYCLES_DEFAULT\fP   1"
.PP
Definition at line 60 of file agility\&.h\&.
.SS "#define \fBAGIL_MEASUREMENT_TIMEOUT_DEFAULT\fP   (1ul*SECONDS_OF_ONE_HOUR)"
.PP
Definition at line 58 of file agility\&.h\&.
.SS "#define \fBAGIL_RUN\fP   (1u)"
.PP
Definition at line 54 of file agility\&.h\&.
.SS "#define \fBAGIL_SCALE_DEFAULT\fP   10"
.PP
Definition at line 64 of file agility\&.h\&.
.SS "#define \fBAGIL_STOP\fP   (0u)"
.PP
Definition at line 53 of file agility\&.h\&.
.SS "#define \fBSECONDS_OF_ONE_HOUR\fP   (60ul*60ul)"
.PP
Definition at line 57 of file agility\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBagility_tick\fP (void)"
.PP
Definition at line 123 of file agility\&.c\&.
.SS "void \fBdisplay_agility\fP (u8line, u8update)"
.PP
Definition at line 333 of file agility\&.c\&.
.SS "void \fBmx_agility\fP (u8line)"
.PP
Definition at line 279 of file agility\&.c\&.
.SS "void \fBreset_agility\fP (void)"
.PP
Definition at line 181 of file agility\&.c\&.
.SS "void \fBsx_agility\fP (u8line)"
.PP
Definition at line 306 of file agility\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBagil\fP \fBsAgil\fP"
.PP
Definition at line 75 of file agility\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
