.TH "alt" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
alt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'altitude\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmenu_t\fP \fBstate\fP"
.br
.ti -1c
.RI "u32 \fBpressure\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBtemperature\fP"
.br
.ti -1c
.RI "s16 \fBaltitude\fP"
.br
.ti -1c
.RI "s16 \fBaltitude_offset\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBtimeout\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 67 of file altitude\&.h\&.
.SH "Field Documentation"
.PP 
.SS "s16 \fBaltitude\fP"
.PP
Definition at line 79 of file altitude\&.h\&.
.SS "s16 \fBaltitude_offset\fP"
.PP
Definition at line 82 of file altitude\&.h\&.
.SS "u32 \fBpressure\fP"
.PP
Definition at line 73 of file altitude\&.h\&.
.SS "\fBmenu_t\fP \fBstate\fP"
.PP
Definition at line 70 of file altitude\&.h\&.
.SS "\fBu16\fP \fBtemperature\fP"
.PP
Definition at line 76 of file altitude\&.h\&.
.SS "\fBu16\fP \fBtimeout\fP"
.PP
Definition at line 85 of file altitude\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
