.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/bluerobin/bm.h" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/bluerobin/bm.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <float\&.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBFALSE\fP   (0 == 1)"
.br
.ti -1c
.RI "#define \fBTRUE\fP   (1 == 1)"
.br
.ti -1c
.RI "#define \fBUSE_RAW_ATTR\fP   \fBFALSE\fP"
.br
.ti -1c
.RI "#define \fB_TI_MSP430_\fP   (16)"
.br
.ti -1c
.RI "#define \fBBITSIZEOF\fP(type)   (sizeof(type) * CHAR_BIT)"
.br
.ti -1c
.RI "#define \fBBIT\fP(x)   (1uL << (x))"
.br
.ti -1c
.RI "#define \fBBIT_T\fP(t, x)   ((t)((t)1 << (x)))"
.br
.ti -1c
.RI "#define \fBBIT_HIGHEST\fP(Input_u32)"
.br
.ti -1c
.RI "#define \fBMONITOR\fP"
.br
.ti -1c
.RI "#define \fBNO_INIT\fP"
.br
.ti -1c
.RI "#define \fBINTERRUPT\fP"
.br
.ti -1c
.RI "#define \fBISR\fP(ignore)"
.br
.ti -1c
.RI "#define \fBINLINE_FUNC\fP"
.br
.ti -1c
.RI "#define \fBINTERRUPTS_ENABLE\fP()"
.br
.ti -1c
.RI "#define \fBINTERRUPTS_DISABLE\fP()"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBBYTE\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBWORD\fP"
.br
.ti -1c
.RI "typedef unsigned long \fBDWORD\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fB_TI_MSP430_\fP   (16)"
.PP
Definition at line 65 of file bm\&.h\&.
.SS "#define \fBBIT\fP(x)   (1uL << (x))"
.PP
Definition at line 366 of file bm\&.h\&.
.SS "#define \fBBIT_HIGHEST\fP(Input_u32)"
.PP
Definition at line 381 of file bm\&.h\&.
.SS "#define \fBBIT_T\fP(t, x)   ((t)((t)1 << (x)))"
.PP
Definition at line 375 of file bm\&.h\&.
.SS "#define \fBBITSIZEOF\fP(type)   (sizeof(type) * CHAR_BIT)"
.PP
Definition at line 358 of file bm\&.h\&.
.SS "#define \fBFALSE\fP   (0 == 1)"
.PP
Definition at line 44 of file bm\&.h\&.
.SS "#define \fBINLINE_FUNC\fP"
.PP
Definition at line 433 of file bm\&.h\&.
.SS "#define \fBINTERRUPT\fP"
.PP
Definition at line 425 of file bm\&.h\&.
.SS "#define \fBINTERRUPTS_DISABLE\fP()"
.PP
Definition at line 441 of file bm\&.h\&.
.SS "#define \fBINTERRUPTS_ENABLE\fP()"
.PP
Definition at line 437 of file bm\&.h\&.
.SS "#define \fBISR\fP(ignore)"
.PP
Definition at line 429 of file bm\&.h\&.
.SS "#define \fBMONITOR\fP"
.PP
Definition at line 417 of file bm\&.h\&.
.SS "#define \fBNO_INIT\fP"
.PP
Definition at line 421 of file bm\&.h\&.
.SS "#define \fBTRUE\fP   (1 == 1)"
.PP
Definition at line 49 of file bm\&.h\&.
.SS "#define \fBUSE_RAW_ATTR\fP   \fBFALSE\fP"
.PP
Definition at line 54 of file bm\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned char \fBBYTE\fP"
.PP
Definition at line 350 of file bm\&.h\&.
.SS "typedef unsigned long \fBDWORD\fP"
.PP
Definition at line 352 of file bm\&.h\&.
.SS "typedef unsigned int \fBWORD\fP"
.PP
Definition at line 351 of file bm\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
