.TH "br" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
br \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'bluerobin\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBlueRobin_state_t\fP \fBstate\fP"
.br
.ti -1c
.RI "\fBBlueRobin_update_t\fP \fBupdate\fP"
.br
.ti -1c
.RI "u32 \fBcs_id\fP"
.br
.ti -1c
.RI "u8 \fBuser_sex\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBuser_weight\fP"
.br
.ti -1c
.RI "u8 \fBheartrate\fP"
.br
.ti -1c
.RI "u32 \fBcalories\fP"
.br
.ti -1c
.RI "u8 \fBspeed\fP"
.br
.ti -1c
.RI "u32 \fBdistance\fP"
.br
.ti -1c
.RI "u8 \fBcaldist_view\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 91 of file bluerobin\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u8 \fBcaldist_view\fP"
.PP
Definition at line 119 of file bluerobin\&.h\&.
.SS "u32 \fBcalories\fP"
.PP
Definition at line 110 of file bluerobin\&.h\&.
.SS "u32 \fBcs_id\fP"
.PP
Definition at line 100 of file bluerobin\&.h\&.
.SS "u32 \fBdistance\fP"
.PP
Definition at line 116 of file bluerobin\&.h\&.
.SS "u8 \fBheartrate\fP"
.PP
Definition at line 107 of file bluerobin\&.h\&.
.SS "u8 \fBspeed\fP"
.PP
Definition at line 113 of file bluerobin\&.h\&.
.SS "\fBBlueRobin_state_t\fP \fBstate\fP"
.PP
Definition at line 94 of file bluerobin\&.h\&.
.SS "\fBBlueRobin_update_t\fP \fBupdate\fP"
.PP
Definition at line 97 of file bluerobin\&.h\&.
.SS "u8 \fBuser_sex\fP"
.PP
Definition at line 103 of file bluerobin\&.h\&.
.SS "\fBu16\fP \fBuser_weight\fP"
.PP
Definition at line 104 of file bluerobin\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
