.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/bsp/bsp.c" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/bsp/bsp.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bsp\&.h'\fP
.br
\fC#include 'bsp_driver_defs\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBSP_Init\fP (void)"
.br
.ti -1c
.RI "void \fBbspDummyPrototype\fP (char \fBdummy\fP[1/((sizeof(\fBuint8_t\fP)==1)!=0)])"
.br
.ti -1c
.RI "void \fBbspDummyPrototype\fP (char \fBdummy\fP[1/((sizeof(\fBint8_t\fP)==1)!=0)])"
.br
.ti -1c
.RI "void \fBbspDummyPrototype\fP (char \fBdummy\fP[1/((sizeof(\fBuint16_t\fP)==2)!=0)])"
.br
.ti -1c
.RI "void \fBbspDummyPrototype\fP (char \fBdummy\fP[1/((sizeof(\fBint16_t\fP)==2)!=0)])"
.br
.ti -1c
.RI "void \fBbspDummyPrototype\fP (char \fBdummy\fP[1/((sizeof(\fBuint32_t\fP)==4)!=0)])"
.br
.ti -1c
.RI "void \fBbspDummyPrototype\fP (char \fBdummy\fP[1/((sizeof(\fBint32_t\fP)==4)!=0)])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBBSP_Init\fP (void)"
.PP
Definition at line 56 of file bsp\&.c\&.
.SS "void \fBbspDummyPrototype\fP (chardummy[1/((sizeof(uint8_t)==1)!=0)])"
.SS "void \fBbspDummyPrototype\fP (chardummy[1/((sizeof(int8_t)==1)!=0)])"
.SS "void \fBbspDummyPrototype\fP (chardummy[1/((sizeof(uint16_t)==2)!=0)])"
.SS "void \fBbspDummyPrototype\fP (chardummy[1/((sizeof(int16_t)==2)!=0)])"
.SS "void \fBbspDummyPrototype\fP (chardummy[1/((sizeof(uint32_t)==4)!=0)])"
.SS "void \fBbspDummyPrototype\fP (chardummy[1/((sizeof(int32_t)==4)!=0)])"
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
