.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/bsp/boards/CC430EM/bsp_board_defs.h" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/bsp/boards/CC430EM/bsp_board_defs.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mcus/bsp_msp430_defs\&.h'\fP
.br
\fC#include 'bsp_config\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBSP_BOARD_CC430EM\fP"
.br
.ti -1c
.RI "#define \fB__bsp_CLOCK_MHZ__\fP   BSP_CONFIG_CLOCK_MHZ"
.br
.ti -1c
.RI "#define \fBBSP_BOARD_C\fP   'bsp_board\&.c'"
.br
.ti -1c
.RI "#define \fBBSP_INIT_BOARD\fP()   \fBBSP_InitBoard\fP()"
.br
.ti -1c
.RI "#define \fBBSP_DELAY_USECS\fP(x)   \fBBSP_Delay\fP(x)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBSP_InitBoard\fP (void)"
.br
.ti -1c
.RI "void \fBBSP_Delay\fP (\fBuint16_t\fP usec)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fB__bsp_CLOCK_MHZ__\fP   BSP_CONFIG_CLOCK_MHZ"
.PP
Definition at line 62 of file bsp_board_defs\&.h\&.
.SS "#define \fBBSP_BOARD_C\fP   'bsp_board\&.c'"
.PP
Definition at line 69 of file bsp_board_defs\&.h\&.
.SS "#define \fBBSP_BOARD_CC430EM\fP"
.PP
Definition at line 47 of file bsp_board_defs\&.h\&.
.SS "#define \fBBSP_DELAY_USECS\fP(x)   \fBBSP_Delay\fP(x)"
.PP
Definition at line 71 of file bsp_board_defs\&.h\&.
.SS "#define \fBBSP_INIT_BOARD\fP()   \fBBSP_InitBoard\fP()"
.PP
Definition at line 70 of file bsp_board_defs\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBBSP_Delay\fP (\fBuint16_t\fPusec)"
.PP
Definition at line 263 of file bsp_board\&.c\&.
.SS "void \fBBSP_InitBoard\fP (void)"
.PP
Definition at line 234 of file bsp_board\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
