.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/bsp/boards/CC430EM/bsp_board.c" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/bsp/boards/CC430EM/bsp_board.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bsp\&.h'\fP
.br
\fC#include 'bsp_config\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBSP_TIMER_CLK_MHZ\fP   12       /* 12 MHz MCLKC and SMCLK */"
.br
.ti -1c
.RI "#define \fBBSP_DELAY_MAX_USEC\fP   (0xFFFF/BSP_TIMER_CLK_MHZ)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBSetVCore\fP (\fBuint8_t\fP level)"
.br
.ti -1c
.RI "static void \fBSetVCoreUp\fP (\fBuint8_t\fP level)"
.br
.ti -1c
.RI "static void \fBSetVCoreDown\fP (\fBuint8_t\fP level)"
.br
.ti -1c
.RI "static void \fBBsp_SetVCore\fP (void)"
.br
.ti -1c
.RI "static void \fBBsp_SetClocks\fP (void)"
.br
.ti -1c
.RI "\fBBSP_EARLY_INIT\fP (void)"
.br
.ti -1c
.RI "void \fBBSP_InitBoard\fP (void)"
.br
.ti -1c
.RI "void \fBBSP_Delay\fP (\fBuint16_t\fP usec)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBBSP_DELAY_MAX_USEC\fP   (0xFFFF/BSP_TIMER_CLK_MHZ)"
.PP
Definition at line 62 of file bsp_board\&.c\&.
.SS "#define \fBBSP_TIMER_CLK_MHZ\fP   12       /* 12 MHz MCLKC and SMCLK */"
.PP
Definition at line 61 of file bsp_board\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void \fBBSP_Delay\fP (\fBuint16_t\fPusec)"
.PP
Definition at line 263 of file bsp_board\&.c\&.
.SS "\fBBSP_EARLY_INIT\fP (void)"
.PP
Definition at line 209 of file bsp_board\&.c\&.
.SS "void \fBBSP_InitBoard\fP (void)"
.PP
Definition at line 234 of file bsp_board\&.c\&.
.SS "static void \fBBsp_SetClocks\fP (void)\fC [static]\fP"
.PP
Definition at line 157 of file bsp_board\&.c\&.
.SS "static void \fBBsp_SetVCore\fP (void)\fC [static]\fP"
.PP
Definition at line 142 of file bsp_board\&.c\&.
.SS "static void \fBSetVCore\fP (\fBuint8_t\fPlevel)\fC [static]\fP"
.SS "static void \fBSetVCoreDown\fP (\fBuint8_t\fPlevel)\fC [static]\fP"
.SS "static void \fBSetVCoreUp\fP (\fBuint8_t\fPlevel)\fC [static]\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
