.TH "buzzer" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
buzzer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'buzzer\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBtime\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBon_time\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBoff_time\fP"
.br
.ti -1c
.RI "u8 \fBstate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file buzzer\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBu16\fP \fBoff_time\fP"
.PP
Definition at line 86 of file buzzer\&.h\&.
.SS "\fBu16\fP \fBon_time\fP"
.PP
Definition at line 85 of file buzzer\&.h\&.
.SS "u8 \fBstate\fP"
.PP
Definition at line 89 of file buzzer\&.h\&.
.SS "u8 \fBtime\fP"
.PP
Definition at line 82 of file buzzer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
