.TH "connInfo_t" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
connInfo_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'nwk\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile \fBuint8_t\fP \fBconnState\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBhops2target\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBpeerAddr\fP [\fBNET_ADDR_SIZE\fP]"
.br
.ti -1c
.RI "\fBrxMetrics_t\fP \fBsigInfo\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBportRx\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBportTx\fP"
.br
.ti -1c
.RI "\fBlinkID_t\fP \fBthisLinkID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file nwk\&.h\&.
.SH "Field Documentation"
.PP 
.SS "volatile \fBuint8_t\fP \fBconnState\fP"
.PP
Definition at line 85 of file nwk\&.h\&.
.SS "\fBuint8_t\fP \fBhops2target\fP"
.PP
Definition at line 86 of file nwk\&.h\&.
.SS "\fBuint8_t\fP \fBpeerAddr\fP[\fBNET_ADDR_SIZE\fP]"
.PP
Definition at line 90 of file nwk\&.h\&.
.SS "\fBuint8_t\fP \fBportRx\fP"
.PP
Definition at line 92 of file nwk\&.h\&.
.SS "\fBuint8_t\fP \fBportTx\fP"
.PP
Definition at line 93 of file nwk\&.h\&.
.SS "\fBrxMetrics_t\fP \fBsigInfo\fP"
.PP
Definition at line 91 of file nwk\&.h\&.
.SS "\fBlinkID_t\fP \fBthisLinkID\fP"
.PP
Definition at line 94 of file nwk\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
