.TH "frameInfo_t" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frameInfo_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'nwk_frame\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile \fBuint8_t\fP \fBfi_usage\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBorderStamp\fP"
.br
.ti -1c
.RI "\fBmrfiPacket_t\fP \fBmrfiPkt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 121 of file nwk_frame\&.h\&.
.SH "Field Documentation"
.PP 
.SS "volatile \fBuint8_t\fP \fBfi_usage\fP"
.PP
Definition at line 123 of file nwk_frame\&.h\&.
.SS "\fBmrfiPacket_t\fP \fBmrfiPkt\fP"
.PP
Definition at line 125 of file nwk_frame\&.h\&.
.SS "\fBuint8_t\fP \fBorderStamp\fP"
.PP
Definition at line 124 of file nwk_frame\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
