.TH "ioctlNVObj_t" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ioctlNVObj_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'nwk_types\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBobjVersion\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBobjLen\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP ** \fBobjPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 210 of file nwk_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint16_t\fP \fBobjLen\fP"
.PP
Definition at line 213 of file nwk_types\&.h\&.
.SS "\fBuint8_t\fP** \fBobjPtr\fP"
.PP
Definition at line 214 of file nwk_types\&.h\&.
.SS "\fBuint8_t\fP \fBobjVersion\fP"
.PP
Definition at line 212 of file nwk_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
