.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/miscellaneous.h" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/miscellaneous.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBUcsResetHandling\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBUCSRESET_NO\fP   0"
.br
.ti -1c
.RI "#define \fBUCSRESET_YES\fP   1"
.br
.ti -1c
.RI "#define \fBUCSRESET_AUTO\fP   2"
.br
.ti -1c
.RI "#define \fBUCSRESET_MAN\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreset_number_storage\fP (void)"
.br
.ti -1c
.RI "void \fBmx_number_storage\fP (u8 line)"
.br
.ti -1c
.RI "void \fBsx_number_storage\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_number_storage\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBmx_sync\fP (u8 line)"
.br
.ti -1c
.RI "void \fBreset_ucs_reset_handler\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBUcsResetHandling\fP \fBsUcsResetHandling\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBUCSRESET_AUTO\fP   2"
.PP
Definition at line 59 of file miscellaneous\&.h\&.
.SS "#define \fBUCSRESET_MAN\fP   3"
.PP
Definition at line 60 of file miscellaneous\&.h\&.
.SS "#define \fBUCSRESET_NO\fP   0"
.PP
Definition at line 57 of file miscellaneous\&.h\&.
.SS "#define \fBUCSRESET_YES\fP   1"
.PP
Definition at line 58 of file miscellaneous\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBdisplay_number_storage\fP (u8line, u8update)"
.PP
Definition at line 263 of file miscellaneous\&.c\&.
.SS "void \fBmx_number_storage\fP (u8line)"
.PP
Definition at line 178 of file miscellaneous\&.c\&.
.SS "void \fBmx_sync\fP (u8line)"
.PP
Definition at line 382 of file miscellaneous\&.c\&.
.SS "void \fBreset_number_storage\fP (void)"
.PP
Definition at line 121 of file miscellaneous\&.c\&.
.SS "void \fBreset_ucs_reset_handler\fP (void)"
.PP
Definition at line 368 of file miscellaneous\&.c\&.
.SS "void \fBsx_number_storage\fP (u8line)"
.PP
Definition at line 158 of file miscellaneous\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBUcsResetHandling\fP \fBsUcsResetHandling\fP"
.PP
Definition at line 103 of file miscellaneous\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
