.TH "mrfiPacket_t" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mrfiPacket_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'mrfi\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBframe\fP [(__mrfi_MAX_PAYLOAD_SIZE__+__mrfi_FRAME_OVERHEAD_SIZE__)]"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBrxMetrics\fP [__mrfi_RX_METRICS_SIZE__]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 142 of file mrfi\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint8_t\fP \fBframe\fP[(__mrfi_MAX_PAYLOAD_SIZE__+__mrfi_FRAME_OVERHEAD_SIZE__)]"
.PP
Definition at line 144 of file mrfi\&.h\&.
.SS "\fBuint8_t\fP \fBrxMetrics\fP[__mrfi_RX_METRICS_SIZE__]"
.PP
Definition at line 145 of file mrfi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
