.TH "numstore" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
numstore \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBState\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBMem\fP [11]"
.br
.ti -1c
.RI "u8 \fBIndex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 105 of file miscellaneous\&.c\&.
.SH "Field Documentation"
.PP 
.SS "u8 \fBIndex\fP"
.PP
Definition at line 109 of file miscellaneous\&.c\&.
.SS "\fBu16\fP \fBMem\fP[11]"
.PP
Definition at line 108 of file miscellaneous\&.c\&.
.SS "u8 \fBState\fP"
.PP
Definition at line 107 of file miscellaneous\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
