.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/nwk_applications/nwk_ping.h" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/nwk_applications/nwk_ping.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAX_PING_APP_FRAME\fP   2"
.br
.ti -1c
.RI "#define \fBPB_REQ_OS\fP   0"
.br
.ti -1c
.RI "#define \fBPB_TID_OS\fP   1"
.br
.ti -1c
.RI "#define \fBPING_REQ_PING\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfhStatus_t\fP \fBnwk_processPing\fP (\fBmrfiPacket_t\fP *)"
.br
.ti -1c
.RI "void \fBnwk_pingInit\fP (void)"
.br
.ti -1c
.RI "\fBsmplStatus_t\fP \fBnwk_ping\fP (\fBlinkID_t\fP)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBMAX_PING_APP_FRAME\fP   2"
.PP
Definition at line 41 of file nwk_ping\&.h\&.
.SS "#define \fBPB_REQ_OS\fP   0"
.PP
Definition at line 45 of file nwk_ping\&.h\&.
.SS "#define \fBPB_TID_OS\fP   1"
.PP
Definition at line 46 of file nwk_ping\&.h\&.
.SS "#define \fBPING_REQ_PING\fP   1"
.PP
Definition at line 50 of file nwk_ping\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBsmplStatus_t\fP \fBnwk_ping\fP (\fBlinkID_t\fP)"
.PP
Definition at line 118 of file nwk_ping\&.c\&.
.SS "void \fBnwk_pingInit\fP (void)"
.PP
Definition at line 95 of file nwk_ping\&.c\&.
.SS "\fBfhStatus_t\fP \fBnwk_processPing\fP (\fBmrfiPacket_t\fP *)"
.PP
Definition at line 252 of file nwk_ping\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
