.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/nwk/nwk_api.c" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/nwk/nwk_api.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'bsp\&.h'\fP
.br
\fC#include 'mrfi\&.h'\fP
.br
\fC#include 'nwk_types\&.h'\fP
.br
\fC#include 'nwk_api\&.h'\fP
.br
\fC#include 'nwk_frame\&.h'\fP
.br
\fC#include 'nwk\&.h'\fP
.br
\fC#include 'nwk_app\&.h'\fP
.br
\fC#include 'nwk_globals\&.h'\fP
.br
\fC#include 'nwk_freq\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLINKLISTEN_MILLISECONDS_2_WAIT\fP   (5000)"
.br
.ti -1c
.RI "#define \fBLINKLISTEN_POLL_PERIOD_MS\fP   (10)"
.br
.ti -1c
.RI "#define \fBLINKLISTEN_POLL_COUNT\fP   ( (\fBLINKLISTEN_MILLISECONDS_2_WAIT\fP) / (\fBLINKLISTEN_POLL_PERIOD_MS\fP) )"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static \fBuint8_t\fP \fBioctlPreInitAccessIsOK\fP (\fBioctlObject_t\fP)"
.br
.ti -1c
.RI "\fBsmplStatus_t\fP \fBSMPL_Init\fP (\fBuint8_t\fP(*f)(\fBlinkID_t\fP))"
.br
.ti -1c
.RI "\fBsmplStatus_t\fP \fBSMPL_LinkListen\fP (\fBlinkID_t\fP *linkID)"
.br
.ti -1c
.RI "\fBsmplStatus_t\fP \fBSMPL_Send\fP (\fBlinkID_t\fP lid, \fBuint8_t\fP *msg, \fBuint8_t\fP len)"
.br
.ti -1c
.RI "\fBsmplStatus_t\fP \fBSMPL_SendOpt\fP (\fBlinkID_t\fP lid, \fBuint8_t\fP *msg, \fBuint8_t\fP len, \fBtxOpt_t\fP options)"
.br
.ti -1c
.RI "\fBsmplStatus_t\fP \fBSMPL_Receive\fP (\fBlinkID_t\fP lid, \fBuint8_t\fP *msg, \fBuint8_t\fP *len)"
.br
.ti -1c
.RI "\fBsmplStatus_t\fP \fBSMPL_Link\fP (\fBlinkID_t\fP *lid)"
.br
.ti -1c
.RI "\fBsmplStatus_t\fP \fBSMPL_Ioctl\fP (\fBioctlObject_t\fP object, \fBioctlAction_t\fP action, void *val)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBsInit_done\fP = 0"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBLINKLISTEN_MILLISECONDS_2_WAIT\fP   (5000)"
.PP
Definition at line 70 of file nwk_api\&.c\&.
.SS "#define \fBLINKLISTEN_POLL_COUNT\fP   ( (\fBLINKLISTEN_MILLISECONDS_2_WAIT\fP) / (\fBLINKLISTEN_POLL_PERIOD_MS\fP) )"
.PP
Definition at line 73 of file nwk_api\&.c\&.
.SS "#define \fBLINKLISTEN_POLL_PERIOD_MS\fP   (10)"
.PP
Definition at line 72 of file nwk_api\&.c\&.
.SH "Function Documentation"
.PP 
.SS "static \fBuint8_t\fP \fBioctlPreInitAccessIsOK\fP (\fBioctlObject_t\fPobject)\fC [static]\fP"
.PP
Definition at line 838 of file nwk_api\&.c\&.
.SS "\fBsmplStatus_t\fP \fBSMPL_Init\fP (\fBuint8_t\fP(*)(\fBlinkID_t\fP)f)"
.PP
Definition at line 120 of file nwk_api\&.c\&.
.SS "\fBsmplStatus_t\fP \fBSMPL_Ioctl\fP (\fBioctlObject_t\fPobject, \fBioctlAction_t\fPaction, void *val)"
.PP
Definition at line 684 of file nwk_api\&.c\&.
.SS "\fBsmplStatus_t\fP \fBSMPL_Link\fP (\fBlinkID_t\fP *lid)"
.PP
Definition at line 532 of file nwk_api\&.c\&.
.SS "\fBsmplStatus_t\fP \fBSMPL_LinkListen\fP (\fBlinkID_t\fP *linkID)"
.PP
Definition at line 182 of file nwk_api\&.c\&.
.SS "\fBsmplStatus_t\fP \fBSMPL_Receive\fP (\fBlinkID_t\fPlid, \fBuint8_t\fP *msg, \fBuint8_t\fP *len)"
.PP
Definition at line 428 of file nwk_api\&.c\&.
.SS "\fBsmplStatus_t\fP \fBSMPL_Send\fP (\fBlinkID_t\fPlid, \fBuint8_t\fP *msg, \fBuint8_t\fPlen)"
.PP
Definition at line 245 of file nwk_api\&.c\&.
.SS "\fBsmplStatus_t\fP \fBSMPL_SendOpt\fP (\fBlinkID_t\fPlid, \fBuint8_t\fP *msg, \fBuint8_t\fPlen, \fBtxOpt_t\fPoptions)"
.PP
Definition at line 274 of file nwk_api\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBuint8_t\fP \fBsInit_done\fP = 0"
.PP
Definition at line 84 of file nwk_api\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
