.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/nwk_applications/nwk_mgmt.h" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/nwk_applications/nwk_mgmt.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMGMT_REQ_POLL\fP   0x01"
.br
.ti -1c
.RI "#define \fBMAX_MGMT_APP_FRAME\fP   7"
.br
.ti -1c
.RI "#define \fBMB_APP_INFO_OS\fP   0"
.br
.ti -1c
.RI "#define \fBMB_TID_OS\fP   1"
.br
.ti -1c
.RI "#define \fBM_POLL_PORT_OS\fP   2"
.br
.ti -1c
.RI "#define \fBM_POLL_ADDR_OS\fP   3"
.br
.ti -1c
.RI "#define \fBMAX_MGMT_APP_FRAME\fP   7"
.br
.ti -1c
.RI "#define \fBMGMT_POLL_FRAME_SIZE\fP   7"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnwk_mgmtInit\fP (void)"
.br
.ti -1c
.RI "\fBfhStatus_t\fP \fBnwk_processMgmt\fP (\fBmrfiPacket_t\fP *)"
.br
.ti -1c
.RI "\fBsmplStatus_t\fP \fBnwk_poll\fP (\fBuint8_t\fP, \fBuint8_t\fP *)"
.br
.ti -1c
.RI "void \fBnwk_resetSFMarker\fP (\fBuint8_t\fP)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBM_POLL_ADDR_OS\fP   3"
.PP
Definition at line 53 of file nwk_mgmt\&.h\&.
.SS "#define \fBM_POLL_PORT_OS\fP   2"
.PP
Definition at line 52 of file nwk_mgmt\&.h\&.
.SS "#define \fBMAX_MGMT_APP_FRAME\fP   7"
.PP
Definition at line 56 of file nwk_mgmt\&.h\&.
.SS "#define \fBMAX_MGMT_APP_FRAME\fP   7"
.PP
Definition at line 56 of file nwk_mgmt\&.h\&.
.SS "#define \fBMB_APP_INFO_OS\fP   0"
.PP
Definition at line 48 of file nwk_mgmt\&.h\&.
.SS "#define \fBMB_TID_OS\fP   1"
.PP
Definition at line 49 of file nwk_mgmt\&.h\&.
.SS "#define \fBMGMT_POLL_FRAME_SIZE\fP   7"
.PP
Definition at line 59 of file nwk_mgmt\&.h\&.
.SS "#define \fBMGMT_REQ_POLL\fP   0x01"
.PP
Definition at line 41 of file nwk_mgmt\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBnwk_mgmtInit\fP (void)"
.PP
Definition at line 103 of file nwk_mgmt\&.c\&.
.SS "\fBsmplStatus_t\fP \fBnwk_poll\fP (\fBuint8_t\fP, \fBuint8_t\fP *)"
.PP
Definition at line 317 of file nwk_mgmt\&.c\&.
.SS "\fBfhStatus_t\fP \fBnwk_processMgmt\fP (\fBmrfiPacket_t\fP *)"
.PP
Definition at line 128 of file nwk_mgmt\&.c\&.
.SS "void \fBnwk_resetSFMarker\fP (\fBuint8_t\fP)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
