.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/include/project.h" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/include/project.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cc430x613x\&.h>\fP
.br
\fC#include <msp430F5509\&.h>\fP
.br
\fC#include <bm\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBs_system_flags\fP"
.br
.ti -1c
.RI "union \fBs_request_flags\fP"
.br
.ti -1c
.RI "union \fBs_message_flags\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBUSE_WATCHDOG\fP"
.br
.ti -1c
.RI "#define \fBFILTER_OFF\fP   (0u)"
.br
.ti -1c
.RI "#define \fBFILTER_ON\fP   (1u)"
.br
.ti -1c
.RI "#define \fBCONV_US_TO_TICKS\fP(usec)   (((usec) * 32768) / 1000000)"
.br
.ti -1c
.RI "#define \fBCONV_MS_TO_TICKS\fP(msec)   (((msec) * 32768) / 1000)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBmenu_t\fP { \fBMENU_ITEM_NOT_VISIBLE\fP =  0, \fBMENU_ITEM_VISIBLE\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile \fBs_system_flags\fP \fBsys\fP"
.br
.ti -1c
.RI "volatile \fBs_request_flags\fP \fBrequest\fP"
.br
.ti -1c
.RI "volatile \fBs_message_flags\fP \fBmessage\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBCONV_MS_TO_TICKS\fP(msec)   (((msec) * 32768) / 1000)"
.PP
Definition at line 67 of file project\&.h\&.
.SS "#define \fBCONV_US_TO_TICKS\fP(usec)   (((usec) * 32768) / 1000000)"
.PP
Definition at line 64 of file project\&.h\&.
.SS "#define \fBFILTER_OFF\fP   (0u)"
.PP
Definition at line 56 of file project\&.h\&.
.SS "#define \fBFILTER_ON\fP   (1u)"
.PP
Definition at line 57 of file project\&.h\&.
.SS "#define \fBUSE_WATCHDOG\fP"
.PP
Definition at line 53 of file project\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBmenu_t\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIMENU_ITEM_NOT_VISIBLE \fP\fP
.TP
\fB\fIMENU_ITEM_VISIBLE \fP\fP

.PP
Definition at line 73 of file project\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "volatile \fBs_message_flags\fP \fBmessage\fP"
.PP
Definition at line 106 of file main\&.c\&.
.SS "volatile \fBs_request_flags\fP \fBrequest\fP"
.PP
Definition at line 103 of file main\&.c\&.
.SS "volatile \fBs_system_flags\fP \fBsys\fP"
.PP
Definition at line 100 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
