.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/driver/radio.c" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/driver/radio.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include 'rf1a\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'rfsimpliciti\&.h'\fP
.br
\fC#include 'bluerobin\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMRFI_RadioIsr\fP (void)"
.br
.ti -1c
.RI "void \fBBlueRobin_RadioISR_v\fP (void)"
.br
.ti -1c
.RI "void \fBradio_reset\fP (void)"
.br
.ti -1c
.RI "void \fBradio_powerdown\fP (void)"
.br
.ti -1c
.RI "void \fBradio_sxoff\fP (void)"
.br
.ti -1c
.RI "void \fBopen_radio\fP (void)"
.br
.ti -1c
.RI "void \fBclose_radio\fP (void)"
.br
.ti -1c
.RI "__interrupt void \fBradio_ISR\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBBlueRobin_RadioISR_v\fP (void)"
.PP
Definition at line 3 of file stubs\&.c\&.
.SS "void \fBclose_radio\fP (void)"
.PP
Definition at line 146 of file radio\&.c\&.
.SS "void \fBMRFI_RadioIsr\fP (void)"
.PP
Definition at line 1176 of file mrfi_radio\&.c\&.
.SS "void \fBopen_radio\fP (void)"
.PP
Definition at line 127 of file radio\&.c\&.
.SS "__interrupt void \fBradio_ISR\fP (void)"
.PP
Definition at line 169 of file radio\&.c\&.
.SS "void \fBradio_powerdown\fP (void)"
.PP
Definition at line 90 of file radio\&.c\&.
.SS "void \fBradio_reset\fP (void)"
.PP
Definition at line 66 of file radio\&.c\&.
.SS "void \fBradio_sxoff\fP (void)"
.PP
Definition at line 109 of file radio\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
