.TH "rcvContext_t" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcvContext_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'nwk_types\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBrcvType_t\fP \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBlinkID_t\fP \fBlid\fP"
.br
.ti -1c
.RI "   \fBuint8_t\fP \fBport\fP"
.br
.ti -1c
.RI "   \fBmrfiPacket_t\fP * \fBpkt\fP"
.br
.ti -1c
.RI "} \fBt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 263 of file nwk_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBlinkID_t\fP \fBlid\fP"
.PP
Definition at line 268 of file nwk_types\&.h\&.
.SS "\fBmrfiPacket_t\fP* \fBpkt\fP"
.PP
Definition at line 270 of file nwk_types\&.h\&.
.SS "\fBuint8_t\fP \fBport\fP"
.PP
Definition at line 269 of file nwk_types\&.h\&.
.SS "union { \&.\&.\&. }   \fBt\fP"
.SS "\fBrcvType_t\fP \fBtype\fP"
.PP
Definition at line 265 of file nwk_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
