.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/rfsimpliciti.h" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/rfsimpliciti.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBRFsmpl\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSIMPLICITI_TIMEOUT\fP   (60*60u)"
.br
.ti -1c
.RI "#define \fBSIMPLICITI_BUTTON_STAR\fP   (0x10)"
.br
.ti -1c
.RI "#define \fBSIMPLICITI_BUTTON_NUM\fP   (0x20)"
.br
.ti -1c
.RI "#define \fBSIMPLICITI_BUTTON_UP\fP   (0x30)"
.br
.ti -1c
.RI "#define \fBSIMPLICITI_MOUSE_EVENTS\fP   (0x01)"
.br
.ti -1c
.RI "#define \fBSIMPLICITI_KEY_EVENTS\fP   (0x02)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBsimpliciti_mode_t\fP { \fBSIMPLICITI_OFF\fP =  0, \fBSIMPLICITI_ACCELERATION\fP, \fBSIMPLICITI_BUTTONS\fP, \fBSIMPLICITI_SYNC\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreset_rf\fP (void)"
.br
.ti -1c
.RI "void \fBsx_rf\fP (u8 line)"
.br
.ti -1c
.RI "void \fBsx_ppt\fP (u8 line)"
.br
.ti -1c
.RI "void \fBsx_sync\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_rf\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBdisplay_ppt\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBdisplay_sync\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBsend_smpl_data\fP (\fBu16\fP data)"
.br
.ti -1c
.RI "u8 \fBis_rf\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBRFsmpl\fP \fBsRFsmpl\fP"
.br
.ti -1c
.RI "unsigned char \fBsimpliciti_flag\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBSIMPLICITI_BUTTON_NUM\fP   (0x20)"
.PP
Definition at line 73 of file rfsimpliciti\&.h\&.
.SS "#define \fBSIMPLICITI_BUTTON_STAR\fP   (0x10)"
.PP
Definition at line 72 of file rfsimpliciti\&.h\&.
.SS "#define \fBSIMPLICITI_BUTTON_UP\fP   (0x30)"
.PP
Definition at line 74 of file rfsimpliciti\&.h\&.
.SS "#define \fBSIMPLICITI_KEY_EVENTS\fP   (0x02)"
.PP
Definition at line 78 of file rfsimpliciti\&.h\&.
.SS "#define \fBSIMPLICITI_MOUSE_EVENTS\fP   (0x01)"
.PP
Definition at line 77 of file rfsimpliciti\&.h\&.
.SS "#define \fBSIMPLICITI_TIMEOUT\fP   (60*60u)"
.PP
Definition at line 69 of file rfsimpliciti\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBsimpliciti_mode_t\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fISIMPLICITI_OFF \fP\fP
.TP
\fB\fISIMPLICITI_ACCELERATION \fP\fP
.TP
\fB\fISIMPLICITI_BUTTONS \fP\fP
.TP
\fB\fISIMPLICITI_SYNC \fP\fP

.PP
Definition at line 60 of file rfsimpliciti\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBdisplay_ppt\fP (u8line, u8update)"
.PP
Definition at line 302 of file rfsimpliciti\&.c\&.
.SS "void \fBdisplay_rf\fP (u8line, u8update)"
.PP
Definition at line 286 of file rfsimpliciti\&.c\&.
.SS "void \fBdisplay_sync\fP (u8line, u8update)"
.PP
Definition at line 318 of file rfsimpliciti\&.c\&.
.SS "u8 \fBis_rf\fP (void)"
.PP
Definition at line 333 of file rfsimpliciti\&.c\&.
.SS "void \fBreset_rf\fP (void)"
.PP
Definition at line 123 of file rfsimpliciti\&.c\&.
.SS "void \fBsend_smpl_data\fP (\fBu16\fPdata)"
.SS "void \fBsx_ppt\fP (u8line)"
.PP
Definition at line 158 of file rfsimpliciti\&.c\&.
.SS "void \fBsx_rf\fP (u8line)"
.PP
Definition at line 139 of file rfsimpliciti\&.c\&.
.SS "void \fBsx_sync\fP (u8line)"
.PP
Definition at line 177 of file rfsimpliciti\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "unsigned char \fBsimpliciti_flag\fP"
.PP
Definition at line 84 of file rfsimpliciti\&.c\&.
.SS "struct \fBRFsmpl\fP \fBsRFsmpl\fP"
.PP
Definition at line 81 of file rfsimpliciti\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
