.TH "s_message_flags" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_message_flags \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'project\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBu16\fP \fBprepare\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBshow\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBerase\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBtype_locked\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBtype_unlocked\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBtype_lobatt\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBtype_alarm_on\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBtype_alarm_off\fP: 1"
.br
.ti -1c
.RI "} \fBflag\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBall_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 116 of file project\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBu16\fP \fBall_flags\fP"
.PP
Definition at line 129 of file project\&.h\&.
.SS "\fBu16\fP \fBerase\fP"
.PP
Definition at line 122 of file project\&.h\&.
.SS "struct { \&.\&.\&. }   \fBflag\fP"
.SS "\fBu16\fP \fBprepare\fP"
.PP
Definition at line 120 of file project\&.h\&.
.SS "\fBu16\fP \fBshow\fP"
.PP
Definition at line 121 of file project\&.h\&.
.SS "\fBu16\fP \fBtype_alarm_off\fP"
.PP
Definition at line 127 of file project\&.h\&.
.SS "\fBu16\fP \fBtype_alarm_on\fP"
.PP
Definition at line 126 of file project\&.h\&.
.SS "\fBu16\fP \fBtype_lobatt\fP"
.PP
Definition at line 125 of file project\&.h\&.
.SS "\fBu16\fP \fBtype_locked\fP"
.PP
Definition at line 123 of file project\&.h\&.
.SS "\fBu16\fP \fBtype_unlocked\fP"
.PP
Definition at line 124 of file project\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
