.TH "sigInfo_t" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sigInfo_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'nwk_frame\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBrssi\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBlqi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 115 of file nwk_frame\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint8_t\fP \fBlqi\fP"
.PP
Definition at line 118 of file nwk_frame\&.h\&.
.SS "\fBuint8_t\fP \fBrssi\fP"
.PP
Definition at line 117 of file nwk_frame\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
