.TH "smplVersionInfo_t" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
smplVersionInfo_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'nwk_types\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBprotocolVersion\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBfwVerString\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 277 of file nwk_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint8_t\fP \fBfwVerString\fP[4]"
.PP
Definition at line 280 of file nwk_types\&.h\&.
.SS "\fBuint8_t\fP \fBprotocolVersion\fP"
.PP
Definition at line 279 of file nwk_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
