.TH "struct_button" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
struct_button \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'ports\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBstar_timeout\fP"
.br
.ti -1c
.RI "u8 \fBnum_timeout\fP"
.br
.ti -1c
.RI "s16 \fBrepeats\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 106 of file ports\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u8 \fBnum_timeout\fP"
.PP
Definition at line 109 of file ports\&.h\&.
.SS "s16 \fBrepeats\fP"
.PP
Definition at line 110 of file ports\&.h\&.
.SS "u8 \fBstar_timeout\fP"
.PP
Definition at line 108 of file ports\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
