.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/stubs.c" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/stubs.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBbr\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBlueRobin_state_t\fP { \fBBLUEROBIN_OFF\fP =  0, \fBBLUEROBIN_SEARCHING\fP, \fBBLUEROBIN_CONNECTED\fP, \fBBLUEROBIN_ERROR\fP, \fBBLUEROBIN_OFF\fP =  0, \fBBLUEROBIN_SEARCHING\fP, \fBBLUEROBIN_CONNECTED\fP, \fBBLUEROBIN_ERROR\fP }"
.br
.ti -1c
.RI "enum \fBBlueRobin_update_t\fP { \fBBLUEROBIN_NO_UPDATE\fP =  0, \fBBLUEROBIN_NEW_DATA\fP, \fBBLUEROBIN_NO_UPDATE\fP =  0, \fBBLUEROBIN_NEW_DATA\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBlueRobin_RadioISR_v\fP (void)"
.br
.ti -1c
.RI "void \fBBRRX_TimerTask_v\fP (void)"
.br
.ti -1c
.RI "unsigned char \fBis_bluerobin\fP (void)"
.br
.ti -1c
.RI "unsigned char \fBis_bluerobin_searching\fP (void)"
.br
.ti -1c
.RI "void \fBtest_mode\fP (void)"
.br
.ti -1c
.RI "void \fBreset_bluerobin\fP (void)"
.br
.ti -1c
.RI "void \fBget_bluerobin_data\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBbr\fP \fBsBlueRobin\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBBlueRobin_state_t\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIBLUEROBIN_OFF \fP\fP
.TP
\fB\fIBLUEROBIN_SEARCHING \fP\fP
.TP
\fB\fIBLUEROBIN_CONNECTED \fP\fP
.TP
\fB\fIBLUEROBIN_ERROR \fP\fP
.TP
\fB\fIBLUEROBIN_OFF \fP\fP
.TP
\fB\fIBLUEROBIN_SEARCHING \fP\fP
.TP
\fB\fIBLUEROBIN_CONNECTED \fP\fP
.TP
\fB\fIBLUEROBIN_ERROR \fP\fP

.PP
Definition at line 31 of file stubs\&.c\&.
.SS "enum \fBBlueRobin_update_t\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIBLUEROBIN_NO_UPDATE \fP\fP
.TP
\fB\fIBLUEROBIN_NEW_DATA \fP\fP
.TP
\fB\fIBLUEROBIN_NO_UPDATE \fP\fP
.TP
\fB\fIBLUEROBIN_NEW_DATA \fP\fP

.PP
Definition at line 39 of file stubs\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void \fBBlueRobin_RadioISR_v\fP (void)"
.PP
Definition at line 3 of file stubs\&.c\&.
.SS "void \fBBRRX_TimerTask_v\fP (void)"
.PP
Definition at line 7 of file stubs\&.c\&.
.SS "void \fBget_bluerobin_data\fP (void)"
.PP
Definition at line 27 of file stubs\&.c\&.
.SS "unsigned char \fBis_bluerobin\fP (void)"
.PP
Definition at line 11 of file stubs\&.c\&.
.SS "unsigned char \fBis_bluerobin_searching\fP (void)"
.PP
Definition at line 15 of file stubs\&.c\&.
.SS "void \fBreset_bluerobin\fP (void)"
.PP
Definition at line 23 of file stubs\&.c\&.
.SS "void \fBtest_mode\fP (void)"
.PP
Definition at line 19 of file stubs\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBbr\fP \fBsBlueRobin\fP"
.PP
Definition at line 76 of file stubs\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
