.TH "temp" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
temp \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'temperature\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmenu_t\fP \fBstate\fP"
.br
.ti -1c
.RI "s16 \fBdegrees\fP"
.br
.ti -1c
.RI "s16 \fBoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file temperature\&.h\&.
.SH "Field Documentation"
.PP 
.SS "s16 \fBdegrees\fP"
.PP
Definition at line 67 of file temperature\&.h\&.
.SS "s16 \fBoffset\fP"
.PP
Definition at line 69 of file temperature\&.h\&.
.SS "\fBmenu_t\fP \fBstate\fP"
.PP
Definition at line 65 of file temperature\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
