.TH "timer" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'timer\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBu16\fP \fBtimer0_A3_ticks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file timer\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBu16\fP \fBtimer0_A3_ticks\fP"
.PP
Definition at line 59 of file timer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
