.TH "UcsResetHandling" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UcsResetHandling \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'miscellaneous\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBstatus\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBcounter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file miscellaneous\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBu16\fP \fBcounter\fP"
.PP
Definition at line 67 of file miscellaneous\&.h\&.
.SS "u8 \fBstatus\fP"
.PP
Definition at line 66 of file miscellaneous\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
