.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/driver/vti_as.c" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/driver/vti_as.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include 'simpliciti\&.h'\fP
.br
\fC#include 'vti_as\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBAS_BR_DIVIDER\fP   (30u)"
.br
.ti -1c
.RI "#define \fBAS_RANGE\fP   (2u)"
.br
.ti -1c
.RI "#define \fBAS_SAMPLE_RATE\fP   (100u)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBas_start\fP (void)"
.br
.ti -1c
.RI "void \fBas_stop\fP (void)"
.br
.ti -1c
.RI "u8 \fBas_read_register\fP (u8 bAddress)"
.br
.ti -1c
.RI "u8 \fBas_write_register\fP (u8 bAddress, u8 bData)"
.br
.ti -1c
.RI "void \fBas_init\fP (void)"
.br
.ti -1c
.RI "void \fBas_get_data\fP (u8 *data)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "u8 \fBas_ok\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBAS_BR_DIVIDER\fP   (30u)"
.PP
Definition at line 70 of file vti_as\&.c\&.
.SS "#define \fBAS_RANGE\fP   (2u)"
.PP
Definition at line 74 of file vti_as\&.c\&.
.SS "#define \fBAS_SAMPLE_RATE\fP   (100u)"
.PP
Definition at line 79 of file vti_as\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void \fBas_get_data\fP (u8 *data)"
.PP
Definition at line 345 of file vti_as\&.c\&.
.SS "void \fBas_init\fP (void)"
.PP
Definition at line 100 of file vti_as\&.c\&.
.SS "u8 \fBas_read_register\fP (u8bAddress)"
.PP
Definition at line 242 of file vti_as\&.c\&.
.SS "void \fBas_start\fP (void)"
.PP
Definition at line 134 of file vti_as\&.c\&.
.SS "void \fBas_stop\fP (void)"
.PP
Definition at line 212 of file vti_as\&.c\&.
.SS "u8 \fBas_write_register\fP (u8bAddress, u8bData)"
.PP
Definition at line 294 of file vti_as\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "u8 \fBas_ok\fP"
.PP
Definition at line 86 of file vti_as\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
