.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/driver/vti_ps.c" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/driver/vti_ps.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include 'vti_ps\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBu16\fP \fBps_read_register\fP (u8 address, u8 mode)"
.br
.ti -1c
.RI "u8 \fBps_write_register\fP (u8 address, u8 data)"
.br
.ti -1c
.RI "u8 \fBps_twi_read\fP (u8 ack)"
.br
.ti -1c
.RI "void \fBtwi_delay\fP (void)"
.br
.ti -1c
.RI "void \fBps_init\fP (void)"
.br
.ti -1c
.RI "void \fBps_start\fP (void)"
.br
.ti -1c
.RI "void \fBps_stop\fP (void)"
.br
.ti -1c
.RI "u8 \fBps_twi_sda\fP (u8 condition)"
.br
.ti -1c
.RI "void \fBps_twi_write\fP (u8 data)"
.br
.ti -1c
.RI "u32 \fBps_get_pa\fP (void)"
.br
.ti -1c
.RI "\fBu16\fP \fBps_get_temp\fP (void)"
.br
.ti -1c
.RI "void \fBinit_pressure_table\fP (void)"
.br
.ti -1c
.RI "void \fBupdate_pressure_table\fP (s16 href, u32 p_meas, \fBu16\fP t_meas)"
.br
.ti -1c
.RI "s16 \fBconv_pa_to_meter\fP (u32 p_meas, \fBu16\fP t_meas)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const s16 \fBh0\fP [17] = { -153, 0, 111, 540, 989, 1457, 1949, 2466, 3012, 3591, 4206, 4865, 5574, 6344, 7185, 8117, 9164 }"
.br
.ti -1c
.RI "const \fBu16\fP \fBp0\fP [17] = { 1031, 1013, 1000, 950, 900, 850, 800, 750, 700, 650, 600, 550, 500, 450, 400, 350, 300 }"
.br
.ti -1c
.RI "float \fBp\fP [17]"
.br
.ti -1c
.RI "u8 \fBps_ok\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "s16 \fBconv_pa_to_meter\fP (u32p_meas, \fBu16\fPt_meas)"
.PP
Definition at line 509 of file vti_ps\&.c\&.
.SS "void \fBinit_pressure_table\fP (void)"
.PP
Definition at line 445 of file vti_ps\&.c\&.
.SS "u32 \fBps_get_pa\fP (void)"
.PP
Definition at line 384 of file vti_ps\&.c\&.
.SS "\fBu16\fP \fBps_get_temp\fP (void)"
.PP
Definition at line 408 of file vti_ps\&.c\&.
.SS "void \fBps_init\fP (void)"
.PP
Definition at line 85 of file vti_ps\&.c\&.
.SS "\fBu16\fP \fBps_read_register\fP (u8address, u8mode)"
.PP
Definition at line 340 of file vti_ps\&.c\&.
.SS "void \fBps_start\fP (void)"
.PP
Definition at line 124 of file vti_ps\&.c\&.
.SS "void \fBps_stop\fP (void)"
.PP
Definition at line 138 of file vti_ps\&.c\&.
.SS "u8 \fBps_twi_read\fP (u8ack)"
.PP
Definition at line 264 of file vti_ps\&.c\&.
.SS "u8 \fBps_twi_sda\fP (u8condition)"
.PP
Definition at line 153 of file vti_ps\&.c\&.
.SS "void \fBps_twi_write\fP (u8data)"
.PP
Definition at line 227 of file vti_ps\&.c\&.
.SS "u8 \fBps_write_register\fP (u8address, u8data)"
.PP
Definition at line 308 of file vti_ps\&.c\&.
.SS "void \fBtwi_delay\fP (void)"
.PP
Definition at line 215 of file vti_ps\&.c\&.
.SS "void \fBupdate_pressure_table\fP (s16href, u32p_meas, \fBu16\fPt_meas)"
.PP
Definition at line 462 of file vti_ps\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const s16 \fBh0\fP[17] = { -153, 0, 111, 540, 989, 1457, 1949, 2466, 3012, 3591, 4206, 4865, 5574, 6344, 7185, 8117, 9164 }"
.PP
Definition at line 66 of file vti_ps\&.c\&.
.SS "float \fBp\fP[17]"
.PP
Definition at line 68 of file vti_ps\&.c\&.
.SS "const \fBu16\fP \fBp0\fP[17] = { 1031, 1013, 1000, 950, 900, 850, 800, 750, 700, 650, 600, 550, 500, 450, 400, 350, 300 }"
.PP
Definition at line 67 of file vti_ps\&.c\&.
.SS "u8 \fBps_ok\fP"
.PP
Definition at line 71 of file vti_ps\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
