.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/driver/vti_as.h" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/driver/vti_as.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBAS_DISCONNECT\fP"
.br
.ti -1c
.RI "#define \fBAS_SPI_IN\fP   (P1IN)"
.br
.ti -1c
.RI "#define \fBAS_SPI_OUT\fP   (P1OUT)"
.br
.ti -1c
.RI "#define \fBAS_SPI_DIR\fP   (P1DIR)"
.br
.ti -1c
.RI "#define \fBAS_SPI_SEL\fP   (P1SEL)"
.br
.ti -1c
.RI "#define \fBAS_SPI_REN\fP   (P1REN)"
.br
.ti -1c
.RI "#define \fBAS_SDO_PIN\fP   (BIT6)"
.br
.ti -1c
.RI "#define \fBAS_SDI_PIN\fP   (BIT5)"
.br
.ti -1c
.RI "#define \fBAS_SCK_PIN\fP   (BIT7)"
.br
.ti -1c
.RI "#define \fBAS_CSN_OUT\fP   (PJOUT)"
.br
.ti -1c
.RI "#define \fBAS_CSN_DIR\fP   (PJDIR)"
.br
.ti -1c
.RI "#define \fBAS_CSN_PIN\fP   (BIT1)"
.br
.ti -1c
.RI "#define \fBAS_TX_BUFFER\fP   (UCA0TXBUF)"
.br
.ti -1c
.RI "#define \fBAS_RX_BUFFER\fP   (UCA0RXBUF)"
.br
.ti -1c
.RI "#define \fBAS_TX_IFG\fP   (UCTXIFG)"
.br
.ti -1c
.RI "#define \fBAS_RX_IFG\fP   (UCRXIFG)"
.br
.ti -1c
.RI "#define \fBAS_IRQ_REG\fP   (UCA0IFG)"
.br
.ti -1c
.RI "#define \fBAS_SPI_CTL0\fP   (UCA0CTL0)"
.br
.ti -1c
.RI "#define \fBAS_SPI_CTL1\fP   (UCA0CTL1)"
.br
.ti -1c
.RI "#define \fBAS_SPI_BR0\fP   (UCA0BR0)"
.br
.ti -1c
.RI "#define \fBAS_SPI_BR1\fP   (UCA0BR1)"
.br
.ti -1c
.RI "#define \fBAS_PWR_OUT\fP   (PJOUT)"
.br
.ti -1c
.RI "#define \fBAS_PWR_DIR\fP   (PJDIR)"
.br
.ti -1c
.RI "#define \fBAS_PWR_PIN\fP   (BIT0)"
.br
.ti -1c
.RI "#define \fBAS_INT_IN\fP   (P2IN)"
.br
.ti -1c
.RI "#define \fBAS_INT_OUT\fP   (P2OUT)"
.br
.ti -1c
.RI "#define \fBAS_INT_DIR\fP   (P2DIR)"
.br
.ti -1c
.RI "#define \fBAS_INT_IE\fP   (P2IE)"
.br
.ti -1c
.RI "#define \fBAS_INT_IES\fP   (P2IES)"
.br
.ti -1c
.RI "#define \fBAS_INT_IFG\fP   (P2IFG)"
.br
.ti -1c
.RI "#define \fBAS_INT_PIN\fP   (BIT5)"
.br
.ti -1c
.RI "#define \fBSPI_TIMEOUT\fP   (1000u)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBas_init\fP (void)"
.br
.ti -1c
.RI "void \fBas_start\fP (void)"
.br
.ti -1c
.RI "void \fBas_stop\fP (void)"
.br
.ti -1c
.RI "u8 \fBas_read_register\fP (u8 bAddress)"
.br
.ti -1c
.RI "u8 \fBas_write_register\fP (u8 bAddress, u8 bData)"
.br
.ti -1c
.RI "void \fBas_get_data\fP (u8 *data)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBAS_CSN_DIR\fP   (PJDIR)"
.PP
Definition at line 73 of file vti_as\&.h\&.
.SS "#define \fBAS_CSN_OUT\fP   (PJOUT)"
.PP
Definition at line 72 of file vti_as\&.h\&.
.SS "#define \fBAS_CSN_PIN\fP   (BIT1)"
.PP
Definition at line 74 of file vti_as\&.h\&.
.SS "#define \fBAS_DISCONNECT\fP"
.PP
Definition at line 58 of file vti_as\&.h\&.
.SS "#define \fBAS_INT_DIR\fP   (P2DIR)"
.PP
Definition at line 94 of file vti_as\&.h\&.
.SS "#define \fBAS_INT_IE\fP   (P2IE)"
.PP
Definition at line 95 of file vti_as\&.h\&.
.SS "#define \fBAS_INT_IES\fP   (P2IES)"
.PP
Definition at line 96 of file vti_as\&.h\&.
.SS "#define \fBAS_INT_IFG\fP   (P2IFG)"
.PP
Definition at line 97 of file vti_as\&.h\&.
.SS "#define \fBAS_INT_IN\fP   (P2IN)"
.PP
Definition at line 92 of file vti_as\&.h\&.
.SS "#define \fBAS_INT_OUT\fP   (P2OUT)"
.PP
Definition at line 93 of file vti_as\&.h\&.
.SS "#define \fBAS_INT_PIN\fP   (BIT5)"
.PP
Definition at line 98 of file vti_as\&.h\&.
.SS "#define \fBAS_IRQ_REG\fP   (UCA0IFG)"
.PP
Definition at line 80 of file vti_as\&.h\&.
.SS "#define \fBAS_PWR_DIR\fP   (PJDIR)"
.PP
Definition at line 88 of file vti_as\&.h\&.
.SS "#define \fBAS_PWR_OUT\fP   (PJOUT)"
.PP
Definition at line 87 of file vti_as\&.h\&.
.SS "#define \fBAS_PWR_PIN\fP   (BIT0)"
.PP
Definition at line 89 of file vti_as\&.h\&.
.SS "#define \fBAS_RX_BUFFER\fP   (UCA0RXBUF)"
.PP
Definition at line 77 of file vti_as\&.h\&.
.SS "#define \fBAS_RX_IFG\fP   (UCRXIFG)"
.PP
Definition at line 79 of file vti_as\&.h\&.
.SS "#define \fBAS_SCK_PIN\fP   (BIT7)"
.PP
Definition at line 69 of file vti_as\&.h\&.
.SS "#define \fBAS_SDI_PIN\fP   (BIT5)"
.PP
Definition at line 68 of file vti_as\&.h\&.
.SS "#define \fBAS_SDO_PIN\fP   (BIT6)"
.PP
Definition at line 67 of file vti_as\&.h\&.
.SS "#define \fBAS_SPI_BR0\fP   (UCA0BR0)"
.PP
Definition at line 83 of file vti_as\&.h\&.
.SS "#define \fBAS_SPI_BR1\fP   (UCA0BR1)"
.PP
Definition at line 84 of file vti_as\&.h\&.
.SS "#define \fBAS_SPI_CTL0\fP   (UCA0CTL0)"
.PP
Definition at line 81 of file vti_as\&.h\&.
.SS "#define \fBAS_SPI_CTL1\fP   (UCA0CTL1)"
.PP
Definition at line 82 of file vti_as\&.h\&.
.SS "#define \fBAS_SPI_DIR\fP   (P1DIR)"
.PP
Definition at line 64 of file vti_as\&.h\&.
.SS "#define \fBAS_SPI_IN\fP   (P1IN)"
.PP
Definition at line 62 of file vti_as\&.h\&.
.SS "#define \fBAS_SPI_OUT\fP   (P1OUT)"
.PP
Definition at line 63 of file vti_as\&.h\&.
.SS "#define \fBAS_SPI_REN\fP   (P1REN)"
.PP
Definition at line 66 of file vti_as\&.h\&.
.SS "#define \fBAS_SPI_SEL\fP   (P1SEL)"
.PP
Definition at line 65 of file vti_as\&.h\&.
.SS "#define \fBAS_TX_BUFFER\fP   (UCA0TXBUF)"
.PP
Definition at line 76 of file vti_as\&.h\&.
.SS "#define \fBAS_TX_IFG\fP   (UCTXIFG)"
.PP
Definition at line 78 of file vti_as\&.h\&.
.SS "#define \fBSPI_TIMEOUT\fP   (1000u)"
.PP
Definition at line 101 of file vti_as\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBas_get_data\fP (u8 *data)"
.PP
Definition at line 345 of file vti_as\&.c\&.
.SS "void \fBas_init\fP (void)"
.PP
Definition at line 100 of file vti_as\&.c\&.
.SS "u8 \fBas_read_register\fP (u8bAddress)"
.PP
Definition at line 242 of file vti_as\&.c\&.
.SS "void \fBas_start\fP (void)"
.PP
Definition at line 134 of file vti_as\&.c\&.
.SS "void \fBas_stop\fP (void)"
.PP
Definition at line 212 of file vti_as\&.c\&.
.SS "u8 \fBas_write_register\fP (u8bAddress, u8bData)"
.PP
Definition at line 294 of file vti_as\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
