.TH "accel" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
accel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'acceleration\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBmode\fP"
.br
.ti -1c
.RI "u8 \fBxyz\fP [3]"
.br
.ti -1c
.RI "\fBu16\fP \fBdata\fP"
.br
.ti -1c
.RI "u8 \fBview_style\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBtimeout\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file acceleration\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBu16\fP \fBdata\fP"
.PP
Definition at line 74 of file acceleration\&.h\&.
.SS "u8 \fBmode\fP"
.PP
Definition at line 68 of file acceleration\&.h\&.
.SS "\fBu16\fP \fBtimeout\fP"
.PP
Definition at line 80 of file acceleration\&.h\&.
.SS "u8 \fBview_style\fP"
.PP
Definition at line 77 of file acceleration\&.h\&.
.SS "u8 \fBxyz\fP[3]"
.PP
Definition at line 71 of file acceleration\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
