.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/agility.c" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/agility.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'vti_as\&.h'\fP
.br
\fC#include 'ports\&.h'\fP
.br
\fC#include 'user\&.h'\fP
.br
\fC#include 'agility\&.h'\fP
.br
\fC#include 'acceleration\&.h'\fP
.br
\fC#include 'simpliciti\&.h'\fP
.br
\fC#include 'menu\&.h'\fP
.br
\fC#include 'display2\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBACCEL_TIMEOUT_PREVENTION\fP   5"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstart_agility\fP (void)"
.br
.ti -1c
.RI "void \fBstop_agility\fP (void)"
.br
.ti -1c
.RI "void \fBset_agility\fP (void)"
.br
.ti -1c
.RI "void \fBwrite_agility_history\fP (void)"
.br
.ti -1c
.RI "u8 \fBacceleration_value_is_positive\fP (u8 value)"
.br
.ti -1c
.RI "\fBu16\fP \fBconvert_acceleration_value_to_mgrav\fP (u8 value)"
.br
.ti -1c
.RI "void \fBdisplay_agility_indicator\fP (u8 segments, u32 value, u8 digits, u8 blanks)"
.br
.ti -1c
.RI "void \fBagility_tick\fP (void)"
.br
.ti -1c
.RI "void \fBreset_agility\fP (void)"
.br
.ti -1c
.RI "void \fBmx_agility\fP (u8 line)"
.br
.ti -1c
.RI "void \fBsx_agility\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_agility\fP (u8 line, u8 update)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBagil\fP \fBsAgil\fP"
.br
.ti -1c
.RI "u8 \fBas_ok\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBACCEL_TIMEOUT_PREVENTION\fP   5"
.PP
Definition at line 70 of file agility\&.c\&.
.SH "Function Documentation"
.PP 
.SS "u8 \fBacceleration_value_is_positive\fP (u8value)"
.PP
Definition at line 114 of file acceleration\&.c\&.
.SS "void \fBagility_tick\fP (void)"
.PP
Definition at line 123 of file agility\&.c\&.
.SS "\fBu16\fP \fBconvert_acceleration_value_to_mgrav\fP (u8value)"
.PP
Definition at line 126 of file acceleration\&.c\&.
.SS "void \fBdisplay_agility\fP (u8line, u8update)"
.PP
Definition at line 333 of file agility\&.c\&.
.SS "void \fBdisplay_agility_indicator\fP (u8segments, u32value, u8digits, u8blanks)"
.PP
Definition at line 98 of file agility\&.c\&.
.SS "void \fBmx_agility\fP (u8line)"
.PP
Definition at line 279 of file agility\&.c\&.
.SS "void \fBreset_agility\fP (void)"
.PP
Definition at line 181 of file agility\&.c\&.
.SS "void \fBset_agility\fP (void)"
.PP
Definition at line 379 of file agility\&.c\&.
.SS "void \fBstart_agility\fP (void)"
.PP
Definition at line 214 of file agility\&.c\&.
.SS "void \fBstop_agility\fP (void)"
.PP
Definition at line 244 of file agility\&.c\&.
.SS "void \fBsx_agility\fP (u8line)"
.PP
Definition at line 306 of file agility\&.c\&.
.SS "void \fBwrite_agility_history\fP (void)"
.PP
Definition at line 264 of file agility\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "u8 \fBas_ok\fP"
.PP
Definition at line 86 of file vti_as\&.c\&.
.SS "struct \fBagil\fP \fBsAgil\fP"
.PP
Definition at line 75 of file agility\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
