.TH "batt" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
batt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'battery\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmenu_t\fP \fBstate\fP"
.br
.ti -1c
.RI "u8 \fBlobatt_display\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBvoltage\fP"
.br
.ti -1c
.RI "s16 \fBoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 70 of file battery\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u8 \fBlobatt_display\fP"
.PP
Definition at line 76 of file battery\&.h\&.
.SS "s16 \fBoffset\fP"
.PP
Definition at line 82 of file battery\&.h\&.
.SS "\fBmenu_t\fP \fBstate\fP"
.PP
Definition at line 73 of file battery\&.h\&.
.SS "\fBu16\fP \fBvoltage\fP"
.PP
Definition at line 79 of file battery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
