.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/bsp/mcus/bsp_msp430_defs.h" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/bsp/mcus/bsp_msp430_defs.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBSP_MCU_MSP430\fP"
.br
.ti -1c
.RI "#define \fB__bsp_LITTLE_ENDIAN__\fP   1"
.br
.ti -1c
.RI "#define \fB__bsp_CODE_MEMSPACE__\fP   /* blank */"
.br
.ti -1c
.RI "#define \fB__bsp_XDATA_MEMSPACE__\fP   /* blank */"
.br
.ti -1c
.RI "#define \fBNULL\fP   0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef signed char \fBint8_t\fP"
.br
.ti -1c
.RI "typedef signed short \fBint16_t\fP"
.br
.ti -1c
.RI "typedef signed long \fBint32_t\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBuint8_t\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBuint16_t\fP"
.br
.ti -1c
.RI "typedef unsigned long \fBuint32_t\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fB__bsp_CODE_MEMSPACE__\fP   /* blank */"
.PP
Definition at line 124 of file bsp_msp430_defs\&.h\&.
.SS "#define \fB__bsp_LITTLE_ENDIAN__\fP   1"
.PP
Definition at line 123 of file bsp_msp430_defs\&.h\&.
.SS "#define \fB__bsp_XDATA_MEMSPACE__\fP   /* blank */"
.PP
Definition at line 125 of file bsp_msp430_defs\&.h\&.
.SS "#define \fBBSP_MCU_MSP430\fP"
.PP
Definition at line 47 of file bsp_msp430_defs\&.h\&.
.SS "#define \fBNULL\fP   0"
.PP
Definition at line 136 of file bsp_msp430_defs\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef signed short \fBint16_t\fP"
.PP
Definition at line 128 of file bsp_msp430_defs\&.h\&.
.SS "typedef signed long \fBint32_t\fP"
.PP
Definition at line 129 of file bsp_msp430_defs\&.h\&.
.SS "typedef signed char \fBint8_t\fP"
.PP
Definition at line 127 of file bsp_msp430_defs\&.h\&.
.SS "typedef unsigned short \fBuint16_t\fP"
.PP
Definition at line 132 of file bsp_msp430_defs\&.h\&.
.SS "typedef unsigned long \fBuint32_t\fP"
.PP
Definition at line 133 of file bsp_msp430_defs\&.h\&.
.SS "typedef unsigned char \fBuint8_t\fP"
.PP
Definition at line 131 of file bsp_msp430_defs\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
