.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/bsp/drivers/bsp_buttons.h" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/bsp/drivers/bsp_buttons.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bsp_button_defs\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBSP_NUM_BUTTONS\fP   \fB__bsp_NUM_BUTTONS__\fP"
.br
.ti -1c
.RI "#define \fBBSP_BUTTON_DEBOUNCE_WAIT\fP(expr)   \fB__bsp_BUTTON_DEBOUNCE_WAIT__\fP(expr)"
.br
.ti -1c
.RI "#define \fBBSP_BUTTON1\fP()   \fB__bsp_BUTTON1__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_BUTTON2\fP()   \fB__bsp_BUTTON2__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_BUTTON3\fP()   \fB__bsp_BUTTON3__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_BUTTON4\fP()   \fB__bsp_BUTTON4__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_BUTTON5\fP()   \fB__bsp_BUTTON5__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_BUTTON6\fP()   \fB__bsp_BUTTON6__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_BUTTON7\fP()   \fB__bsp_BUTTON7__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_BUTTON8\fP()   \fB__bsp_BUTTON8__\fP()"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBSP_InitButtons\fP (void)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBBSP_BUTTON1\fP()   \fB__bsp_BUTTON1__\fP()"
.PP
Definition at line 62 of file bsp_buttons\&.h\&.
.SS "#define \fBBSP_BUTTON2\fP()   \fB__bsp_BUTTON2__\fP()"
.PP
Definition at line 63 of file bsp_buttons\&.h\&.
.SS "#define \fBBSP_BUTTON3\fP()   \fB__bsp_BUTTON3__\fP()"
.PP
Definition at line 64 of file bsp_buttons\&.h\&.
.SS "#define \fBBSP_BUTTON4\fP()   \fB__bsp_BUTTON4__\fP()"
.PP
Definition at line 65 of file bsp_buttons\&.h\&.
.SS "#define \fBBSP_BUTTON5\fP()   \fB__bsp_BUTTON5__\fP()"
.PP
Definition at line 66 of file bsp_buttons\&.h\&.
.SS "#define \fBBSP_BUTTON6\fP()   \fB__bsp_BUTTON6__\fP()"
.PP
Definition at line 67 of file bsp_buttons\&.h\&.
.SS "#define \fBBSP_BUTTON7\fP()   \fB__bsp_BUTTON7__\fP()"
.PP
Definition at line 68 of file bsp_buttons\&.h\&.
.SS "#define \fBBSP_BUTTON8\fP()   \fB__bsp_BUTTON8__\fP()"
.PP
Definition at line 69 of file bsp_buttons\&.h\&.
.SS "#define \fBBSP_BUTTON_DEBOUNCE_WAIT\fP(expr)   \fB__bsp_BUTTON_DEBOUNCE_WAIT__\fP(expr)"
.PP
Definition at line 60 of file bsp_buttons\&.h\&.
.SS "#define \fBBSP_NUM_BUTTONS\fP   \fB__bsp_NUM_BUTTONS__\fP"
.PP
Definition at line 53 of file bsp_buttons\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBBSP_InitButtons\fP (void)"
.PP
Definition at line 76 of file bsp_buttons\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
