.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/clock.c" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/clock.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include 'ports\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'menu\&.h'\fP
.br
\fC#include 'clock\&.h'\fP
.br
\fC#include 'user\&.h'\fP
.br
\fC#include 'bluerobin\&.h'\fP
.br
\fC#include 'date\&.h'\fP
.br
\fC#include 'random\&.h'\fP
.br
\fC#include 'agility\&.h'\fP
.br
\fC#include 'display2\&.h'\fP
.br
\fC#include 'miscellaneous\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDAILY_CORRECTION_SEC_DEFAULT\fP   (0)"
.br
.ti -1c
.RI "#define \fBWEEKLY_CORRECTION_SEC_DEFAULT\fP   (0)"
.br
.ti -1c
.RI "#define \fBDST_NO\fP   0"
.br
.ti -1c
.RI "#define \fBDST_AUTO\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreset_clock\fP (void)"
.br
.ti -1c
.RI "void \fBclock_tick\fP (void)"
.br
.ti -1c
.RI "void \fBmx_time\fP (u8 line)"
.br
.ti -1c
.RI "void \fBsx_time\fP (u8 line)"
.br
.ti -1c
.RI "void \fBcalc_24H_to_12H\fP (u8 *hours, u8 *timeAM)"
.br
.ti -1c
.RI "void \fBconv_24H_to_12H\fP (u8 *hours24, u8 *hours12, u8 *timeAMorPM)"
.br
.ti -1c
.RI "void \fBnumber_storage_tick\fP (void)"
.br
.ti -1c
.RI "void \fBinit_ucs\fP (void)"
.br
.ti -1c
.RI "void \fBcdtimer_tick\fP (void)"
.br
.ti -1c
.RI "void \fBcheck_ucs\fP (void)"
.br
.ti -1c
.RI "u8 \fBconvert_hour_to_12H_format\fP (u8 hour)"
.br
.ti -1c
.RI "u8 \fBis_hour_am\fP (u8 hour)"
.br
.ti -1c
.RI "void \fBdisplay_selection_Timeformat1\fP (u8 segments, u32 index, u8 digits, u8 blanks)"
.br
.ti -1c
.RI "void \fBdisplay_time\fP (u8 line, u8 update)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "__no_init struct \fBtime\fP \fBsTime\fP"
.br
.ti -1c
.RI "u8 \fBTimeCorrectionFlag\fP"
.br
.ti -1c
.RI "u8 \fBDST_CorrectionFlag\fP"
.br
.ti -1c
.RI "u8 \fBDST_AutoFlag\fP"
.br
.ti -1c
.RI "s8 \fBDailyCorr\fP"
.br
.ti -1c
.RI "s8 \fBWeeklyCorr\fP"
.br
.ti -1c
.RI "u8 \fBBlOnFlag\fP"
.br
.ti -1c
.RI "u8 \fBBlTimeoutCounter\fP = 0"
.br
.ti -1c
.RI "const u8 \fBselection_Timeformat\fP [][4]"
.br
.ti -1c
.RI "void(* \fBfptr_lcd_function_line1\fP )(u8 line, u8 update)"
.br
.ti -1c
.RI "void(* \fBfptr_lcd_function_line2\fP )(u8 line, u8 update)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBDAILY_CORRECTION_SEC_DEFAULT\fP   (0)"
.PP
Definition at line 78 of file clock\&.c\&.
.SS "#define \fBDST_AUTO\fP   1"
.PP
Definition at line 81 of file clock\&.c\&.
.SS "#define \fBDST_NO\fP   0"
.PP
Definition at line 80 of file clock\&.c\&.
.SS "#define \fBWEEKLY_CORRECTION_SEC_DEFAULT\fP   (0)"
.PP
Definition at line 79 of file clock\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void \fBcalc_24H_to_12H\fP (u8 *hours, u8 *timeAM)"
.SS "void \fBcdtimer_tick\fP (void)"
.PP
Definition at line 122 of file countdowntimer\&.c\&.
.SS "void \fBcheck_ucs\fP (void)"
.PP
Definition at line 117 of file clock\&.c\&.
.SS "void \fBclock_tick\fP (void)"
.PP
Definition at line 192 of file clock\&.c\&.
.SS "void \fBconv_24H_to_12H\fP (u8 *hours24, u8 *hours12, u8 *timeAMorPM)"
.SS "u8 \fBconvert_hour_to_12H_format\fP (u8hour)"
.PP
Definition at line 372 of file clock\&.c\&.
.SS "void \fBdisplay_selection_Timeformat1\fP (u8segments, u32index, u8digits, u8blanks)"
.PP
Definition at line 406 of file clock\&.c\&.
.SS "void \fBdisplay_time\fP (u8line, u8update)"
.PP
Definition at line 581 of file clock\&.c\&.
.SS "void \fBinit_ucs\fP (void)"
.PP
Definition at line 170 of file main\&.c\&.
.SS "u8 \fBis_hour_am\fP (u8hour)"
.PP
Definition at line 388 of file clock\&.c\&.
.SS "void \fBmx_time\fP (u8line)"
.PP
Definition at line 418 of file clock\&.c\&.
.SS "void \fBnumber_storage_tick\fP (void)"
.PP
Definition at line 138 of file miscellaneous\&.c\&.
.SS "void \fBreset_clock\fP (void)"
.PP
Definition at line 158 of file clock\&.c\&.
.SS "void \fBsx_time\fP (u8line)"
.PP
Definition at line 566 of file clock\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "u8 \fBBlOnFlag\fP"
.PP
Definition at line 113 of file main\&.c\&.
.SS "u8 \fBBlTimeoutCounter\fP = 0"
.PP
Definition at line 94 of file clock\&.c\&.
.SS "s8 \fBDailyCorr\fP"
.PP
Definition at line 89 of file clock\&.c\&.
.SS "u8 \fBDST_AutoFlag\fP"
.PP
Definition at line 88 of file clock\&.c\&.
.SS "u8 \fBDST_CorrectionFlag\fP"
.PP
Definition at line 87 of file clock\&.c\&.
.SS "void(* \fBfptr_lcd_function_line1\fP)(u8 line, u8 update)"
.PP
Definition at line 116 of file main\&.c\&.
.SS "void(* \fBfptr_lcd_function_line2\fP)(u8 line, u8 update)"
.PP
Definition at line 117 of file main\&.c\&.
.SS "const u8 \fBselection_Timeformat\fP[][4]"\fBInitial value:\fP
.PP
.nf

{
        '24H', '12H'
}
.fi
.PP
Definition at line 97 of file clock\&.c\&.
.SS "__no_init struct \fBtime\fP \fBsTime\fP"
.PP
Definition at line 85 of file clock\&.c\&.
.SS "u8 \fBTimeCorrectionFlag\fP"
.PP
Definition at line 86 of file clock\&.c\&.
.SS "s8 \fBWeeklyCorr\fP"
.PP
Definition at line 90 of file clock\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
