.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/clock.h" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/clock.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtime\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBTIMEFORMAT_24H\fP   (0u)"
.br
.ti -1c
.RI "#define \fBTIMEFORMAT_12H\fP   (1u)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreset_clock\fP (void)"
.br
.ti -1c
.RI "void \fBsx_time\fP (u8 line)"
.br
.ti -1c
.RI "void \fBmx_time\fP (u8 line)"
.br
.ti -1c
.RI "void \fBclock_tick\fP (void)"
.br
.ti -1c
.RI "void \fBdisplay_selection_Timeformat1\fP (u8 segments, u32 index, u8 digits, u8 blanks)"
.br
.ti -1c
.RI "void \fBdisplay_time\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBcalc_24H_to_12H\fP (u8 *hours, u8 *timeAM)"
.br
.ti -1c
.RI "u8 \fBconvert_hour_to_12H_format\fP (u8 hour)"
.br
.ti -1c
.RI "u8 \fBis_hour_am\fP (u8 hour)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBtime\fP \fBsTime\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBTIMEFORMAT_12H\fP   (1u)"
.PP
Definition at line 44 of file clock\&.h\&.
.SS "#define \fBTIMEFORMAT_24H\fP   (0u)"
.PP
Definition at line 43 of file clock\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBcalc_24H_to_12H\fP (u8 *hours, u8 *timeAM)"
.SS "void \fBclock_tick\fP (void)"
.PP
Definition at line 192 of file clock\&.c\&.
.SS "u8 \fBconvert_hour_to_12H_format\fP (u8hour)"
.PP
Definition at line 372 of file clock\&.c\&.
.SS "void \fBdisplay_selection_Timeformat1\fP (u8segments, u32index, u8digits, u8blanks)"
.PP
Definition at line 406 of file clock\&.c\&.
.SS "void \fBdisplay_time\fP (u8line, u8update)"
.PP
Definition at line 581 of file clock\&.c\&.
.SS "u8 \fBis_hour_am\fP (u8hour)"
.PP
Definition at line 388 of file clock\&.c\&.
.SS "void \fBmx_time\fP (u8line)"
.PP
Definition at line 418 of file clock\&.c\&.
.SS "void \fBreset_clock\fP (void)"
.PP
Definition at line 158 of file clock\&.c\&.
.SS "void \fBsx_time\fP (u8line)"
.PP
Definition at line 566 of file clock\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBtime\fP \fBsTime\fP"
.PP
Definition at line 85 of file clock\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
