.TH "ioctlRawSend_t" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ioctlRawSend_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'nwk_types\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBaddr_t\fP * \fBaddr\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBmsg\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBlen\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBport\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 109 of file nwk_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBaddr_t\fP* \fBaddr\fP"
.PP
Definition at line 111 of file nwk_types\&.h\&.
.SS "\fBuint8_t\fP \fBlen\fP"
.PP
Definition at line 113 of file nwk_types\&.h\&.
.SS "\fBuint8_t\fP* \fBmsg\fP"
.PP
Definition at line 112 of file nwk_types\&.h\&.
.SS "\fBuint8_t\fP \fBport\fP"
.PP
Definition at line 114 of file nwk_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
