.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/menu.c" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/logic/menu.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'menu\&.h'\fP
.br
\fC#include 'user\&.h'\fP
.br
\fC#include 'clock\&.h'\fP
.br
\fC#include 'date\&.h'\fP
.br
\fC#include 'alarm\&.h'\fP
.br
\fC#include 'stopwatch\&.h'\fP
.br
\fC#include 'temperature\&.h'\fP
.br
\fC#include 'altitude\&.h'\fP
.br
\fC#include 'battery\&.h'\fP
.br
\fC#include 'bluerobin\&.h'\fP
.br
\fC#include 'rfsimpliciti\&.h'\fP
.br
\fC#include 'acceleration\&.h'\fP
.br
\fC#include 'rfbsl\&.h'\fP
.br
\fC#include 'countdowntimer\&.h'\fP
.br
\fC#include 'random\&.h'\fP
.br
\fC#include 'agility\&.h'\fP
.br
\fC#include 'miscellaneous\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBFUNCTION\fP(function)   function"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdisplay_nothing\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "u8 \fBupdate_nothing\fP (void)"
.br
.ti -1c
.RI "u8 \fBupdate_time\fP (void)"
.br
.ti -1c
.RI "u8 \fBupdate_stopwatch\fP (void)"
.br
.ti -1c
.RI "u8 \fBupdate_date\fP (void)"
.br
.ti -1c
.RI "u8 \fBupdate_alarm\fP (void)"
.br
.ti -1c
.RI "u8 \fBupdate_temperature\fP (void)"
.br
.ti -1c
.RI "u8 \fBupdate_battery_voltage\fP (void)"
.br
.ti -1c
.RI "u8 \fBupdate_acceleration\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBmenu\fP * \fBptrMenu_L1\fP = \fBNULL\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP * \fBptrMenu_L2\fP = \fBNULL\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L1_Time\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L1_Alarm\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L1_Temperature\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L1_Altitude\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L1_Acceleration\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_Date\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_Stopwatch\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_cdtimer\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_agility\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_number_storage\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_random\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_Battery\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_Rf\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_Ppt\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_Sync\fP"
.br
.ti -1c
.RI "struct \fBmenu\fP \fBmenu_L2_RFBSL\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBFUNCTION\fP(function)   function"
.PP
Definition at line 70 of file menu\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void \fBdisplay_nothing\fP (u8line, u8update)"
.PP
Definition at line 82 of file menu\&.c\&.
.SS "u8 \fBupdate_acceleration\fP (void)"
.PP
Definition at line 113 of file menu\&.c\&.
.SS "u8 \fBupdate_alarm\fP (void)"
.PP
Definition at line 101 of file menu\&.c\&.
.SS "u8 \fBupdate_battery_voltage\fP (void)"
.PP
Definition at line 109 of file menu\&.c\&.
.SS "u8 \fBupdate_date\fP (void)"
.PP
Definition at line 97 of file menu\&.c\&.
.SS "u8 \fBupdate_nothing\fP (void)"
.PP
Definition at line 85 of file menu\&.c\&.
.SS "u8 \fBupdate_stopwatch\fP (void)"
.PP
Definition at line 93 of file menu\&.c\&.
.SS "u8 \fBupdate_temperature\fP (void)"
.PP
Definition at line 105 of file menu\&.c\&.
.SS "u8 \fBupdate_time\fP (void)"
.PP
Definition at line 89 of file menu\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBmenu\fP \fBmenu_L1_Acceleration\fP"\fBInitial value:\fP
.PP
.nf

{
         sx_acceleration ,                      
         dummy ,                                        
         display_acceleration ,         
         update_acceleration ,          
        &menu_L1_Time,
}
.fi
.PP
Definition at line 186 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L1_Alarm\fP"\fBInitial value:\fP
.PP
.nf

{
         sx_alarm ,                     
         mx_alarm ,                     
         display_alarm ,        
         update_alarm ,         
        &menu_L1_Temperature,
}
.fi
.PP
Definition at line 140 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L1_Altitude\fP"\fBInitial value:\fP
.PP
.nf

{
         sx_altitude ,                          
         mx_altitude ,                          
         display_altitude ,                     
         update_time ,                          
        &menu_L1_Acceleration,

}
.fi
.PP
Definition at line 158 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L1_Temperature\fP"\fBInitial value:\fP
.PP
.nf

{
         dummy ,                                        
         mx_temperature ,                       
         display_temperature ,          
         update_temperature ,           
        &menu_L1_Altitude,
}
.fi
.PP
Definition at line 149 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L1_Time\fP"\fBInitial value:\fP
.PP
.nf

{
         sx_time ,                      
         mx_time ,                      
         display_time ,         
         update_time ,          
        &menu_L1_Alarm,
}
.fi
.PP
Definition at line 131 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_agility\fP"\fBInitial value:\fP
.PP
.nf

{
         sx_agility ,               
         mx_agility ,           
         display_agility ,      
         update_time ,          
        &menu_L2_number_storage,
}
.fi
.PP
Definition at line 223 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_Battery\fP"\fBInitial value:\fP
.PP
.nf

{
         dummy ,                                        
         dummy ,                                        
         display_battery_V ,            
         update_battery_voltage ,       
        &menu_L2_Rf,
}
.fi
.PP
Definition at line 250 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_cdtimer\fP"\fBInitial value:\fP
.PP
.nf

{
         sx_cdtimer ,           
         mx_cdtimer ,           
         display_cdtimer ,  
         update_time ,      
        &menu_L2_agility,
}
.fi
.PP
Definition at line 214 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_Date\fP"\fBInitial value:\fP
.PP
.nf

{
         sx_date ,                      
         mx_date ,                      
         display_date ,         
         update_date ,          
        &menu_L2_Stopwatch,
}
.fi
.PP
Definition at line 196 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_number_storage\fP"\fBInitial value:\fP
.PP
.nf

{
         sx_number_storage ,            
         mx_number_storage ,        
         display_number_storage ,   
         update_nothing ,           
        &menu_L2_random,
}
.fi
.PP
Definition at line 232 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_Ppt\fP"\fBInitial value:\fP
.PP
.nf

{
         sx_ppt ,                               
         dummy ,                                
         display_ppt ,                  
         update_time ,                  
        &menu_L2_Sync,
}
.fi
.PP
Definition at line 268 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_random\fP"\fBInitial value:\fP
.PP
.nf

{
         sx_random ,                
         mx_random ,            
         display_random ,       
         update_time ,          
        &menu_L2_Battery,
}
.fi
.PP
Definition at line 241 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_Rf\fP"\fBInitial value:\fP
.PP
.nf

{
         sx_rf ,                                
         dummy ,                                
         display_rf ,                   
         update_time ,                  
        &menu_L2_Ppt,
}
.fi
.PP
Definition at line 259 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_RFBSL\fP"\fBInitial value:\fP
.PP
.nf

{
         sx_rfbsl ,                             
         dummy ,                                
         display_rfbsl ,                
         update_time ,                  
        &menu_L2_Date,
}
.fi
.PP
Definition at line 296 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_Stopwatch\fP"\fBInitial value:\fP
.PP
.nf

{
         sx_stopwatch ,         
         mx_stopwatch ,         
         display_stopwatch ,
         update_stopwatch ,     
        &menu_L2_cdtimer,
}
.fi
.PP
Definition at line 205 of file menu\&.c\&.
.SS "struct \fBmenu\fP \fBmenu_L2_Sync\fP"\fBInitial value:\fP
.PP
.nf

{
         sx_sync ,                              
         mx_sync ,                              
         display_sync ,                 
         update_time ,                  
        &menu_L2_RFBSL,

}
.fi
.PP
Definition at line 277 of file menu\&.c\&.
.SS "struct \fBmenu\fP* \fBptrMenu_L1\fP = \fBNULL\fP"
.PP
Definition at line 75 of file menu\&.c\&.
.SS "struct \fBmenu\fP* \fBptrMenu_L2\fP = \fBNULL\fP"
.PP
Definition at line 76 of file menu\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
