.TH "persistentContext_t" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
persistentContext_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBuint8_t\fP \fBstructureVersion\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBnumConnections\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBcurNextLinkPort\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBcurMaxReplyPort\fP"
.br
.ti -1c
.RI "\fBlinkID_t\fP \fBnextLinkID\fP"
.br
.ti -1c
.RI "\fBconnInfo_t\fP \fBconnStruct\fP [(NUM_CONNECTIONS+1)]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 120 of file nwk\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBconnInfo_t\fP \fBconnStruct\fP[(NUM_CONNECTIONS+1)]"
.PP
Definition at line 138 of file nwk\&.c\&.
.SS "\fBuint8_t\fP \fBcurMaxReplyPort\fP"
.PP
Definition at line 132 of file nwk\&.c\&.
.SS "\fBuint8_t\fP \fBcurNextLinkPort\fP"
.PP
Definition at line 131 of file nwk\&.c\&.
.SS "\fBlinkID_t\fP \fBnextLinkID\fP"
.PP
Definition at line 133 of file nwk\&.c\&.
.SS "\fBuint8_t\fP \fBnumConnections\fP"
.PP
Definition at line 123 of file nwk\&.c\&.
.SS "const \fBuint8_t\fP \fBstructureVersion\fP"
.PP
Definition at line 122 of file nwk\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
