.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/driver/ports.c" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/driver/ports.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include 'ports\&.h'\fP
.br
\fC#include 'buzzer\&.h'\fP
.br
\fC#include 'vti_as\&.h'\fP
.br
\fC#include 'vti_ps\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'clock\&.h'\fP
.br
\fC#include 'alarm\&.h'\fP
.br
\fC#include 'rfsimpliciti\&.h'\fP
.br
\fC#include 'simpliciti\&.h'\fP
.br
\fC#include 'altitude\&.h'\fP
.br
\fC#include 'stopwatch\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBIRQ_TRIGGERED\fP(flags, bit)   ((flags & bit) == bit)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbutton_repeat_on\fP (\fBu16\fP msec)"
.br
.ti -1c
.RI "void \fBbutton_repeat_off\fP (void)"
.br
.ti -1c
.RI "void \fBbutton_repeat_function\fP (void)"
.br
.ti -1c
.RI "void \fBinit_buttons\fP (void)"
.br
.ti -1c
.RI "__interrupt void \fBPORT2_ISR\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile \fBs_button_flags\fP \fBbutton\fP"
.br
.ti -1c
.RI "struct \fBstruct_button\fP \fBsButton\fP"
.br
.ti -1c
.RI "void(* \fBfptr_Timer0_A3_function\fP )(void)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBIRQ_TRIGGERED\fP(flags, bit)   ((flags & bit) == bit)"
.PP
Definition at line 73 of file ports\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void \fBbutton_repeat_function\fP (void)"
.PP
Definition at line 376 of file ports\&.c\&.
.SS "void \fBbutton_repeat_off\fP (void)"
.PP
Definition at line 359 of file ports\&.c\&.
.SS "void \fBbutton_repeat_on\fP (\fBu16\fPmsec)"
.PP
Definition at line 340 of file ports\&.c\&.
.SS "void \fBinit_buttons\fP (void)"
.PP
Definition at line 93 of file ports\&.c\&.
.SS "__interrupt void \fBPORT2_ISR\fP (void)"
.PP
Definition at line 125 of file ports\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "volatile \fBs_button_flags\fP \fBbutton\fP"
.PP
Definition at line 78 of file ports\&.c\&.
.SS "void(* \fBfptr_Timer0_A3_function\fP)(void)"
.PP
Definition at line 76 of file timer\&.c\&.
.SS "struct \fBstruct_button\fP \fBsButton\fP"
.PP
Definition at line 79 of file ports\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
