.TH "RFsmpl" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RFsmpl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'rfsimpliciti\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsimpliciti_mode_t\fP \fBmode\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBtimeout\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file rfsimpliciti\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBsimpliciti_mode_t\fP \fBmode\fP"
.PP
Definition at line 86 of file rfsimpliciti\&.h\&.
.SS "\fBu16\fP \fBtimeout\fP"
.PP
Definition at line 89 of file rfsimpliciti\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
