.TH "s_request_flags" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_request_flags \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'project\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBu16\fP \fBtemperature_measurement\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBvoltage_measurement\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBaltitude_measurement\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBacceleration_measurement\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBbuzzer\fP: 1"
.br
.ti -1c
.RI "} \fBflag\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBall_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 100 of file project\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBu16\fP \fBacceleration_measurement\fP"
.PP
Definition at line 107 of file project\&.h\&.
.SS "\fBu16\fP \fBall_flags\fP"
.PP
Definition at line 110 of file project\&.h\&.
.SS "\fBu16\fP \fBaltitude_measurement\fP"
.PP
Definition at line 106 of file project\&.h\&.
.SS "\fBu16\fP \fBbuzzer\fP"
.PP
Definition at line 108 of file project\&.h\&.
.SS "struct { \&.\&.\&. }   \fBflag\fP"
.SS "\fBu16\fP \fBtemperature_measurement\fP"
.PP
Definition at line 104 of file project\&.h\&.
.SS "\fBu16\fP \fBvoltage_measurement\fP"
.PP
Definition at line 105 of file project\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
