.TH "s_system_flags" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_system_flags \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'project\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBu16\fP \fBidle_timeout\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBidle_timeout_enabled\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBlock_buttons\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBmask_buzzer\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBup_down_repeat_enabled\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBlow_battery\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBuse_metric_units\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBdelay_over\fP: 1"
.br
.ti -1c
.RI "} \fBflag\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBall_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file project\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBu16\fP \fBall_flags\fP"
.PP
Definition at line 94 of file project\&.h\&.
.SS "\fBu16\fP \fBdelay_over\fP"
.PP
Definition at line 92 of file project\&.h\&.
.SS "struct { \&.\&.\&. }   \fBflag\fP"
.SS "\fBu16\fP \fBidle_timeout\fP"
.PP
Definition at line 85 of file project\&.h\&.
.SS "\fBu16\fP \fBidle_timeout_enabled\fP"
.PP
Definition at line 86 of file project\&.h\&.
.SS "\fBu16\fP \fBlock_buttons\fP"
.PP
Definition at line 87 of file project\&.h\&.
.SS "\fBu16\fP \fBlow_battery\fP"
.PP
Definition at line 90 of file project\&.h\&.
.SS "\fBu16\fP \fBmask_buzzer\fP"
.PP
Definition at line 88 of file project\&.h\&.
.SS "\fBu16\fP \fBup_down_repeat_enabled\fP"
.PP
Definition at line 89 of file project\&.h\&.
.SS "\fBu16\fP \fBuse_metric_units\fP"
.PP
Definition at line 91 of file project\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
