.TH "/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/mrfi/smartrf/CC430/smartrf_CC430.h" 3 "Sat Jun 22 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/francispapineau/Documents/4th year project/Source Code/Black-Box-Mouse-Interface/Original Code/V2.2/simpliciti/Components/mrfi/smartrf/CC430/smartrf_CC430.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSMARTRF_RADIO_CC430\fP"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FSCTRL1\fP   0x08"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FSCTRL0\fP   0x00"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_MDMCFG4\fP   0x7B"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_MDMCFG3\fP   0x83"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_MDMCFG2\fP   0x13"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_MDMCFG1\fP   0x22"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_MDMCFG0\fP   0xF8"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_CHANNR\fP   0x00"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_DEVIATN\fP   0x42"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FREND1\fP   0xB6"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FREND0\fP   0x10"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_MCSM0\fP   0x18"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FOCCFG\fP   0x1D"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_BSCFG\fP   0x1C"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_AGCCTRL2\fP   0xC7"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_AGCCTRL1\fP   0x00"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_AGCCTRL0\fP   0xB2"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FSCAL3\fP   0xEA"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FSCAL2\fP   0x2A"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FSCAL1\fP   0x00"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FSCAL0\fP   0x1F"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FSTEST\fP   0x59"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_TEST2\fP   0x81"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_TEST1\fP   0x35"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_TEST0\fP   0x09"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_FIFOTHR\fP   0x47"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_IOCFG2\fP   0x29"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_IOCFG0D\fP   0x06"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_PKTCTRL1\fP   0x04"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_PKTCTRL0\fP   0x05"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_ADDR\fP   0x00"
.br
.ti -1c
.RI "#define \fBSMARTRF_SETTING_PKTLEN\fP   0xFF"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBSMARTRF_RADIO_CC430\fP"
.PP
Definition at line 107 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_ADDR\fP   0x00"
.PP
Definition at line 161 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_AGCCTRL0\fP   0xB2"
.PP
Definition at line 147 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_AGCCTRL1\fP   0x00"
.PP
Definition at line 146 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_AGCCTRL2\fP   0xC7"
.PP
Definition at line 145 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_BSCFG\fP   0x1C"
.PP
Definition at line 144 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_CHANNR\fP   0x00"
.PP
Definition at line 138 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_DEVIATN\fP   0x42"
.PP
Definition at line 139 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FIFOTHR\fP   0x47"
.PP
Definition at line 156 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FOCCFG\fP   0x1D"
.PP
Definition at line 143 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FREND0\fP   0x10"
.PP
Definition at line 141 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FREND1\fP   0xB6"
.PP
Definition at line 140 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FSCAL0\fP   0x1F"
.PP
Definition at line 151 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FSCAL1\fP   0x00"
.PP
Definition at line 150 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FSCAL2\fP   0x2A"
.PP
Definition at line 149 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FSCAL3\fP   0xEA"
.PP
Definition at line 148 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FSCTRL0\fP   0x00"
.PP
Definition at line 110 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FSCTRL1\fP   0x08"
.PP
Definition at line 109 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_FSTEST\fP   0x59"
.PP
Definition at line 152 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_IOCFG0D\fP   0x06"
.PP
Definition at line 158 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_IOCFG2\fP   0x29"
.PP
Definition at line 157 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_MCSM0\fP   0x18"
.PP
Definition at line 142 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_MDMCFG0\fP   0xF8"
.PP
Definition at line 137 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_MDMCFG1\fP   0x22"
.PP
Definition at line 136 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_MDMCFG2\fP   0x13"
.PP
Definition at line 135 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_MDMCFG3\fP   0x83"
.PP
Definition at line 134 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_MDMCFG4\fP   0x7B"
.PP
Definition at line 133 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_PKTCTRL0\fP   0x05"
.PP
Definition at line 160 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_PKTCTRL1\fP   0x04"
.PP
Definition at line 159 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_PKTLEN\fP   0xFF"
.PP
Definition at line 162 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_TEST0\fP   0x09"
.PP
Definition at line 155 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_TEST1\fP   0x35"
.PP
Definition at line 154 of file smartrf_CC430\&.h\&.
.SS "#define \fBSMARTRF_SETTING_TEST2\fP   0x81"
.PP
Definition at line 153 of file smartrf_CC430\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
