.TH "alarm" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
alarm \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'alarm\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBstate\fP"
.br
.ti -1c
.RI "u8 \fBduration\fP"
.br
.ti -1c
.RI "u8 \fBhour\fP"
.br
.ti -1c
.RI "u8 \fBminute\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 69 of file alarm\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u8 \fBduration\fP"
.PP
Definition at line 74 of file alarm\&.h\&.
.SS "u8 \fBhour\fP"
.PP
Definition at line 76 of file alarm\&.h\&.
.SS "u8 \fBminute\fP"
.PP
Definition at line 78 of file alarm\&.h\&.
.SS "u8 \fBstate\fP"
.PP
Definition at line 72 of file alarm\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
