.TH "Original Code/V2.2/logic/bluerobin.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/logic/bluerobin.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <project\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBbr\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBUSER_SEX_MALE\fP   0"
.br
.ti -1c
.RI "#define \fBUSER_SEX_FEMALE\fP   1"
.br
.ti -1c
.RI "#define \fBUSER_WEIGHT_MIN_KG\fP   30"
.br
.ti -1c
.RI "#define \fBUSER_WEIGHT_MAX_KG\fP   150"
.br
.ti -1c
.RI "#define \fBUSER_WEIGHT_MIN_LB\fP   70"
.br
.ti -1c
.RI "#define \fBUSER_WEIGHT_MAX_LB\fP   400"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBlueRobin_state_t\fP { \fBBLUEROBIN_OFF\fP =  0, \fBBLUEROBIN_SEARCHING\fP, \fBBLUEROBIN_CONNECTED\fP, \fBBLUEROBIN_ERROR\fP, \fBBLUEROBIN_OFF\fP =  0, \fBBLUEROBIN_SEARCHING\fP, \fBBLUEROBIN_CONNECTED\fP, \fBBLUEROBIN_ERROR\fP }"
.br
.ti -1c
.RI "enum \fBBlueRobin_update_t\fP { \fBBLUEROBIN_NO_UPDATE\fP =  0, \fBBLUEROBIN_NEW_DATA\fP, \fBBLUEROBIN_NO_UPDATE\fP =  0, \fBBLUEROBIN_NEW_DATA\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreset_bluerobin\fP (void)"
.br
.ti -1c
.RI "void \fBmx_bluerobin\fP (u8 line)"
.br
.ti -1c
.RI "void \fBsx_bluerobin\fP (u8 line)"
.br
.ti -1c
.RI "void \fBmx_caldist\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_heartrate\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBdisplay_speed\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBsx_caldist\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_caldist\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "u8 \fBis_bluerobin\fP (void)"
.br
.ti -1c
.RI "u8 \fBis_bluerobin_searching\fP (void)"
.br
.ti -1c
.RI "void \fBget_bluerobin_data\fP (void)"
.br
.ti -1c
.RI "void \fBstop_bluerobin\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBbr\fP \fBsBlueRobin\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBUSER_SEX_FEMALE\fP   1"
.PP
Definition at line 82 of file bluerobin\&.h\&.
.SS "#define \fBUSER_SEX_MALE\fP   0"
.PP
Definition at line 81 of file bluerobin\&.h\&.
.SS "#define \fBUSER_WEIGHT_MAX_KG\fP   150"
.PP
Definition at line 84 of file bluerobin\&.h\&.
.SS "#define \fBUSER_WEIGHT_MAX_LB\fP   400"
.PP
Definition at line 86 of file bluerobin\&.h\&.
.SS "#define \fBUSER_WEIGHT_MIN_KG\fP   30"
.PP
Definition at line 83 of file bluerobin\&.h\&.
.SS "#define \fBUSER_WEIGHT_MIN_LB\fP   70"
.PP
Definition at line 85 of file bluerobin\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBBlueRobin_state_t\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIBLUEROBIN_OFF \fP\fP
.TP
\fB\fIBLUEROBIN_SEARCHING \fP\fP
.TP
\fB\fIBLUEROBIN_CONNECTED \fP\fP
.TP
\fB\fIBLUEROBIN_ERROR \fP\fP
.TP
\fB\fIBLUEROBIN_OFF \fP\fP
.TP
\fB\fIBLUEROBIN_SEARCHING \fP\fP
.TP
\fB\fIBLUEROBIN_CONNECTED \fP\fP
.TP
\fB\fIBLUEROBIN_ERROR \fP\fP

.PP
Definition at line 66 of file bluerobin\&.h\&.
.SS "enum \fBBlueRobin_update_t\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIBLUEROBIN_NO_UPDATE \fP\fP
.TP
\fB\fIBLUEROBIN_NEW_DATA \fP\fP
.TP
\fB\fIBLUEROBIN_NO_UPDATE \fP\fP
.TP
\fB\fIBLUEROBIN_NEW_DATA \fP\fP

.PP
Definition at line 75 of file bluerobin\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBdisplay_caldist\fP (u8line, u8update)"
.PP
Definition at line 545 of file bluerobin\&.c\&.
.SS "void \fBdisplay_heartrate\fP (u8line, u8update)"
.PP
Definition at line 374 of file bluerobin\&.c\&.
.SS "void \fBdisplay_speed\fP (u8line, u8update)"
.PP
Definition at line 414 of file bluerobin\&.c\&.
.SS "void \fBget_bluerobin_data\fP (void)"
.PP
Definition at line 613 of file bluerobin\&.c\&.
.SS "u8 \fBis_bluerobin\fP (void)"
.PP
Definition at line 589 of file bluerobin\&.c\&.
.SS "u8 \fBis_bluerobin_searching\fP (void)"
.PP
Definition at line 601 of file bluerobin\&.c\&.
.SS "void \fBmx_bluerobin\fP (u8line)"
.PP
Definition at line 128 of file bluerobin\&.c\&.
.SS "void \fBmx_caldist\fP (u8line)"
.PP
Definition at line 272 of file bluerobin\&.c\&.
.SS "void \fBreset_bluerobin\fP (void)"
.PP
Definition at line 97 of file bluerobin\&.c\&.
.SS "void \fBstop_bluerobin\fP (void)"
.PP
Definition at line 668 of file bluerobin\&.c\&.
.SS "void \fBsx_bluerobin\fP (u8line)"
.PP
Definition at line 152 of file bluerobin\&.c\&.
.SS "void \fBsx_caldist\fP (u8line)"
.PP
Definition at line 353 of file bluerobin\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBbr\fP \fBsBlueRobin\fP"
.PP
Definition at line 75 of file bluerobin\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
