.TH "Original Code/V2.2/simpliciti/Components/bsp/drivers/code/bsp_buttons.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/simpliciti/Components/bsp/drivers/code/bsp_buttons.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bsp_buttons\&.h'\fP
.br
\fC#include 'bsp_button_defs\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBSP_CONFIG_BUTTON1\fP()   \fB__bsp_BUTTON1_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_CONFIG_BUTTON2\fP()   \fB__bsp_BUTTON2_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_CONFIG_BUTTON3\fP()   \fB__bsp_BUTTON3_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_CONFIG_BUTTON4\fP()   \fB__bsp_BUTTON4_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_CONFIG_BUTTON5\fP()   \fB__bsp_BUTTON5_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_CONFIG_BUTTON6\fP()   \fB__bsp_BUTTON6_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_CONFIG_BUTTON7\fP()   \fB__bsp_BUTTON7_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_CONFIG_BUTTON8\fP()   \fB__bsp_BUTTON8_CONFIG__\fP()"
.br
.ti -1c
.RI "#define \fBBSP_BUTTON_EXTENDED_CONFIG\fP()"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBSP_InitButtons\fP (void)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBBSP_BUTTON_EXTENDED_CONFIG\fP()"
.PP
Definition at line 62 of file bsp_buttons\&.c\&.
.SS "#define \fBBSP_CONFIG_BUTTON1\fP()   \fB__bsp_BUTTON1_CONFIG__\fP()"
.PP
Definition at line 50 of file bsp_buttons\&.c\&.
.SS "#define \fBBSP_CONFIG_BUTTON2\fP()   \fB__bsp_BUTTON2_CONFIG__\fP()"
.PP
Definition at line 51 of file bsp_buttons\&.c\&.
.SS "#define \fBBSP_CONFIG_BUTTON3\fP()   \fB__bsp_BUTTON3_CONFIG__\fP()"
.PP
Definition at line 52 of file bsp_buttons\&.c\&.
.SS "#define \fBBSP_CONFIG_BUTTON4\fP()   \fB__bsp_BUTTON4_CONFIG__\fP()"
.PP
Definition at line 53 of file bsp_buttons\&.c\&.
.SS "#define \fBBSP_CONFIG_BUTTON5\fP()   \fB__bsp_BUTTON5_CONFIG__\fP()"
.PP
Definition at line 54 of file bsp_buttons\&.c\&.
.SS "#define \fBBSP_CONFIG_BUTTON6\fP()   \fB__bsp_BUTTON6_CONFIG__\fP()"
.PP
Definition at line 55 of file bsp_buttons\&.c\&.
.SS "#define \fBBSP_CONFIG_BUTTON7\fP()   \fB__bsp_BUTTON7_CONFIG__\fP()"
.PP
Definition at line 56 of file bsp_buttons\&.c\&.
.SS "#define \fBBSP_CONFIG_BUTTON8\fP()   \fB__bsp_BUTTON8_CONFIG__\fP()"
.PP
Definition at line 57 of file bsp_buttons\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void \fBBSP_InitButtons\fP (void)"
.PP
Definition at line 76 of file bsp_buttons\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
