.TH "cdtimer" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cdtimer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'countdowntimer\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBstate\fP"
.br
.ti -1c
.RI "u8 \fBmode\fP"
.br
.ti -1c
.RI "u8 \fBdrawFlag\fP"
.br
.ti -1c
.RI "u8 \fBtime\fP [6]"
.br
.ti -1c
.RI "u8 \fBdefaultTime\fP [6]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 70 of file countdowntimer\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u8 \fBdefaultTime\fP[6]"
.PP
Definition at line 85 of file countdowntimer\&.h\&.
.SS "u8 \fBdrawFlag\fP"
.PP
Definition at line 74 of file countdowntimer\&.h\&.
.SS "u8 \fBmode\fP"
.PP
Definition at line 73 of file countdowntimer\&.h\&.
.SS "u8 \fBstate\fP"
.PP
Definition at line 72 of file countdowntimer\&.h\&.
.SS "u8 \fBtime\fP[6]"
.PP
Definition at line 82 of file countdowntimer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
