.TH "Original Code/V2.2/logic/date.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/logic/date.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'ports\&.h'\fP
.br
\fC#include 'date\&.h'\fP
.br
\fC#include 'clock\&.h'\fP
.br
\fC#include 'user\&.h'\fP
.br
\fC#include 'display2\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAX_LANGUAGES\fP   6"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreset_date\fP (void)"
.br
.ti -1c
.RI "u8 \fBget_numberOfDays\fP (u8 month, \fBu16\fP year)"
.br
.ti -1c
.RI "void \fBadd_day\fP (void)"
.br
.ti -1c
.RI "void \fBmx_date\fP (u8 line)"
.br
.ti -1c
.RI "void \fBsx_date\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_date\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBdisplay_time_line2\fP (u8 TimeLine2ViewStyle)"
.br
.ti -1c
.RI "void \fBdisplay_DayOfWeek\fP (u8 segments, u32 value, u8 digits, u8 blanks)"
.br
.ti -1c
.RI "void \fBdisplay_DayOfWeek_Language\fP (u8 segments, u32 value, u8 digits, u8 blanks)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "__no_init struct \fBdate\fP \fBsDate\fP"
.br
.ti -1c
.RI "__no_init u8 \fBSecondTimeOffset\fP"
.br
.ti -1c
.RI "s32 \fBDoW_Language\fP = 0"
.br
.ti -1c
.RI "const u8 \fBDayStr\fP [6][7][3]"
.br
.ti -1c
.RI "void(* \fBfptr_lcd_function_line1\fP )(u8 line, u8 update)"
.br
.ti -1c
.RI "void(* \fBfptr_lcd_function_line2\fP )(u8 line, u8 update)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBMAX_LANGUAGES\fP   6"
.PP
Definition at line 70 of file date\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void \fBadd_day\fP (void)"
.PP
Definition at line 395 of file date\&.c\&.
.SS "void \fBdisplay_date\fP (u8line, u8update)"
.PP
Definition at line 582 of file date\&.c\&.
.SS "void \fBdisplay_DayOfWeek\fP (u8segments, u32value, u8digits, u8blanks)"
.PP
Definition at line 314 of file date\&.c\&.
.SS "void \fBdisplay_DayOfWeek_Language\fP (u8segments, u32value, u8digits, u8blanks)"
.PP
Definition at line 331 of file date\&.c\&.
.SS "void \fBdisplay_time_line2\fP (u8TimeLine2ViewStyle)"
.SS "u8 \fBget_numberOfDays\fP (u8month, \fBu16\fPyear)"
.PP
Definition at line 358 of file date\&.c\&.
.SS "void \fBmx_date\fP (u8line)"
.PP
Definition at line 436 of file date\&.c\&.
.SS "void \fBreset_date\fP (void)"
.PP
Definition at line 288 of file date\&.c\&.
.SS "void \fBsx_date\fP (u8line)"
.PP
Definition at line 564 of file date\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const u8 \fBDayStr\fP[6][7][3]"
.PP
Definition at line 86 of file date\&.c\&.
.SS "s32 \fBDoW_Language\fP = 0"
.PP
Definition at line 76 of file date\&.c\&.
.SS "void(* \fBfptr_lcd_function_line1\fP)(u8 line, u8 update)"
.PP
Definition at line 116 of file main\&.c\&.
.SS "void(* \fBfptr_lcd_function_line2\fP)(u8 line, u8 update)"
.PP
Definition at line 117 of file main\&.c\&.
.SS "__no_init struct \fBdate\fP \fBsDate\fP"
.PP
Definition at line 74 of file date\&.c\&.
.SS "__no_init u8 \fBSecondTimeOffset\fP"
.PP
Definition at line 75 of file date\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
