.TH "freqEntry_t" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
freqEntry_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'nwk_types\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBlogicalChan\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 171 of file nwk_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint8_t\fP \fBlogicalChan\fP"
.PP
Definition at line 173 of file nwk_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
