.TH "ioctlScanChan_t" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ioctlScanChan_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'nwk_types\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBnumChan\fP"
.br
.ti -1c
.RI "\fBfreqEntry_t\fP * \fBfreq\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 176 of file nwk_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBfreqEntry_t\fP* \fBfreq\fP"
.PP
Definition at line 179 of file nwk_types\&.h\&.
.SS "\fBuint8_t\fP \fBnumChan\fP"
.PP
Definition at line 178 of file nwk_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
