.TH "ioctlRadioSiginfo_t" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ioctlRadioSiginfo_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'nwk_types\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBlinkID_t\fP \fBlid\fP"
.br
.ti -1c
.RI "\fBrxMetrics_t\fP \fBsigInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 137 of file nwk_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBlinkID_t\fP \fBlid\fP"
.PP
Definition at line 139 of file nwk_types\&.h\&.
.SS "\fBrxMetrics_t\fP \fBsigInfo\fP"
.PP
Definition at line 140 of file nwk_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
