.TH "menu" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
menu \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'menu\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void(* \fBsx_function\fP )(u8 line)"
.br
.ti -1c
.RI "void(* \fBmx_function\fP )(u8 line)"
.br
.ti -1c
.RI "void(* \fBdisplay_function\fP )(u8 line, u8 mode)"
.br
.ti -1c
.RI "u8(* \fBdisplay_update\fP )(void)"
.br
.ti -1c
.RI "struct \fBmenu\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file menu\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void(* \fBdisplay_function\fP)(u8 line, u8 mode)"
.PP
Definition at line 57 of file menu\&.h\&.
.SS "u8(* \fBdisplay_update\fP)(void)"
.PP
Definition at line 59 of file menu\&.h\&.
.SS "void(* \fBmx_function\fP)(u8 line)"
.PP
Definition at line 55 of file menu\&.h\&.
.SS "struct \fBmenu\fP* \fBnext\fP"
.PP
Definition at line 61 of file menu\&.h\&.
.SS "void(* \fBsx_function\fP)(u8 line)"
.PP
Definition at line 53 of file menu\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
