.TH "Original Code/V2.2/simpliciti/Components/mrfi/radios/family5/mrfi_radio_interface.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/simpliciti/Components/mrfi/radios/family5/mrfi_radio_interface.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bsp\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBIOCFG2\fP   0x00      /*  IOCFG2   - GDO2 output pin configuration  */"
.br
.ti -1c
.RI "#define \fBIOCFG1\fP   0x01      /*  IOCFG1   - GDO1 output pin configuration  */"
.br
.ti -1c
.RI "#define \fBIOCFG0\fP   0x02      /*  IOCFG1   - GDO0 output pin configuration  */"
.br
.ti -1c
.RI "#define \fBFIFOTHR\fP   0x03      /*  FIFOTHR  - RX FIFO and TX FIFO thresholds */"
.br
.ti -1c
.RI "#define \fBSYNC1\fP   0x04      /*  SYNC1    - Sync word, high byte */"
.br
.ti -1c
.RI "#define \fBSYNC0\fP   0x05      /*  SYNC0    - Sync word, low byte */"
.br
.ti -1c
.RI "#define \fBPKTLEN\fP   0x06      /*  PKTLEN   - Packet length */"
.br
.ti -1c
.RI "#define \fBPKTCTRL1\fP   0x07      /*  PKTCTRL1 - Packet automation control */"
.br
.ti -1c
.RI "#define \fBPKTCTRL0\fP   0x08      /*  PKTCTRL0 - Packet automation control */"
.br
.ti -1c
.RI "#define \fBADDR\fP   0x09      /*  ADDR     - Device address */"
.br
.ti -1c
.RI "#define \fBCHANNR\fP   0x0A      /*  CHANNR   - Channel number */"
.br
.ti -1c
.RI "#define \fBFSCTRL1\fP   0x0B      /*  FSCTRL1  - Frequency synthesizer control */"
.br
.ti -1c
.RI "#define \fBFSCTRL0\fP   0x0C      /*  FSCTRL0  - Frequency synthesizer control */"
.br
.ti -1c
.RI "#define \fBFREQ2\fP   0x0D      /*  FREQ2    - Frequency control word, high byte */"
.br
.ti -1c
.RI "#define \fBFREQ1\fP   0x0E      /*  FREQ1    - Frequency control word, middle byte */"
.br
.ti -1c
.RI "#define \fBFREQ0\fP   0x0F      /*  FREQ0    - Frequency control word, low byte */"
.br
.ti -1c
.RI "#define \fBMDMCFG4\fP   0x10      /*  MDMCFG4  - Modem configuration */"
.br
.ti -1c
.RI "#define \fBMDMCFG3\fP   0x11      /*  MDMCFG3  - Modem configuration */"
.br
.ti -1c
.RI "#define \fBMDMCFG2\fP   0x12      /*  MDMCFG2  - Modem configuration */"
.br
.ti -1c
.RI "#define \fBMDMCFG1\fP   0x13      /*  MDMCFG1  - Modem configuration */"
.br
.ti -1c
.RI "#define \fBMDMCFG0\fP   0x14      /*  MDMCFG0  - Modem configuration */"
.br
.ti -1c
.RI "#define \fBDEVIATN\fP   0x15      /*  DEVIATN  - Modem deviation setting */"
.br
.ti -1c
.RI "#define \fBMCSM2\fP   0x16      /*  MCSM2    - Main Radio Control State Machine configuration */"
.br
.ti -1c
.RI "#define \fBMCSM1\fP   0x17      /*  MCSM1    - Main Radio Control State Machine configuration */"
.br
.ti -1c
.RI "#define \fBMCSM0\fP   0x18      /*  MCSM0    - Main Radio Control State Machine configuration */"
.br
.ti -1c
.RI "#define \fBFOCCFG\fP   0x19      /*  FOCCFG   - Frequency Offset Compensation configuration */"
.br
.ti -1c
.RI "#define \fBBSCFG\fP   0x1A      /*  BSCFG    - Bit Synchronization configuration */"
.br
.ti -1c
.RI "#define \fBAGCCTRL2\fP   0x1B      /*  AGCCTRL2 - AGC control */"
.br
.ti -1c
.RI "#define \fBAGCCTRL1\fP   0x1C      /*  AGCCTRL1 - AGC control */"
.br
.ti -1c
.RI "#define \fBAGCCTRL0\fP   0x1D      /*  AGCCTRL0 - AGC control */"
.br
.ti -1c
.RI "#define \fBWOREVT1\fP   0x1E      /*  WOREVT1  - High byte Event0 timeout */"
.br
.ti -1c
.RI "#define \fBWOREVT0\fP   0x1F      /*  WOREVT0  - Low byte Event0 timeout */"
.br
.ti -1c
.RI "#define \fBWORCTRL\fP   0x20      /*  WORCTRL  - Wake On Radio control */"
.br
.ti -1c
.RI "#define \fBFREND1\fP   0x21      /*  FREND1   - Front end RX configuration */"
.br
.ti -1c
.RI "#define \fBFREND0\fP   0x22      /*  FREDN0   - Front end TX configuration */"
.br
.ti -1c
.RI "#define \fBFSCAL3\fP   0x23      /*  FSCAL3   - Frequency synthesizer calibration */"
.br
.ti -1c
.RI "#define \fBFSCAL2\fP   0x24      /*  FSCAL2   - Frequency synthesizer calibration */"
.br
.ti -1c
.RI "#define \fBFSCAL1\fP   0x25      /*  FSCAL1   - Frequency synthesizer calibration */"
.br
.ti -1c
.RI "#define \fBFSCAL0\fP   0x26      /*  FSCAL0   - Frequency synthesizer calibration */"
.br
.ti -1c
.RI "#define \fBRCCTRL1\fP   0x27      /*  RCCTRL1  - RC oscillator configuration */"
.br
.ti -1c
.RI "#define \fBRCCTRL0\fP   0x28      /*  RCCTRL0  - RC oscillator configuration */"
.br
.ti -1c
.RI "#define \fBFSTEST\fP   0x29      /*  FSTEST   - Frequency synthesizer calibration control */"
.br
.ti -1c
.RI "#define \fBPTEST\fP   0x2A      /*  PTEST    - Production test */"
.br
.ti -1c
.RI "#define \fBAGCTEST\fP   0x2B      /*  AGCTEST  - AGC test */"
.br
.ti -1c
.RI "#define \fBTEST2\fP   0x2C      /*  TEST2    - Various test settings */"
.br
.ti -1c
.RI "#define \fBTEST1\fP   0x2D      /*  TEST1    - Various test settings */"
.br
.ti -1c
.RI "#define \fBTEST0\fP   0x2E      /*  TEST0    - Various test settings */"
.br
.ti -1c
.RI "#define \fBPARTNUM\fP   0x30      /*  PARTNUM    - Chip ID */"
.br
.ti -1c
.RI "#define \fBVERSION\fP   0x31      /*  VERSION    - Chip ID */"
.br
.ti -1c
.RI "#define \fBFREQEST\fP   0x32      /*  FREQEST    – Frequency Offset Estimate from demodulator */"
.br
.ti -1c
.RI "#define \fBLQI\fP   0x33      /*  LQI        – Demodulator estimate for Link Quality */"
.br
.ti -1c
.RI "#define \fBRSSI\fP   0x34      /*  RSSI       – Received signal strength indication */"
.br
.ti -1c
.RI "#define \fBMARCSTATE\fP   0x35      /*  MARCSTATE  – Main Radio Control State Machine state */"
.br
.ti -1c
.RI "#define \fBWORTIME1\fP   0x36      /*  WORTIME1   – High byte of WOR time */"
.br
.ti -1c
.RI "#define \fBWORTIME0\fP   0x37      /*  WORTIME0   – Low byte of WOR time */"
.br
.ti -1c
.RI "#define \fBPKTSTATUS\fP   0x38      /*  PKTSTATUS  – Current GDOx status and packet status */"
.br
.ti -1c
.RI "#define \fBVCO_VC_DAC\fP   0x39      /*  VCO_VC_DAC – Current setting from PLL calibration module */"
.br
.ti -1c
.RI "#define \fBTXBYTES\fP   0x3A      /*  TXBYTES    – Underflow and number of bytes */"
.br
.ti -1c
.RI "#define \fBRXBYTES\fP   0x3B      /*  RXBYTES    – Overflow and number of bytes */"
.br
.ti -1c
.RI "#define \fBPATABLE\fP   0x3E      /*  PATABLE - PA control settings table */"
.br
.ti -1c
.RI "#define \fBSRES\fP   0x30      /*  SRES    - Reset chip\&. */"
.br
.ti -1c
.RI "#define \fBSFSTXON\fP   0x31      /*  SFSTXON - Enable and calibrate frequency synthesizer\&. */"
.br
.ti -1c
.RI "#define \fBSXOFF\fP   0x32      /*  SXOFF   - Turn off crystal oscillator\&. */"
.br
.ti -1c
.RI "#define \fBSCAL\fP   0x33      /*  SCAL    - Calibrate frequency synthesizer and turn it off\&. */"
.br
.ti -1c
.RI "#define \fBSRX\fP   0x34      /*  SRX     - Enable RX\&. Perform calibration if enabled\&. */"
.br
.ti -1c
.RI "#define \fBSTX\fP   0x35      /*  STX     - Enable TX\&. If in RX state, only enable TX if CCA passes\&. */"
.br
.ti -1c
.RI "#define \fBSIDLE\fP   0x36      /*  SIDLE   - Exit RX / TX, turn off frequency synthesizer\&. */"
.br
.ti -1c
.RI "#define \fBSRSVD\fP   0x37      /*  SRVSD   - Reserved\&.  Do not use\&. */"
.br
.ti -1c
.RI "#define \fBSWOR\fP   0x38      /*  SWOR    - Start automatic RX polling sequence (Wake-on-Radio) */"
.br
.ti -1c
.RI "#define \fBSPWD\fP   0x39      /*  SPWD    - Enter power down mode when CSn goes high\&. */"
.br
.ti -1c
.RI "#define \fBSFRX\fP   0x3A      /*  SFRX    - Flush the RX FIFO buffer\&. */"
.br
.ti -1c
.RI "#define \fBSFTX\fP   0x3B      /*  SFTX    - Flush the TX FIFO buffer\&. */"
.br
.ti -1c
.RI "#define \fBSWORRST\fP   0x3C      /*  SWORRST - Reset real time clock\&. */"
.br
.ti -1c
.RI "#define \fBSNOP\fP   0x3D      /*  SNOP    - No operation\&. Returns status byte\&. */"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmrfiRadioInterfaceInit\fP (void)"
.br
.ti -1c
.RI "void \fBmrfiRadioInterfaceWriteReg\fP (\fBuint8_t\fP addr, \fBuint8_t\fP value)"
.br
.ti -1c
.RI "void \fBmrfiRadioInterfaceWriteTxFifo\fP (\fBuint8_t\fP *pWriteData, \fBuint8_t\fP len)"
.br
.ti -1c
.RI "void \fBmrfiRadioInterfaceReadRxFifo\fP (\fBuint8_t\fP *pReadData, \fBuint8_t\fP len)"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBmrfiRadioInterfaceCmdStrobe\fP (\fBuint8_t\fP addr)"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBmrfiRadioInterfaceReadReg\fP (\fBuint8_t\fP addr)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBADDR\fP   0x09      /*  ADDR     - Device address */"
.PP
Definition at line 63 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBAGCCTRL0\fP   0x1D      /*  AGCCTRL0 - AGC control */"
.PP
Definition at line 83 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBAGCCTRL1\fP   0x1C      /*  AGCCTRL1 - AGC control */"
.PP
Definition at line 82 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBAGCCTRL2\fP   0x1B      /*  AGCCTRL2 - AGC control */"
.PP
Definition at line 81 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBAGCTEST\fP   0x2B      /*  AGCTEST  - AGC test */"
.PP
Definition at line 97 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBBSCFG\fP   0x1A      /*  BSCFG    - Bit Synchronization configuration */"
.PP
Definition at line 80 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBCHANNR\fP   0x0A      /*  CHANNR   - Channel number */"
.PP
Definition at line 64 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBDEVIATN\fP   0x15      /*  DEVIATN  - Modem deviation setting */"
.PP
Definition at line 75 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBFIFOTHR\fP   0x03      /*  FIFOTHR  - RX FIFO and TX FIFO thresholds */"
.PP
Definition at line 57 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBFOCCFG\fP   0x19      /*  FOCCFG   - Frequency Offset Compensation configuration */"
.PP
Definition at line 79 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBFREND0\fP   0x22      /*  FREDN0   - Front end TX configuration */"
.PP
Definition at line 88 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBFREND1\fP   0x21      /*  FREND1   - Front end RX configuration */"
.PP
Definition at line 87 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBFREQ0\fP   0x0F      /*  FREQ0    - Frequency control word, low byte */"
.PP
Definition at line 69 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBFREQ1\fP   0x0E      /*  FREQ1    - Frequency control word, middle byte */"
.PP
Definition at line 68 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBFREQ2\fP   0x0D      /*  FREQ2    - Frequency control word, high byte */"
.PP
Definition at line 67 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBFREQEST\fP   0x32      /*  FREQEST    – Frequency Offset Estimate from demodulator */"
.PP
Definition at line 105 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBFSCAL0\fP   0x26      /*  FSCAL0   - Frequency synthesizer calibration */"
.PP
Definition at line 92 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBFSCAL1\fP   0x25      /*  FSCAL1   - Frequency synthesizer calibration */"
.PP
Definition at line 91 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBFSCAL2\fP   0x24      /*  FSCAL2   - Frequency synthesizer calibration */"
.PP
Definition at line 90 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBFSCAL3\fP   0x23      /*  FSCAL3   - Frequency synthesizer calibration */"
.PP
Definition at line 89 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBFSCTRL0\fP   0x0C      /*  FSCTRL0  - Frequency synthesizer control */"
.PP
Definition at line 66 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBFSCTRL1\fP   0x0B      /*  FSCTRL1  - Frequency synthesizer control */"
.PP
Definition at line 65 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBFSTEST\fP   0x29      /*  FSTEST   - Frequency synthesizer calibration control */"
.PP
Definition at line 95 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBIOCFG0\fP   0x02      /*  IOCFG1   - GDO0 output pin configuration  */"
.PP
Definition at line 56 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBIOCFG1\fP   0x01      /*  IOCFG1   - GDO1 output pin configuration  */"
.PP
Definition at line 55 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBIOCFG2\fP   0x00      /*  IOCFG2   - GDO2 output pin configuration  */"
.PP
Definition at line 54 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBLQI\fP   0x33      /*  LQI        – Demodulator estimate for Link Quality */"
.PP
Definition at line 106 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBMARCSTATE\fP   0x35      /*  MARCSTATE  – Main Radio Control State Machine state */"
.PP
Definition at line 108 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBMCSM0\fP   0x18      /*  MCSM0    - Main Radio Control State Machine configuration */"
.PP
Definition at line 78 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBMCSM1\fP   0x17      /*  MCSM1    - Main Radio Control State Machine configuration */"
.PP
Definition at line 77 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBMCSM2\fP   0x16      /*  MCSM2    - Main Radio Control State Machine configuration */"
.PP
Definition at line 76 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBMDMCFG0\fP   0x14      /*  MDMCFG0  - Modem configuration */"
.PP
Definition at line 74 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBMDMCFG1\fP   0x13      /*  MDMCFG1  - Modem configuration */"
.PP
Definition at line 73 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBMDMCFG2\fP   0x12      /*  MDMCFG2  - Modem configuration */"
.PP
Definition at line 72 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBMDMCFG3\fP   0x11      /*  MDMCFG3  - Modem configuration */"
.PP
Definition at line 71 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBMDMCFG4\fP   0x10      /*  MDMCFG4  - Modem configuration */"
.PP
Definition at line 70 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBPARTNUM\fP   0x30      /*  PARTNUM    - Chip ID */"
.PP
Definition at line 103 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBPATABLE\fP   0x3E      /*  PATABLE - PA control settings table */"
.PP
Definition at line 117 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBPKTCTRL0\fP   0x08      /*  PKTCTRL0 - Packet automation control */"
.PP
Definition at line 62 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBPKTCTRL1\fP   0x07      /*  PKTCTRL1 - Packet automation control */"
.PP
Definition at line 61 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBPKTLEN\fP   0x06      /*  PKTLEN   - Packet length */"
.PP
Definition at line 60 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBPKTSTATUS\fP   0x38      /*  PKTSTATUS  – Current GDOx status and packet status */"
.PP
Definition at line 111 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBPTEST\fP   0x2A      /*  PTEST    - Production test */"
.PP
Definition at line 96 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBRCCTRL0\fP   0x28      /*  RCCTRL0  - RC oscillator configuration */"
.PP
Definition at line 94 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBRCCTRL1\fP   0x27      /*  RCCTRL1  - RC oscillator configuration */"
.PP
Definition at line 93 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBRSSI\fP   0x34      /*  RSSI       – Received signal strength indication */"
.PP
Definition at line 107 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBRXBYTES\fP   0x3B      /*  RXBYTES    – Overflow and number of bytes */"
.PP
Definition at line 114 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSCAL\fP   0x33      /*  SCAL    - Calibrate frequency synthesizer and turn it off\&. */"
.PP
Definition at line 123 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSFRX\fP   0x3A      /*  SFRX    - Flush the RX FIFO buffer\&. */"
.PP
Definition at line 130 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSFSTXON\fP   0x31      /*  SFSTXON - Enable and calibrate frequency synthesizer\&. */"
.PP
Definition at line 121 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSFTX\fP   0x3B      /*  SFTX    - Flush the TX FIFO buffer\&. */"
.PP
Definition at line 131 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSIDLE\fP   0x36      /*  SIDLE   - Exit RX / TX, turn off frequency synthesizer\&. */"
.PP
Definition at line 126 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSNOP\fP   0x3D      /*  SNOP    - No operation\&. Returns status byte\&. */"
.PP
Definition at line 133 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSPWD\fP   0x39      /*  SPWD    - Enter power down mode when CSn goes high\&. */"
.PP
Definition at line 129 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSRES\fP   0x30      /*  SRES    - Reset chip\&. */"
.PP
Definition at line 120 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSRSVD\fP   0x37      /*  SRVSD   - Reserved\&.  Do not use\&. */"
.PP
Definition at line 127 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSRX\fP   0x34      /*  SRX     - Enable RX\&. Perform calibration if enabled\&. */"
.PP
Definition at line 124 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSTX\fP   0x35      /*  STX     - Enable TX\&. If in RX state, only enable TX if CCA passes\&. */"
.PP
Definition at line 125 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSWOR\fP   0x38      /*  SWOR    - Start automatic RX polling sequence (Wake-on-Radio) */"
.PP
Definition at line 128 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSWORRST\fP   0x3C      /*  SWORRST - Reset real time clock\&. */"
.PP
Definition at line 132 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSXOFF\fP   0x32      /*  SXOFF   - Turn off crystal oscillator\&. */"
.PP
Definition at line 122 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSYNC0\fP   0x05      /*  SYNC0    - Sync word, low byte */"
.PP
Definition at line 59 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBSYNC1\fP   0x04      /*  SYNC1    - Sync word, high byte */"
.PP
Definition at line 58 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBTEST0\fP   0x2E      /*  TEST0    - Various test settings */"
.PP
Definition at line 100 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBTEST1\fP   0x2D      /*  TEST1    - Various test settings */"
.PP
Definition at line 99 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBTEST2\fP   0x2C      /*  TEST2    - Various test settings */"
.PP
Definition at line 98 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBTXBYTES\fP   0x3A      /*  TXBYTES    – Underflow and number of bytes */"
.PP
Definition at line 113 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBVCO_VC_DAC\fP   0x39      /*  VCO_VC_DAC – Current setting from PLL calibration module */"
.PP
Definition at line 112 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBVERSION\fP   0x31      /*  VERSION    - Chip ID */"
.PP
Definition at line 104 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBWORCTRL\fP   0x20      /*  WORCTRL  - Wake On Radio control */"
.PP
Definition at line 86 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBWOREVT0\fP   0x1F      /*  WOREVT0  - Low byte Event0 timeout */"
.PP
Definition at line 85 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBWOREVT1\fP   0x1E      /*  WOREVT1  - High byte Event0 timeout */"
.PP
Definition at line 84 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBWORTIME0\fP   0x37      /*  WORTIME0   – Low byte of WOR time */"
.PP
Definition at line 110 of file mrfi_radio_interface\&.h\&.
.SS "#define \fBWORTIME1\fP   0x36      /*  WORTIME1   – High byte of WOR time */"
.PP
Definition at line 109 of file mrfi_radio_interface\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBuint8_t\fP \fBmrfiRadioInterfaceCmdStrobe\fP (\fBuint8_t\fPaddr)"
.PP
Definition at line 110 of file mrfi_radio_interface\&.c\&.
.SS "void \fBmrfiRadioInterfaceInit\fP (void)"
.PP
Definition at line 86 of file mrfi_radio_interface\&.c\&.
.SS "\fBuint8_t\fP \fBmrfiRadioInterfaceReadReg\fP (\fBuint8_t\fPaddr)"
.PP
Definition at line 186 of file mrfi_radio_interface\&.c\&.
.SS "void \fBmrfiRadioInterfaceReadRxFifo\fP (\fBuint8_t\fP *pReadData, \fBuint8_t\fPlen)"
.PP
Definition at line 315 of file mrfi_radio_interface\&.c\&.
.SS "void \fBmrfiRadioInterfaceWriteReg\fP (\fBuint8_t\fPaddr, \fBuint8_t\fPvalue)"
.PP
Definition at line 232 of file mrfi_radio_interface\&.c\&.
.SS "void \fBmrfiRadioInterfaceWriteTxFifo\fP (\fBuint8_t\fP *pWriteData, \fBuint8_t\fPlen)"
.PP
Definition at line 270 of file mrfi_radio_interface\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
