.TH "Original Code/V2.2/simpliciti/Components/nwk/nwk_QMgmt.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/simpliciti/Components/nwk/nwk_QMgmt.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBINQ\fP   1"
.br
.ti -1c
.RI "#define \fBOUTQ\fP   2"
.br
.ti -1c
.RI "#define \fBUSAGE_NORMAL\fP   1"
.br
.ti -1c
.RI "#define \fBUSAGE_FWD\fP   2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnwk_QInit\fP (void)"
.br
.ti -1c
.RI "\fBframeInfo_t\fP * \fBnwk_QfindSlot\fP (\fBuint8_t\fP)"
.br
.ti -1c
.RI "void \fBnwk_QadjustOrder\fP (\fBuint8_t\fP, \fBuint8_t\fP)"
.br
.ti -1c
.RI "\fBframeInfo_t\fP * \fBnwk_QfindOldest\fP (\fBuint8_t\fP, \fBrcvContext_t\fP *, \fBuint8_t\fP)"
.br
.ti -1c
.RI "\fBframeInfo_t\fP * \fBnwk_getQ\fP (\fBuint8_t\fP)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBINQ\fP   1"
.PP
Definition at line 40 of file nwk_QMgmt\&.h\&.
.SS "#define \fBOUTQ\fP   2"
.PP
Definition at line 41 of file nwk_QMgmt\&.h\&.
.SS "#define \fBUSAGE_FWD\fP   2"
.PP
Definition at line 44 of file nwk_QMgmt\&.h\&.
.SS "#define \fBUSAGE_NORMAL\fP   1"
.PP
Definition at line 43 of file nwk_QMgmt\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBframeInfo_t\fP* \fBnwk_getQ\fP (\fBuint8_t\fP)"
.PP
Definition at line 413 of file nwk_QMgmt\&.c\&.
.SS "void \fBnwk_QadjustOrder\fP (\fBuint8_t\fP, \fBuint8_t\fP)"
.PP
Definition at line 217 of file nwk_QMgmt\&.c\&.
.SS "\fBframeInfo_t\fP* \fBnwk_QfindOldest\fP (\fBuint8_t\fP, \fBrcvContext_t\fP *, \fBuint8_t\fP)"
.PP
Definition at line 268 of file nwk_QMgmt\&.c\&.
.SS "\fBframeInfo_t\fP* \fBnwk_QfindSlot\fP (\fBuint8_t\fP)"
.PP
Definition at line 124 of file nwk_QMgmt\&.c\&.
.SS "void \fBnwk_QInit\fP (void)"
.PP
Definition at line 97 of file nwk_QMgmt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
