.TH "Original Code/V2.2/simpliciti/Components/nwk/nwk_globals.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/simpliciti/Components/nwk/nwk_globals.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'bsp\&.h'\fP
.br
\fC#include 'mrfi\&.h'\fP
.br
\fC#include 'nwk_types\&.h'\fP
.br
\fC#include 'nwk_globals\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnwk_globalsInit\fP (void)"
.br
.ti -1c
.RI "\fBaddr_t\fP const * \fBnwk_getMyAddress\fP (void)"
.br
.ti -1c
.RI "\fBuint8_t\fP const * \fBnwk_getFWVersion\fP ()"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBnwk_getProtocolVersion\fP (void)"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBnwk_setMyAddress\fP (\fBaddr_t\fP *addr)"
.br
.ti -1c
.RI "void \fBnwk_setAPAddress\fP (\fBaddr_t\fP *addr)"
.br
.ti -1c
.RI "\fBaddr_t\fP const * \fBnwk_getAPAddress\fP (void)"
.br
.ti -1c
.RI "\fBaddr_t\fP const * \fBnwk_getBCastAddress\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const \fBaddr_t\fP \fBsMyROMAddress\fP = THIS_DEVICE_ADDRESS"
.br
.ti -1c
.RI "static \fBaddr_t\fP \fBsAPAddress\fP"
.br
.ti -1c
.RI "static \fBaddr_t\fP \fBsMyRAMAddress\fP"
.br
.ti -1c
.RI "static \fBuint8_t\fP \fBsRAMAddressIsSet\fP = 0"
.br
.ti -1c
.RI "static const \fBsmplVersionInfo_t\fP \fBsVersionInfo\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBaddr_t\fP const* \fBnwk_getAPAddress\fP (void)"
.PP
Definition at line 235 of file nwk_globals\&.c\&.
.SS "\fBaddr_t\fP const* \fBnwk_getBCastAddress\fP (void)"
.PP
Definition at line 255 of file nwk_globals\&.c\&.
.SS "\fBuint8_t\fP const* \fBnwk_getFWVersion\fP (void)"
.PP
Definition at line 152 of file nwk_globals\&.c\&.
.SS "\fBaddr_t\fP const* \fBnwk_getMyAddress\fP (void)"
.PP
Definition at line 129 of file nwk_globals\&.c\&.
.SS "\fBuint8_t\fP \fBnwk_getProtocolVersion\fP (void)"
.PP
Definition at line 168 of file nwk_globals\&.c\&.
.SS "void \fBnwk_globalsInit\fP (void)"
.PP
Definition at line 99 of file nwk_globals\&.c\&.
.SS "void \fBnwk_setAPAddress\fP (\fBaddr_t\fP *addr)"
.PP
Definition at line 215 of file nwk_globals\&.c\&.
.SS "\fBuint8_t\fP \fBnwk_setMyAddress\fP (\fBaddr_t\fP *addr)"
.PP
Definition at line 189 of file nwk_globals\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBaddr_t\fP \fBsAPAddress\fP\fC [static]\fP"
.PP
Definition at line 61 of file nwk_globals\&.c\&.
.SS "\fBaddr_t\fP \fBsMyRAMAddress\fP\fC [static]\fP"
.PP
Definition at line 62 of file nwk_globals\&.c\&.
.SS "const \fBaddr_t\fP \fBsMyROMAddress\fP = THIS_DEVICE_ADDRESS\fC [static]\fP"
.PP
Definition at line 60 of file nwk_globals\&.c\&.
.SS "\fBuint8_t\fP \fBsRAMAddressIsSet\fP = 0\fC [static]\fP"
.PP
Definition at line 63 of file nwk_globals\&.c\&.
.SS "const \fBsmplVersionInfo_t\fP \fBsVersionInfo\fP\fC [static]\fP"\fBInitial value:\fP
.PP
.nf
 {
                                                0x02,  
                                                0x01,  
                                                0x01,  
                                                0x01,  
                                                0x00   
                                               }
.fi
.PP
Definition at line 68 of file nwk_globals\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
