.TH "Original Code/V2.2/driver/pmm.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/driver/pmm.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cc430x613x\&.h'\fP
.br
\fC#include 'pmm\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSetVCore\fP (unsigned char level)"
.br
.ti -1c
.RI "void \fBSetVCoreUp\fP (unsigned char level)"
.br
.ti -1c
.RI "void \fBSetVCoreDown\fP (unsigned char level)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void \fBSetVCore\fP (unsigned charlevel)"Set the VCore to a new level
.PP
\fBParameters:\fP
.RS 4
\fIlevel\fP PMM level ID 
.RE
.PP

.PP
Definition at line 20 of file pmm\&.c\&.
.SS "static void \fBSetVCoreDown\fP (unsigned charlevel)"Set the VCore to a new Lower level
.PP
\fBParameters:\fP
.RS 4
\fIlevel\fP PMM level ID 
.RE
.PP

.PP
Definition at line 58 of file pmm\&.c\&.
.SS "static void \fBSetVCoreUp\fP (unsigned charlevel)"Set the VCore to a new higher level
.PP
\fBParameters:\fP
.RS 4
\fIlevel\fP PMM level ID 
.RE
.PP

.PP
Definition at line 36 of file pmm\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
