.TH "Original Code/V2.2/logic/random.h" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/logic/random.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <project\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBrandom\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBRANDOM_STOP\fP   (0u)"
.br
.ti -1c
.RI "#define \fBRANDOM_RUN\fP   (1u)"
.br
.ti -1c
.RI "#define \fBMODE_CONTINUE\fP   (0u)"
.br
.ti -1c
.RI "#define \fBMODE_ONCE\fP   (1u)"
.br
.ti -1c
.RI "#define \fBSTYLE_DEFAULT\fP   (0u)"
.br
.ti -1c
.RI "#define \fBSTYLE_ALTERNATE\fP   (1u)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstart_random\fP (void)"
.br
.ti -1c
.RI "void \fBstop_random\fP (void)"
.br
.ti -1c
.RI "void \fBreset_random\fP (void)"
.br
.ti -1c
.RI "void \fBrandom_tick\fP (void)"
.br
.ti -1c
.RI "void \fBmx_random\fP (u8 line)"
.br
.ti -1c
.RI "void \fBsx_random\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_random\fP (u8 line, u8 update)"
.br
.ti -1c
.RI "void \fBset_random\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBrandom\fP \fBsrandom\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBMODE_CONTINUE\fP   (0u)"
.PP
Definition at line 63 of file random\&.h\&.
.SS "#define \fBMODE_ONCE\fP   (1u)"
.PP
Definition at line 64 of file random\&.h\&.
.SS "#define \fBRANDOM_RUN\fP   (1u)"
.PP
Definition at line 61 of file random\&.h\&.
.SS "#define \fBRANDOM_STOP\fP   (0u)"
.PP
Definition at line 60 of file random\&.h\&.
.SS "#define \fBSTYLE_ALTERNATE\fP   (1u)"
.PP
Definition at line 67 of file random\&.h\&.
.SS "#define \fBSTYLE_DEFAULT\fP   (0u)"
.PP
Definition at line 66 of file random\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBdisplay_random\fP (u8line, u8update)"
.PP
Definition at line 254 of file random\&.c\&.
.SS "void \fBmx_random\fP (u8line)"
.PP
Definition at line 183 of file random\&.c\&.
.SS "void \fBrandom_tick\fP (void)"
.PP
Definition at line 91 of file random\&.c\&.
.SS "void \fBreset_random\fP (void)"
.PP
Definition at line 128 of file random\&.c\&.
.SS "void \fBset_random\fP (void)"
.PP
Definition at line 286 of file random\&.c\&.
.SS "void \fBstart_random\fP (void)"
.PP
Definition at line 154 of file random\&.c\&.
.SS "void \fBstop_random\fP (void)"
.PP
Definition at line 169 of file random\&.c\&.
.SS "void \fBsx_random\fP (u8line)"
.PP
Definition at line 206 of file random\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBrandom\fP \fBsrandom\fP"
.PP
Definition at line 79 of file random\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
