.TH "Original Code/V2.2/logic/rfbsl.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/logic/rfbsl.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'ports\&.h'\fP
.br
\fC#include 'rfbsl\&.h'\fP
.br
\fC#include 'bluerobin\&.h'\fP
.br
\fC#include 'rfsimpliciti\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsx_rfbsl\fP (u8 line)"
.br
.ti -1c
.RI "void \fBdisplay_rfbsl\fP (u8 line, u8 update)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBdisplay_rfbsl\fP (u8line, u8update)"
.PP
Definition at line 92 of file rfbsl\&.c\&.
.SS "void \fBsx_rfbsl\fP (u8line)"
.PP
Definition at line 61 of file rfbsl\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
