.TH "s_display_flags" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_display_flags \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'display\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBu16\fP \fBfull_update\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBpartial_update\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBline1_full_update\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBline2_full_update\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBupdate_time\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBupdate_stopwatch\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBupdate_temperature\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBupdate_battery_voltage\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBupdate_date\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBupdate_alarm\fP: 1"
.br
.ti -1c
.RI "   \fBu16\fP \fBupdate_acceleration\fP: 1"
.br
.ti -1c
.RI "} \fBflag\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBall_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 61 of file display\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBu16\fP \fBall_flags\fP"
.PP
Definition at line 82 of file display\&.h\&.
.SS "struct { \&.\&.\&. }   \fBflag\fP"
.SS "\fBu16\fP \fBfull_update\fP"
.PP
Definition at line 66 of file display\&.h\&.
.SS "\fBu16\fP \fBline1_full_update\fP"
.PP
Definition at line 70 of file display\&.h\&.
.SS "\fBu16\fP \fBline2_full_update\fP"
.PP
Definition at line 71 of file display\&.h\&.
.SS "\fBu16\fP \fBpartial_update\fP"
.PP
Definition at line 67 of file display\&.h\&.
.SS "\fBu16\fP \fBupdate_acceleration\fP"
.PP
Definition at line 80 of file display\&.h\&.
.SS "\fBu16\fP \fBupdate_alarm\fP"
.PP
Definition at line 79 of file display\&.h\&.
.SS "\fBu16\fP \fBupdate_battery_voltage\fP"
.PP
Definition at line 77 of file display\&.h\&.
.SS "\fBu16\fP \fBupdate_date\fP"
.PP
Definition at line 78 of file display\&.h\&.
.SS "\fBu16\fP \fBupdate_stopwatch\fP"
.PP
Definition at line 75 of file display\&.h\&.
.SS "\fBu16\fP \fBupdate_temperature\fP"
.PP
Definition at line 76 of file display\&.h\&.
.SS "\fBu16\fP \fBupdate_time\fP"
.PP
Definition at line 74 of file display\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
