.TH "stopwatch" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stopwatch \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'stopwatch\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBstate\fP"
.br
.ti -1c
.RI "u8 \fBdrawFlag\fP"
.br
.ti -1c
.RI "u8 \fBswtIs1Hz\fP"
.br
.ti -1c
.RI "u8 \fBswtIs10Hz\fP"
.br
.ti -1c
.RI "u8 \fBtime\fP [8]"
.br
.ti -1c
.RI "u8 \fBviewStyle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file stopwatch\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u8 \fBdrawFlag\fP"
.PP
Definition at line 71 of file stopwatch\&.h\&.
.SS "u8 \fBstate\fP"
.PP
Definition at line 70 of file stopwatch\&.h\&.
.SS "u8 \fBswtIs10Hz\fP"
.PP
Definition at line 73 of file stopwatch\&.h\&.
.SS "u8 \fBswtIs1Hz\fP"
.PP
Definition at line 72 of file stopwatch\&.h\&.
.SS "u8 \fBtime\fP[8]"
.PP
Definition at line 83 of file stopwatch\&.h\&.
.SS "u8 \fBviewStyle\fP"
.PP
Definition at line 86 of file stopwatch\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
