.TH "time" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
time \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'clock\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u32 \fBsystem_time\fP"
.br
.ti -1c
.RI "u8 \fBdrawFlag\fP"
.br
.ti -1c
.RI "u8 \fBline1ViewStyle\fP"
.br
.ti -1c
.RI "u8 \fBhour\fP"
.br
.ti -1c
.RI "u8 \fBminute\fP"
.br
.ti -1c
.RI "u8 \fBsecond\fP"
.br
.ti -1c
.RI "u32 \fBlast_activity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file clock\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u8 \fBdrawFlag\fP"
.PP
Definition at line 69 of file clock\&.h\&.
.SS "u8 \fBhour\fP"
.PP
Definition at line 75 of file clock\&.h\&.
.SS "u32 \fBlast_activity\fP"
.PP
Definition at line 80 of file clock\&.h\&.
.SS "u8 \fBline1ViewStyle\fP"
.PP
Definition at line 72 of file clock\&.h\&.
.SS "u8 \fBminute\fP"
.PP
Definition at line 76 of file clock\&.h\&.
.SS "u8 \fBsecond\fP"
.PP
Definition at line 77 of file clock\&.h\&.
.SS "u32 \fBsystem_time\fP"
.PP
Definition at line 66 of file clock\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
