.TH "Original Code/V2.2/logic/user.c" 3 "Sun Jun 16 2013" "Version VER 0.0" "Chronos Ti - Original Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Original Code/V2.2/logic/user.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'buzzer\&.h'\fP
.br
\fC#include 'ports\&.h'\fP
.br
\fC#include 'menu\&.h'\fP
.br
\fC#include 'date\&.h'\fP
.br
\fC#include 'clock\&.h'\fP
.br
\fC#include 'user\&.h'\fP
.br
\fC#include 'stopwatch\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBidle_loop\fP (void)"
.br
.ti -1c
.RI "void \fBdummy\fP (u8 line)"
.br
.ti -1c
.RI "void \fBset_value\fP (s32 *value, u8 digits, u8 blanks, s32 limitLow, s32 limitHigh, \fBu16\fP mode, u8 segments, void(*\fBfptr_setValue_display_function1\fP)(u8 segments, u32 value, u8 digits, u8 blanks))"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBdummy\fP (u8line)"
.PP
Definition at line 81 of file user\&.c\&.
.SS "void \fBidle_loop\fP (void)"
.PP
Definition at line 681 of file main\&.c\&.
.SS "void \fBset_value\fP (s32 *value, u8digits, u8blanks, s32limitLow, s32limitHigh, \fBu16\fPmode, u8segments, void(*)(u8 segments, u32 value, u8 digits, u8 blanks)fptr_setValue_display_function1)"
.PP
Definition at line 99 of file user\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chronos Ti - Original Firmware from the source code\&.
